### ISSUE TITLE
Consider releasing 7.2

### ISSUE THREAD

**Issue by jedesah** [scalaz/scalaz#1029]
We are currently blocked on the release of scalaz 7.2 in order to upgrade to specs2 3.x on our codebase. We would really appreciate it if 7.2 was release or at the very least if we could be provided with some kind of timeline on when it will be released.

**Comment by runarorama** [comment]
:+1: Who's capable of cutting a release?

**Comment by xuwei-k** [comment]
+1

I said ["it's a little bit too early to release 7.2.0 final."](https://github.com/scalaz/scalaz/issues/893#issuecomment-72935651) 8 month ago, but now It's almost time for release 7.2.0 final.

**Comment by jedws** [comment]
would be great to hold this off until the FreeT work is in https://github.com/scalaz/scalaz/pull/1035

**Comment by xuwei-k** [comment]
> would be great to hold this off until the FreeT work is in #1035

+1

**Comment by xuwei-k** [comment]
merged #1035. release 7.2.0-M5 or 7.2.0-RC1?

**Comment by jedws** [comment]
@xuwei-k do we think the Future/Task rename #1040 is valuable? if so, I'd wait for that before RC1, so release M5 for now?

**Comment by sellout** [comment]
Another vote for releasing. There are three things off the top of my head that I would immediately benefit from:

* general `Free` improvements (`Free.apply`, removing the `Functor` constraint),
* `FreeT`, and
* being able to use specs2 v3.

**Comment by puffnfresh** [comment]
:+1:

**Comment by tonymorris** [comment]
:+1:

**Comment by jedws** [comment]
Still would love to see #1040 in this, and if possible the unary-kinded MTL stuff <- this one we only have this one chance to get it in.

**Comment by vmarquez** [comment]
I'd very much appreciate getting https://github.com/scalaz/scalaz/pull/1048  merged in for this release.  It would make the stack behavior consistent between RWST and StateT, and since it does change just a couple constraints it breaks backwards compatibility.

**Comment by jedws** [comment]
unary-kinded MTL work is in #1049, please consider for 7.2 inclusion

**Comment by aloiscochard** [comment]
:+1: for getting all the `FreeT` stuffs and all the stack safety fixes before releasing

**Comment by xuwei-k** [comment]
Anyway, I will release 7.2.0-M5

**Comment by xuwei-k** [comment]
> Anyway, I will release 7.2.0-M5

done

- https://github.com/scalaz/scalaz/wiki/7.2.0-M5
- https://groups.google.com/d/topic/scalaz/FQ5yyjlgsGg/discussion

**Comment by jdegoes** [comment]
I recently learned, quite to my astonishment, that 7.2 will *not be the last Scalaz* release! Woohoo!

What that means is, maybe we can release 7.2 now and then release *7.3* a month from now with all the new goodies currently pending review / merging. Win-win!!! :wink: :laughing:

**Comment by runarorama** [comment]
Sammála síðasta ræðumanni

**Comment by purefn** [comment]
+1 for getting Jed's MTL work in. Either that or making 7.3 have a much shorter release cycle.

**Comment by jedws** [comment]
@jdegoes you are of course right, but due to the importance of scalaz to many libraries, and the significant difficulties of coordinating multiple releases of all of them, releasing a backwards-compatible breaking version is a significant event. Anyway, it seems to have brought forward some important stuff. Let's aim to get the release out in a short time-frame.

I think it'd particularly help if people helped triage the outstanding PR list.

**Comment by xuwei-k** [comment]
> but due to the importance of scalaz to many libraries, and the significant difficulties of coordinating multiple releases of all of them, releasing a backwards-compatible breaking version is a significant event.

I agree with jedws.

**Comment by vmarquez** [comment]
I agree with @jedws and @xuwei-k.  I understand the urgency but I'd like to see as much get in as possible and still maintain the reputation of a library that 'just works'.  I've got some bandwidth this weekend to assist with whatever I can help with.  Yak shaving, code reviews, testing the new version against various projects, happy to do whatever. LMK.

**Comment by jdegoes** [comment]
No worries. I would suggest that this sort of approach leads to extremely long release cycles (7.2 has been in development for what, a year?) and massive refactoring for users on each upgrade. The alternative is short release cycles and minor refactoring for each upgrade, which can get annoying but delivers more value faster to users than the alternative.

In any case, I'm happy to review a pull request or two if I get some direction.

**Comment by jedws** [comment]
@jdegoes again, you are not wrong. I'd argue that long release cycles are A Good Thing™ for a library like scalaz that is essentially an alternative stdlib, especially given the number of other cornerstone libraries that are built on top of it.

However, I think we're all in agreement that a 7.2 proper release is or should be imminent – regardless of opinions on when a 7.3 should happen. I'd just like to see the list of open PRs triaged for potential breaking API change, and if they do, then they need to be carefully assessed for whether we want to include them, defer until 7.3 cycle, or abandon them. As far as I can tell, the following should definitely be looked at for 7.1 inclusion:

- [ ] #1040 deprecate all the unsafe methods on Future/Task
- [ ] #849 Add liftEitherT to \/ instances. vs #962 EitherT.fromDisjunction (<- close the former if we're happy with this or revert 962 if we prefer 849)
 
Apart from that, check that any of the existing PRs change the API and if so add them to this list. Otherwise, mark them for closing.

**Comment by xuwei-k** [comment]
I decide 7.2.0 deadline to November. 28th if there is no strong objections.

I mean
- [ ] release 7.2.0-RC1
- [ ] create 7.3.x branch and chenge default branch
- [ ] release 7.2.0 final after a few days from RC1 if no critical issues are found.

**Comment by japgolly** [comment]
Anyone have time to add Scala.JS support? It would be awesome if 7.2.0 came out targeting both JVM and Scala.JS.

Cross-compiling and publishing for Scala.JS is trivial but I'm not sure about the tests; that would need a little investigation.

**Comment by japgolly** [comment]
Ok I'll take this on myself:
I've started cross-compiling Scalaz for Scala.JS over here: https://github.com/scalaz/scalaz/issues/1062
There's are still issues but I'll get it sorted this weekend.

Seeing I'm not adding new features - just cross-compiling - if I get it building with all tests passing can we get this in for 7.2?

**Comment by japgolly** [comment]
Ok slight hiccup at the finishing line for Scala.JS support. Let's drop it for 7.2.0 (I'll just publish under my fork as before) and I'll hound you all again hopefully by 7.2.1 (as it won't affect backward-compatibility).

**Comment by jedws** [comment]
David, what's the issue? What sort of timeline do you think you need to get
it working?

**Comment by japgolly** [comment]
Pop over to #1062 to see the issues. Basically all tests pass except one which is likely a Scala.JS bug. Also for some reason the JS tests don't run in parallel (they should), take ages and hit some stupid 5min timeout in Scala.JS's test runner.

Timeline: It depends.
* If we want the test situation perfected before release, then I'd guess weeks (waiting on new releases from Scala.JS and possibly ScalaCheck - also I'll be overseas and away from dev for 2 weeks starting next week).
* If we accept that everything works and a potential SJS bug isn't Scalaz's problem then we can release now and fix testing later. My branch is a mess but I can clean it up and turn it into a decent PR in about 15 minutes.

**Comment by xuwei-k** [comment]
7.2 is already release candidate. it's too late. I don't want to include scala-js support in 7.2.

**Comment by xuwei-k** [comment]
[7.2.0 final released!](https://groups.google.com/d/topic/scalaz/BXW6BVxYEPE/discussion)
