### ISSUE TITLE
Reducer[C,M] requries Monoid[M] when Semigroup[M] would suffice

### ISSUE THREAD

**Issue by gwils** [scalaz/scalaz#1038]
The Monoid[M] constraint on Reducer[C,M] is too tight. Semigroup[M] is enough.
Reducer[C,M] should be changed to only require Semigroup[M].

I assume scalaz.Reducer is based on https://hackage.haskell.org/package/monoids/docs/Data-Monoid-Reducer.html
but that has been deprecated by https://hackage.haskell.org/package/reducers/docs/Data-Semigroup-Reducer.html

**Comment by refried** [comment]
I think PRs get more attention than Issues do.

**Comment by S11001001** [comment]
Our `Reducer` couples with `Generator`, for which the `zero` is required.  A semigroup-`Reducer` would probably require a semigroup-`Generator` to match.

It might be worth revisiting this in the context of `Foldable`/`Foldable1` in general, which could use more user-controllable ways of delivering elements, but that would be a larger redesign.
