### ISSUE TITLE
[scalaz8] Subtyping-free encoding for typeclasses

### ISSUE THREAD

**Issue by aloiscochard** [scalaz/scalaz#1084]
Hi,

I would like to propose and discuss the following typeclass encoding for the next major version of scalaz:
https://github.com/aloiscochard/scato

Early feedback from @S11001001 and @puffnfresh where positive, I thought it would  be good to discuss it here.

/cc @tonymorris @vmarquez @xuwei-k @runarorama 

Thanks

*I'm interested into discussing purely the encoding of typeclasses for now, this prototype include other things but here I'm talking about `typeclass` and how it's used in `base`*

**Comment by aloiscochard** [comment]
It should be noted that by using this encoding we loose the context bound syntax, I personally think that the correctness we gain outweigh the syntax cost (which is relatively small imo).

**Comment by jbgi** [comment]
Hi Alois,
I learnt a lot exploring your encoding, thanks!

The creation of a [```Monad[OptionT[F, ?]]```](https://github.com/aloiscochard/scato/blob/master/transformers/src/main/scala/OptionTInstances.scala#L15) instances looks quite heavyweight (lots of val) vs using sub-classing.

Is it necessary for the TC-based encoding to work correctly?

**Comment by tonymorris** [comment]
Looks really good. Previous encodings have diverged from any principled approach (subtyping or not) and I think at the very least, it must be accepted that subtyping and implicits do not work well together, so pick one or the other.

My only suggestion is to diversify the different ideas involved in a type-class hierarchy:

* How do we answer questions such as, a `Functor(fmap)` is derivable from an `Applicative`?

* How do other type-classes, such as `MonadTrans` look and work with others?

* How does the encoding work with alt code that uses variance?

I am certain there are other questions and nuances that are pertinent here, but I have them blocked from memory until I next encounter them.

**Comment by aloiscochard** [comment]
@jbgi it is not, we can craft some helper trait were one could implement all method for `Monad` and the inherited classes in a single place.

I do not want to such facilities for now, because
- I does hide the encoding itself (and how things are bound together)
- It's not clear to me if that will not result in explosion of such template, you basically need one for every possible inheritance scheme... we don't want that, so maybe just for the more common case.

Thanks for your feedback Jean-Baptiste!

**Comment by aloiscochard** [comment]
@tonymorris thanks! very good points.

About `MonadTrans` I do plan to experiment with those, for now I'm focusing on IO/Free so if someone want to give it a shot, please let me know.

It is not clear to me how that would work with variance, but that being said, a given method can accept both `TC` enabled classes and other conventional once. That's the probably the path to take for seamless integration (instead of including class with variance with `TC`).

A concrete example should be added in the examples.

About 'a Functor(fmap) is derivable from an Applicative', I'm not sure to understand what you exactly means by this. Maybe could make it more concrete or share your thoughts it more details on IRC?

**Comment by puffnfresh** [comment]
@aloiscochard it's possible to derive `fmap` by implementing `<*>` and `pure`:

```haskell
(<*>) . pure :: Applicative f => (a -> b) -> f a -> f b
```

At the moment that is achieved by overrides:

https://github.com/scalaz/scalaz/blob/series/7.3.x/core/src/main/scala/scalaz/Applicative.scala#L27-L29

Which is pretty convenient, since having to implement each separate method for Functor, Apply, Applicative, Bind, Monad can be annoying and can discourage a fine-grained type-class hierarchy.

**Comment by jbgi** [comment]
@puffnfresh I think this patch should improve things on that front: https://github.com/aloiscochard/scato/pull/2
@aloiscochard what do you think of it?

**Comment by aloiscochard** [comment]
@puffnfresh okay understood, thanks!

As @jbgi pointed out, this can be solved by the approach he started investigationg.
We will post the result here once it gets in scato.

**Comment by aloiscochard** [comment]
@tonymorris @puffnfresh after doing some experiment with @jbgi, I come to the conclusion it's better to leave the default method outside of the typeclass itself in a sort of template trait, that let the enduser the choice of how to compose his instance.

I think this pretty important, it probably mean a bit more boilerplate, but still it's definitly doable to compose those templates during the instantiation of the class.

Here is an example of such template for `Applicative`:
https://github.com/aloiscochard/scato/commit/1a2f377d18441481cb009df76b3b19480e7b400c

How do you feel about this?

More generally, there is still some ongoing investigation about the performance impact of such design (multiple allocation due the val), it is still unclear but I'm putting up benchmark.

There is some caching possibilities, but I with they should be used as a last resort, more on that soon.

**Comment by runarorama** [comment]
This looks very promising. My only question echoes Tony's:

If we already have a `Monad[F]`, how difficult does this make it to get an `Applicative[F]`? The answer in Scalaz 7 is "zero effort", but it comes with other costs. So I'm curious how much more than zero the effort is with this encoding.

**Comment by xuwei-k** [comment]
This is yet another idea.

https://github.com/xuwei-k/scalaz-prototype

**Comment by aloiscochard** [comment]
@runarorama if you have `TC[F, Monad]` in scope, you simply have to ask implicitly for a `TC[F, Applicative` and you'll get it. It will basically be resolved with the help of a `Monad ~~> Applicative`, which in fact simply do `.applicative` on the instance value.

It's totally fine to use the implicit resolution in "user" code, I'm currently looking into benchmarking the performance impact. It is however, not possible to use that implicit resolution when defining, let say an instance of the class `Bar` (for which `Monad` is a super class) for the newtype `Foo` and you have to get `Monad[Foo]` already defined, in this case I would always recommend to refer explicitly to the instance value if possible, in order to avoid initialization issues, example:
https://github.com/aloiscochard/scato/blob/master/free/src/main/scala/monad/FreeInstances.scala#L22

**Comment by aloiscochard** [comment]
@xuwei-k nice! thanks for the effort, I will see if I can integrate this idea to maybe improve reused and have it in place of the template.

But correct me if I'm wrong, I feel like we would still need `TC` to solve the case @runarorama was just describing, right? how do you get an `Functor[M]` from a `Monad[M]` without it?

**Comment by aloiscochard** [comment]
I did just integrate ideas from Kenji into scato, and that give really nice result when one have to define a monad now:
https://github.com/aloiscochard/scato/blob/8df53ae0aa20ee9908b3197fbc4f111078b4f949/base/src/main/scala/clazz/MonadInstancesStdLib.scala

https://github.com/aloiscochard/scato/pull/5

**Comment by aloiscochard** [comment]
FWIW, we could remove entirely the usage of `TC` thanks to @xuwei-k idea and @jbgi guidance.

Here is an other example, where you can see how one can define a `Monad[Maybe]` instance by mixing `MonadClass` on the companion object:
https://github.com/aloiscochard/scato/blob/master/base/src/main/scala/data/MaybeInstances.scala

**Comment by jbgi** [comment]
https://github.com/aloiscochard/scato/pull/8 allow to use the "good" old subtyping encoding (with its performance benefits) but concealed under a parallel template hierarchy, leaving the main type-class hierarchy subtyping-free.

**Comment by jbgi** [comment]
This latter pull request need to be amended, possibly with https://github.com/aloiscochard/scato/pull/9 to work around a scalac bug. This work around mandate that the user specify the function(s) that should be derived by mixin the appropriate trait.

**Comment by aloiscochard** [comment]
@tonymorris @vmarquez @xuwei-k @runarorama @S11001001 @puffnfresh we (thanks for the great help from @jbgi) have solved all the issues raised here following Kenji idea.

I do not see any remaining known issues, I encourage you to look at the current state of `scato`, for example:
https://github.com/aloiscochard/scato/blob/master/base/src/main/scala/clazz/Monad.scala
https://github.com/aloiscochard/scato/blob/master/base/src/main/scala/clazz/MonadClass.scala
https://github.com/aloiscochard/scato/blob/master/base/src/main/scala/clazz/MonadInstancesStdLib.scala
https://github.com/aloiscochard/scato/blob/master/io/src/main/scala/IOInstances.scala

Here is what I propose:
Let's open now a two weeks discussion period, so we can investigate, discus or find any remaining issues with this encoding. If after this period no major objection has been made, or no major issue has been found, we consider this approach as accepted for the initial design of scalaz8.

What you folks think of this?

_It does not mean I expect the development to start on scalaz8, I think we should decide on the modularity aspect next (I'll be happy to expose `scato` approach in an other issue), bu then we should be ready to start the ground work_

**Comment by shajra** [comment]
Hi everyone, I haven't looked all of @aloiscochard's code yet, but I'm becoming more convinced that his scato project is really a strong candidate for a Scalaz 8.  There's a lot of work he's solved for including:

- 1. a better IO/Task with both API and performance improvements
- 2. removing a ton of subtyping (this issue)
- 3. improving monad transformers (as @jbgi noted above)

After agreeing to a module structure for the work, there's a ton more work porting over all the old code and tests to the new base to validate that all the fiddly bits still fit together.

I'd like to help where I can.  This work can seem daunting, but I think it's necessary for all of us doing Scala at work.  I'd really like to have a good FP library with

- no subtyping
- good support for invariant data types (with the standard library more as a second-class citizen)
- a strong bias towards lawful type classes
- enforcement of coherence

**Comment by puffnfresh** [comment]
Quick questions:

* Why does `system.Unsafe.Val` exist? Why does IO need that unsafety?

* Methods like `def kill(): Unit` in things like `Interruptor` make me feel uneasy. If I want to write my own `Interruptor`, I have to step into side-effect land. I don't want to have to do that. These are probably used in the IO interpreter, so we get into a bit of a chicken-egg problem. Can we avoid this?

* How do things like #1110 get solved? I can't see any `MonadReader` or `MonadError` ports - do we have some other test which shows ambiguous implicits being resolved?

I'm going to do some ports soon to figure out more about Scato.

**Comment by purefn** [comment]
@puffnfresh See [ConflictingInstances.scala](https://github.com/aloiscochard/scato/blob/master/examples/src/main/scala/ConflictingInstances.scala) for an example of #1110 being fixed.

**Comment by puffnfresh** [comment]
Where does this code go?

```scala
trait Hierarchy0 {
  implicit def barFoo[F[_]](implicit F: Bar[F]): Foo[F] = ???
}

object Hierarchy extends Hierarchy0 {
  implicit def bazFoo[F[_]](implicit F: Baz[F]): Foo[F] = ???
}
```

Does the user of Scato have to figure out a hierarchy which works for them?

**Comment by puffnfresh** [comment]
Looks like there's a hierarchy built-in:

https://github.com/aloiscochard/scato/blob/master/base/src/main/scala/BaseHierarchy.scala

**Comment by jbgi** [comment]
Some slides I made for a local meetup to summarize the scato encodings (current and previous encoding): https://github.com/jbgi/scato/raw/master/TypeClassesInScato.pdf

**Comment by aloiscochard** [comment]
@puffnfresh those are great questions, and sorry for the late reply ;-)

1. It does exists in order to do some performance optimization in the datastructure used by the interpreters (similar in spirit to what does cat's `Eval`), by using `Val` I'm being at least a bit more explicit by having the rules to always call the constructors by applying all the types. 

2. Yes, I don't like that one either. But `Interruptor`  is not something to be implemented outside of the RTS (it's like playing with `IORef`), in the original impl. "matterhorn", the  RTS was clearly splitted, and it's the only place those insanity are allowed (https://github.com/aloiscochard/matterhorn). I see this code, as a low level interpreter written in C. It should be automatically battle tested as much as possible but as for now I don't see a better way to achieve a similar trade-off.

3. Yes, as you did worked out there is a hierarchy built-in. Again, it's not a perfect solution, especially in term of modularity (which can be mitigated, I think, by having other hirerachies in module's root package object), but that should give use a pretty solid `base`.

Generally speaking, the RTS interpreter internals might be partially rewritable in a less mutable way while retaining similar performance, I'll investigate this.

**Comment by aloiscochard** [comment]
But to the original topic of this issue, which is the type-class encoding, from I can get I think we are reaching the consensus to use it as a basis for scalaz 8.

Please anybody correct me if I'm wrong, or if you see any remaining concerns! ty

**Comment by aloiscochard** [comment]
We started development on `series/8.0.x` branch using this encoding, I close this issue.
