### ISSUE TITLE
Delete Task

### ISSUE THREAD

**Issue by puffnfresh** [scalaz/scalaz#1086]
I think scalaz-stream was the biggest consumer of `scalaz.concurrent.Task`. With scalaz-stream becoming `fs2` and using its own version of `Task`, I think the version in scalaz-concurrent should probably be deleted.

I think a lot of the use-cases for Task can be done better using IO, with a better API. What is IO missing which Task already has?

**Comment by vmarquez** [comment]
There is a lot of Task usage at OnCue separate from projects using scalaz-stream.   It's very convenient for wrapping unsafe asynchronous java APIs and as a safer Future for when we want to explicitly from parallelism. 

 I don't believe it handles Exceptions (encapsulating a disjunction and 'transforming over it')  which is quite useful. 

There is not  way also no way that I know of to explicitly have an IO capture an ExecutionContext (such as fork).

**Comment by pchiusano** [comment]
The other big thing is the `Task.async` function. I suspect this could be implemented with an `MVar`, though might not be as efficient.

I'm not sure if `IO` catches all exceptions like `Task` does, even in pure code. So stuff like `pure(a) map (_ => throw FailWhale)`. And is there an `attempt` function for `IO`? (I haven't checked lately).

Also, fyi, there was some discussion on what throwables `Task` should catch in #659.

**Comment by aloiscochard** [comment]
Do we really want that to tackle this in the current major release of scalaz?

I would prefer if wait for a new consistent design in the next major version, I think we can get much better performance by using an approach like in `matterhorn`.

For what is worth I have just finished porting `StateT` using this design in `scato`, here is the benchmark and it's result:
```
[info] Benchmark             Mode  Cnt   Score   Error  Units
[info] Interpreters.scalaz  thrpt   20  39.925 ± 2.312  ops/s
[info] Interpreters.scato   thrpt   20  58.295 ± 1.290  ops/s
```
https://github.com/aloiscochard/scato/blob/master/benchmarks/src/main/scala/Interpreters.scala

I plan to apply the same approach for IO/Async (as I did in matterhorn), this should make the State/Free interruptable if lifted inside IO, I think that is pretty cool.

Based on those, what I think promising results, do we want to invest much effort now in 7?

**Please it should then be possible to approach a streaming library design more in the vain of the initial `machines` works**

PS: If you look at matterhorn, you'll also see how the exception problem is solved.

**Comment by xuwei-k** [comment]
- https://github.com/scalaz/scalaz/pull/2037
