### ISSUE TITLE
Deadlock on 1-core virtual machine

### ISSUE THREAD

**Issue by raimohanska** [scalaz/scalaz#1105]
I got a nasty deadlock situation when using http4s client on a 1-core virtual machine. The problem is related to using then number of available processors as the size of the default thread pool in [Strategy](https://github.com/scalaz/scalaz/blob/series/7.3.x/concurrent/src/main/scala/scalaz/concurrent/Strategy.scala#L39).

The problem manifests as an application that has just stopped doing stuff. There are no error/warn messages anywhere, nor you can see a deadlock in a thread dump. I took me at least 8 hours to the get the bottom of this :(

I'll be happy to submit a PR for upping this default to at least 4 threads even if there's just a single CPU core available.

**Comment by puffnfresh** [comment]
This code:

1. Uses implicits for configuration
2. Uses side-effects to create a default configuration
3. Is typed as `() => A`

There's not a lot going on for it. I've said this a few times, but I would like to get rid of `Strategy` and `Task`.

**Comment by raimohanska** [comment]
I cannot debate on scalaz architecture yet, as I'm not fully familiar with it

But wouldn't it anyway be an improvement to use at least 2 threads instead of 1 in a single-core case? This is a practical thing that'll cause huge amounts of pain to newbies who cannot possibly guess that the default configuration is prone to deadlocks on a 1-core machine. Deadlocks that'll never occur on the newbie's 8-core laptop.

**Comment by raimohanska** [comment]
I cannot see any possible downsides in defaulting to a threadpool with more than 1 thread.

**Comment by jedws** [comment]
The problem is not so much that the defaults are wrong, but that defaulting
at all is the wrong thing to be doing.

**Comment by pchlupacek** [comment]
@jedws in 7.2 is still the default strategy available? I think it shall be dropped from any next major release. In meantime i think min 4 threads would be completely sensible fix to me.

**Comment by vmarquez** [comment]
I agree with getting rid of the defaults.

**Comment by raimohanska** [comment]
I too agree with getting rid of the default. Submitted a PR for more convenient defaults to avoid nasty deadlocks on 1-core machines anyway. #1139

**Comment by S11001001** [comment]
Fixed by #1139.
