### ISSUE TITLE
How do I contribute?

### ISSUE THREAD

**Issue by JohnReedLOL** [scalaz/scalaz#1118]
Hey,

  I've never contributes to a library before, so I don't know if you have a special form or something or if I can just make a pull request like normal.

  The contribution I want to make is a trace feature much like the one in Haskell: https://hackage.haskell.org/package/base-4.8.2.0/docs/Debug-Trace.html

^ It is like "print" inside of "final class ShowOps[F]", but it also returns the value that it printed. I also want to add trace with a stacktrace so that you can find what you printed.

My contribution looks like this:

// scalaz-series-7.3.x/core/src/main/scala/scalaz/syntax

```
package scalaz
package syntax
/** Wraps a value `self` and provides methods related to `Show` */
final class ShowOps[F] private[syntax](val self: F)(implicit val F: Show[F]) extends Ops[F] {
  ////
  final def show: Cord = F.show(self)
  final def shows: String = F.shows(self)
  final def print: Unit = Console.print(shows)
  final def println: Unit = Console.println(shows)

  /**
    * 1 internal call, 1 thread call, and ShowOps.traceInternal are the three levels of stack trace offset.
    */
  private val stackOffset = 3
  
  /**
    * Prints this (self) and returns this
    * @return this (self)
    */
  final def trace0: F = traceInternal(0)
  /**
    * Prints this (self) with a 1 line stack trace for easy locate-ability and returns this
    * @return this (self)
    */
  final def trace1: F = traceInternal(1)
  /**
    * Prints this (self) with a 1 line stack trace for easy locate-ability and returns this (self). Short for "trace1"
    * @return this (self)
    */
  final def trace: F = traceInternal(1)
  /**
    * Prints this (self) with a 2 line stack trace for easy locate-ability and returns this
    * @return this (self)
    */
  final def trace2: F = traceInternal(2)
  /**
    * Prints this (self) with a 3 line stack trace for easy locate-ability and returns this
    * @return this (self)
    */
  final def trace3: F = traceInternal(3)
  /**
    * Prints this (self) with a 4 line stack trace for easy locate-ability and returns this
    * @return this (self)
    */
  final def trace4: F = traceInternal(4)
  /**
    * Prints this (self) with a 5 line stack trace for easy locate-ability and returns this
    * @return this (self)
    */
  final def trace5: F = traceInternal(5)
  /**
    * Prints this (self) with an n line stack trace for easy locate-ability and returns this
    * @param numStackLines The number of lines of stack trace. No stack trace lines if numStackLines is less than or equal to zero.
    * @return this (self)
    */
  final def traceN(numStackLines: Int): F = traceInternal(numStackLines)

  /**
    * Used internally by other trace statements. Prints this (self) with trace.
    * @param numStackLinesIntended The number of lines of stack trace. No stack trace lines if this is less than or equal to zero.
    * @return this (self)
    */
  private final def traceInternal(numStackLinesIntended: Int): F  = {
    val numStackLines = if (numStackLinesIntended > 0) {
      numStackLinesIntended
    } else {
      0
    }
    // adds thread name for easy locatability
    val threadName = Thread.currentThread().getName
    val stackTrace = Thread.currentThread().getStackTrace 
    // format the trace like an exception so the IDE can link with the relevant lines in the source code
    var toPrint = "\"" + shows + "\"" + " in thread " + threadName + ":"
    for (row <- 0 to Math.min(numStackLines - 1, stackTrace.length - 1 - stackOffset)) {
      val lineNumber = stackOffset + row;
      val stackLine = stackTrace(lineNumber);
      toPrint += "\n" + "  at " + stackLine
    }
    toPrint += "\n"
    Console.println(toPrint)
    self
  }
}
```

^ This is a really useful feature because you can put it in places where you want to trace, and it will tell you not only the thing toString, but the thread and also will provide a stack trace formatted like an exception so the IDE can link with the relevant lines in the source code.

Sample usage:

if( reallyImportantThing.trace ) {...}

Output:

"true" in thread eventThread:
at path.to.file.MyClassName(MyClassName.scala:49)

**Comment by JohnReedLOL** [comment]
Additionally, if I want to remove all the traces, I just do replace ".trace", ""

**Comment by xuwei-k** [comment]
https://github.com/scalaz/scalaz/pull/1119#issuecomment-195611151

**Comment by JohnReedLOL** [comment]
scallaz already has "reallyImportantThing.print" and "reallyImportantThing.println", and these things have side effects of printing to the terminal. Not to mention that the [Debug.Trace](https://hackage.haskell.org/package/base-4.8.2.0/docs/Debug-Trace.html) feature is from Haskell and in Haskell it is useful for debugging and does not in any way reduce the correctness of the program or the ability of the user to reason about its correctness.

**Comment by JohnReedLOL** [comment]
If Haskell can have _Debug.Trace.trace_ function as well as _Debug.Trace.traceStack_ function , then Scala can have _Debug.Trace.trace_ functionality too.

**Comment by JohnReedLOL** [comment]
Not to mention that nothing is being modified. The original data it not modified. The name of the thread is same. The trace is getting a trace, but it is not changing.

Finally, trace is temporary use feature. It is inserted into code, used, and then removed. Output of function is not modified.

**Comment by shajra** [comment]
Hi John,

I think at this point, Scalaz's reason to exist is to really provide just pure functions, with extremely calculated side-effects along the lines of unsafePerformIO.  I know there's other side-effects and partial functions scattered around the project, but there's talk of actually talking about cleaning this up even more.

I don't think your points are without merit, and there's definitely times a debugging facility as you've proposed is useful.  I just think this should be in another library, and not Scalaz.

**Comment by JohnReedLOL** [comment]
Fine. I will put "trace" inside another library. It might make sense to put "print" and "println" inside of the same library as "trace" because all three can be used to print a debug message to the terminal.

**Comment by JohnReedLOL** [comment]
Also, if you run "trace" as an SBT task (Intellij > Run Configurations > SBT Task > run), it will print to the IntelliJ console and you can click on the stack trace or press the up and down arrows in the IntelliJ console to navigate through the stack trace and actually see the file and line where the stack trace is coming from. It's much better than looking around for where you put a print statement.

**Comment by shajra** [comment]
Sounds like all the more reason to get that library written! :smile:  I don't mean to be snarky, and I don't have the final vote or anything.  I just wanted to say more about why many of us agree with the closing of this ticket.

**Comment by JohnReedLOL** [comment]
I actually didn't expect it to get through, lol. I do have something similar.

Java style trace with no implicit conversions:

https://dl.dropboxusercontent.com/u/214507961/printdebug_2.11-1.0.jar

Work in progress implicit conversions version of trace library:

https://dl.dropboxusercontent.com/u/214507961/printdebug_2.11-1.4.jar

If you want to help, feel free.

**Comment by JohnReedLOL** [comment]
If you wanted to work on the trace library, it would also have a built in "assert" method. Like this:

```
val five = 5
five.println
five.trace
five.assert(_+2=7, "five plus two must equal seven")
five.assert(_+1=7, "five plus one must equal seven")
```
 Output:
```
5
"5" in thread main:
  at path.to.file.Main(Main.scala:49)

"five plus one must equal seven"  in thread main:
  at path.to.file.Main(Main.scala:51)
  ...
  Application terminated due to fatal assertion
```

**Comment by japgolly** [comment]
Contradiction:
https://github.com/scalaz/scalaz/blob/abbd0238972d71bd07724218d4f85341ab720389/core/src/main/scala/scalaz/syntax/IdOps.scala#L19-L35

To be consistent, I suggest either deprecate this ↑, or clarify the reasoning to allowing/denying side-effecting code outside of effectful types.

**Comment by puffnfresh** [comment]
@japgolly we should delete `unsafeTap`

**Comment by japgolly** [comment]
@puffnfresh Let it not be said that it isn't the case that I wouldn't deny that I don't disagree. :smile:

**Comment by JohnReedLOL** [comment]
Would you ever consider removing print and println from scalaz (not version 7, but maybe version 8) if I put print, println, printStdErr, printlnStdErr, trace, traceStdOut, and other related printing functions into a separate library?

**Comment by JohnReedLOL** [comment]
@shajra - Here is that library - 

https://github.com/JohnReedLOL/debugtrace

^ It's really nice for tracing things. My email is johnmichaelreedfas@gmail.com if you want to make any changes.
