### ISSUE TITLE
IdOps#unsafeTap requires removal

### ISSUE THREAD

**Issue by tonymorris** [scalaz/scalaz#1121]
This is not code.

**Comment by tpolecat** [comment]
Hey mate can we do PRs for this stuff? It would be nice to have a record of the discussion.

**Comment by tonymorris** [comment]
OK. But I am still unclear on what "this stuff" means. Since this is a most egregious and blatant software defect, that is unlikely to be surpassed (only equalled), I can assume it means that every possible code change requires a PR.

**Comment by nuttycom** [comment]
@tonymorris well, yeah, a PR for every code change is generally how open-source projects work. I entirely support this change, and I don't think it requires a deprecation cycle, and I'm fucking guilty of writing this crap, I added it (via a PR) back when I didn't know better, but I do think that the process of not pushing straight to master has value.
