### ISSUE TITLE
Remove or replace the TODO comment from EphemeralSream.weakMemo()

### ISSUE THREAD

**Issue by dmitryleskov** [scalaz/scalaz#1172]
There is a TODO comment in `EphemeralSream.weakMemo()` saying

``` scala
    // TODO I don't think this annotation does anything, as `v` isn't a class member.
    @volatile var v: Option[WeakReference[V]] = None
    () => {
    ...
```

My understanding is that returned from that method is a closure, of which `v` is a free variable, so under the hood `v` gets wrapped in a `scala.runtime.VolatileObjectRef` and passed to the constructor of a `scala.runtime.AbstractFunction0` _subclass_, an instance of which represents the given closure. Absent the annotation, it would be `ObjectRef` wrapping that variable, and the difference is indeed the `volatile` attribute on the respective field (`scala.runtime.*Ref` classes are written in Java).

A smaller example illustrating the difference:

``` scala
class Volatile {
  def f: () => String = {
    var nv: String = "Non-volatile"
    @volatile var v: String = "Volatile"
    () => {
      nv = "Foo"
      v = "Bar"
      v
    }
  }
}
```

complies and decompiles to:

``` java
import scala.*;
import scala.runtime.*;

public final class Volatile$$anonfun$f$1 extends AbstractFunction0 implements Serializable {
   public static final long serialVersionUID = 0L;
   private final ObjectRef nv$1;
   private final VolatileObjectRef v$1;

   public final String apply() {
      this.nv$1.elem = "Foo";
      this.v$1.elem = "Bar";
      return (String)this.v$1.elem;
   }

   public Volatile$$anonfun$f$1(Volatile $outer, ObjectRef nv$1, VolatileObjectRef v$1) {
      this.nv$1 = nv$1;
      this.v$1 = v$1;
   }
}
```

So I believe the comment can be removed (or perhaps replaced with one explaining the need for the `@volatile` annotation).

Fixing #1103 would probably invalidate this issue.

**Comment by S11001001** [comment]
Fixed by #1348.
