### ISSUE TITLE
rename "clazz" to "typeclass" for new users

### ISSUE THREAD

**Issue by shajra** [scalaz/scalaz#1178]
This is for the Scalaz 8 branch.  I don't think I have the ability to add a label.

I hate to debate names to death, but in some cases, I think it's worth some rework.  Here's my thoughts:

- "Clazz" a name often used by Java programmers for all their reflection insanity. 
- Even "class" is an unfortunate name because of what it means to Java programmers.
- "Typeclass" is at least a Google-able term that gets people closer to the truth.
- "Typeclass" is only four characters more -- not impossibly long, right?

The PR is easy enough to make, which I'll do shortly.  I don't know if writing up this issue was a needless step process-wise.

**Comment by tonymorris** [comment]
:+1:

**Comment by aloiscochard** [comment]
Fixed with 03f184efec4a62f40eb197121be315d8060a1cec
