### ISSUE TITLE
Upgrade ScalaCheck in scalaz-scalacheck-binding to 1.13.1

### ISSUE THREAD

**Issue by puffnfresh** [scalaz/scalaz#1197]
The current ScalaCheck version in the project is 1.12.5 - some teams at Atlassian are on 1.13.1 and have worked around the problem.

**Comment by puffnfresh** [comment]
specs2 3.8.3 brings in ScalaCheck 1.13.1

**Comment by xuwei-k** [comment]
- https://github.com/scalaz/scalaz/pull/1095
- https://github.com/rickynils/scalacheck/issues/218
- https://github.com/rickynils/scalacheck/issues/190
