### ISSUE TITLE
What are the std-lib types that shoud be supported?

### ISSUE THREAD

**Issue by aloiscochard** [scalaz/scalaz#1207]
- `List`
- `Option`
- `Either`

I would like to say we put `Future` aside until we sort out the RTS case, but it would be good to put at initial list in `CONTRIBUTING.md`.

/cc @vmarquez @shajra

**Comment by vmarquez** [comment]
I think having List/Option/Either is convenient, but there's an argument to be made that once we have optics for all three above, is it worth writing type class instances for them?  I suppose for List you take a more sever performance penalty so that's the only one I'd say might be worth it.

**Comment by puffnfresh** [comment]
@vmarquez I think we should do both: write the type-classes for them, and make it very convenient to not use them.

**Comment by tonymorris** [comment]
As previously discussed, I think module separation should be determined against, "extent of compromise to scala." For example, `scalaz-core` does not do all the usual things that we know are bad ideas.

Using the stdlib is also a bad idea, but of course, is required for legacy reasons. Therefore, "compromises against scala by using the stdlib", should be in its own module and by its absence, a user knows that no such compromise has been made.

**Comment by puffnfresh** [comment]
@tonymorris :+1:

**Comment by aloiscochard** [comment]
@tonymorris totally agree, I think though that instances for the type listed initially should be provided in `base`, nothing else.

Any other feature related to those type (syntax, specific function), should be provided separately.

I think we all agree on this, let me know if that's not the case.
