### ISSUE TITLE
Build failing on Travis (series/7.3.x)

### ISSUE THREAD

**Issue by aloiscochard** [scalaz/scalaz#1213]
Here is the error report:
https://travis-ci.org/scalaz/scalaz/jobs/139905231#L3627

But surprisingly, when running locally all tests pass, any idea?

A transient error from Travis?

**Comment by xuwei-k** [comment]
```
[info] ! scalaz.TreeLocTest.TreeLoc:order.equal.transitive: Gave up after only 0 passed tests. 11 tests were discarded.
```

I think this is a scalacheck issue.

**Comment by xuwei-k** [comment]
maybe https://github.com/rickynils/scalacheck/issues/172 ?
