### ISSUE TITLE
Publish Scalaz for Scala 2.12.0-M5

### ISSUE THREAD

**Issue by etorreborre** [scalaz/scalaz#1215]
@xuwei-k this necessary for me to be able to publish at least a minimal version of [specs2](https://github.com/etorreborre/specs2/issues/489).

**Comment by xuwei-k** [comment]
published scalaz v7.2.4 and v7.1.8 for Scala 2.12.0-M5 (without scalacheck-binding)

```
git clean -fdx
git checkout v7.2.4
sbt ";++ 2.12.0-M5;coreJVM/publishSigned;coreJS/publishSigned;concurrent/publishSigned;effectJVM/publishSigned;effectJS/publishSigned;iterateeJVM/publishSigned;iterateeJS/publishSigned"
```

```
git clean -fdx
git checkout v7.1.8
sbt ";++ 2.12.0-M5;core/publishSigned;concurrent/publishSigned;effect/publishSigned;iteratee/publishSigned;typelevel/publishSigned;xml/publishSigned"
```

**Comment by etorreborre** [comment]
Thanks a lot @xuwei-k for being so fast!

**Comment by xuwei-k** [comment]
released `"org.scalaz" % "scalaz-scalacheck-binding_2.12.0-M5" % "7.2.4"` and `"org.scalaz" % "scalaz-scalacheck-binding_2.12.0-M5" % "7.1.8"` as well
