### ISSUE TITLE
Missing type classes in Isomorphism

### ISSUE THREAD

**Issue by kcsongor** [scalaz/scalaz#1225]
I noticed that while the Isomorphism package provides a large set of derivable type classes through isomorphisms, some are missing.

Is there a particular reason why, for example, IsomorphismMonadReader isn't defined? I find that this can be fairly useful in practice.

I could make a PR to add these, and it would also be nice to have a list of the missing ones.

**Comment by kcsongor** [comment]
It's more of a question than a request: would it be accepted if I made a PR adding isomorphisms for type classes like MonadReader?

**Comment by jedws** [comment]
Csongor,

There isn't a rigorous approach to the inventory of instances. People
notice that useful ones are missing and then add them.

I'm pretty sure your PR would be welcome, as would any attempt at an
inventory of what is and isn't there.

cheers,
jed.

**Comment by kcsongor** [comment]
Using the information in the build script to determine the traits that correspond to type-classes, and diffing that with the existing Isomorphism instances, I think the following type-classes have no Isomorphism instance defined for them:

Align
Arrow
Associative
Catchable
Category
Choice
ComonadStore
Compose
Cozip
Divide
Divisible
Enum
InvariantFunctor
IsEmpty
LiftControlIO
LiftIO
MonadControlIO
MonadError
MonadIO
MonadReader
MonadState
MonadTell
Nondeterminism
PlusEmpty
ProChoice
Profunctor
Resource
Split
Strong
Unzip
Zip

I'm going to make a PR in the next couple of days, when I get around to adding these. Some of them might be tricky, but I will see.

**Comment by kcsongor** [comment]
Note: `PlusEmpty` does have an instance defined for it, but instead of using the `IsomorphismPlusEmpty` naming convention, it is (somewhat confusingly) called `IsomorphismEmpty`
