### ISSUE TITLE
Towards Scalaz 8

### ISSUE THREAD

**Issue by aloiscochard** [scalaz/scalaz#1231]
The intent of this issue is to give a summary of the active groundwork around `scalaz8` and collect the hanging fruits available for those interested to help.
## Research

There is a few topics which have to be researched before being able to move forward in the design of the library.
- Interpreters
  - A numerical representation for `Free`? (https://github.com/scalaz/scalaz/issues/1211)
  - Reflection without remorse data-structure? (i.e. [impl. by m50d](https://github.com/m50d/paperdoll/tree/master/core/src/main/scala/paperdoll/core/queue))
- Lenses (https://github.com/scalaz/scalaz/issues/1227)

The implementation of monad transformers and the RTS is on hold until this research work is done.
### Data

The code base contains currently only a few data structure, so there is room for contribution here, but we have to focus on structure that does not depend on `Free` for now.
- IList (https://github.com/scalaz/scalaz/issues/1228)
- OneAnd as a primitive? (https://groups.google.com/d/msg/scalaz/quM3LyklQBo/7IUTbeTCAgAJ)

There is surely a bunch of others which can be ported without requiring `Free` or transformers.
### Laws

We currently lack a property-based testing and law checking system (https://github.com/scalaz/scalaz/issues/1230).
## Consistency

During the initial design of the base library a few back and worth have been made, resulting in a few inconsistencies.
- Zero-cost all the syntax (https://github.com/scalaz/scalaz/issues/1229).
- Once the template system is finalized (https://github.com/scalaz/scalaz/pull/1226), we should ensure it is properly used among all instances definition of `base`.
## Documentation

The core design seems stabilize and it will be possible soon to document the typeclass encoding and write basic examples.

**Comment by fommil** [comment]
we currently have a Milestone and a label for scalaz8... should we scrap the label and just use the milestone?
