### ISSUE TITLE
Monad transformer map*T functions

### ISSUE THREAD

**Issue by kcsongor** [scalaz/scalaz#1244]
The major Haskell monad transformer libraries (mtl, transformers) define functions like `mapExceptT` and `mapStateT`, that map functions working on the underlying representations to functions acting on the transformers themselves.

For example: `mapExceptT :: (m (Either e a) -> n (Either e' b)) -> ExceptT e m a -> ExceptT e' n b` (from mtl).

The implementations of these functions are of course trivial, which makes me wonder - why are they not present in scalaz?
From a practical perspective, they can make writing certain type class instances much easier that are of the form `instance MonadTypeClass m => MonadTypeClass (ExceptT e m)`, where MonadTypeClass has some *tricky* functions, i.e. ones that aren't of the 'simply liftable' form.
(MonadCatchIO comes to mind)

(Excuse my use of Haskell syntax, it's too late to get the Scala one right).

**Comment by puffnfresh** [comment]
Yes, these are often lacking and it's very annoying :+1:

**Comment by kcsongor** [comment]
I'll make a PR then in the next few days

**Comment by kcsongor** [comment]
And while I'm at it, I'll try to find places where it could make existing code more concise (I already know of one example, which is an open PR)
