### ISSUE TITLE
should we use polymorphic lambdas syntax sugar?

### ISSUE THREAD

**Issue by xuwei-k** [scalaz/scalaz#1258]
Does anyone have an opinion?

- https://github.com/non/kind-projector/pull/33
- WIP https://github.com/xuwei-k/scalaz/commit/55645a10fb785f47c0259d86999ce7d2145449c8

**Comment by aloiscochard** [comment]
I'm all for it, especially as we are already using kind-projector for type lambda.

**Comment by S11001001** [comment]
We should absolutely use polymorphic lambdas, yes please. :+1:
