### ISSUE TITLE
Free.produce has non-unit discard

### ISSUE THREAD

**Issue by djspiewak** [scalaz/scalaz#1283]
``` scala
  def produce[A](a: A): Source[A, Unit] =
    liftF[(A, ?), Unit](a -> point[(A, ?), Unit](()))
```

Why is it `point`ing?  The following is the correct version:

``` scala
  def produce[A](a: A): Source[A, Unit] =
    liftF[(A, ?), Unit]((a, ()))
```

On a related note… `-Ywarn-on-value-discard`

**Comment by puffnfresh** [comment]
I'm not even sure how `point[(A, ?), Unit](())` compiles. Where does the A value come from?

**Comment by djspiewak** [comment]
`Return`. There is no `A`
