### ISSUE TITLE
fix scalaz.\/ scaladoc. scala.Either is now right-biased

### ISSUE THREAD

**Issue by xuwei-k** [scalaz/scalaz#1288]
https://github.com/scalaz/scalaz/blob/v7.3.0-M6/core/src/main/scala/scalaz/Either.scala#L17-L20

```
 * `A` [[\/]] `B` is isomorphic to `scala.Either[A, B]`, but [[\/]] is right-biased, so methods such as `map` and
 * `flatMap` apply only in the context of the "right" case. This right bias makes [[\/]] more convenient to use
 * than `scala.Either` in a monadic context. Methods such as `swap`, `swapped`, and `leftMap` provide functionality
 * that `scala.Either` exposes through left projections.
```

https://github.com/scala/scala/pull/5135

**Comment by kevinmeredith** [comment]
Since `Either` is right-biased in 2.12, what's the expectation of scalaz's `\/`, i.e. will it be replaced?

**Comment by S11001001** [comment]
@kevinmeredith Possibly, after a few preconditions are satisfied:

1. once Scalaz no longer supports any Scala <2.12 (so...that'll be a while),
2. provided that `scala.Either` hasn't added any methods that would replace any syntax extension we did with versions that are not as user-friendly (lest we forget the experience of `Option#fold`), and
3. after considering the implementations of those methods; @xuwei-k has done a lot of work making sure that `\/` methods minimally allocate, and it'd be a shame to lose that.
