### ISSUE TITLE
Library dependency in README.md doesn't appear to work

### ISSUE THREAD

**Issue by accesio** [scalaz/scalaz#1299]
You reference 

```
libraryDependencies += "org.scalaz" %% "scalaz-core" % "7.2.7"
```
Doesn't work for me, and I can't find anything on maven central under that link.

I went to Maven Central and see that they make a reference like
```
libraryDependencies += "org.scalaz" % "scalaz-core_2.11" % "7.2.7"
```

**Comment by xuwei-k** [comment]
This is not a bug. `%%` is standard way to cross building in sbt. please see sbt reference http://www.scala-sbt.org/0.13/docs/Library-Management.html#Dependencies
