### ISSUE TITLE
NoSuchMethodError while checking for Enum laws

### ISSUE THREAD

**Issue by Philippus** [scalaz/scalaz#1303]
I am running into the following error while playing around with Enum and checking if the laws hold:

`Exception: java.lang.NoSuchMethodError: org.scalacheck.Shrink$.shrinkInt()Lorg/scalacheck/Shrink;
scalaz.scalacheck.ScalazProperties$enum$$anonfun$succn$1.apply(ScalazProperties.scala:68)
scalaz.scalacheck.ScalazProperties$enum$$anonfun$succn$1.apply(ScalazProperties.scala:68)
scala.Function1$$anonfun$andThen$1.apply(Function1.scala:52)
org.scalacheck.Prop$$anonfun$forAllShrink$1$$anonfun$3.apply(Prop.scala:712)
org.scalacheck.Prop$$anonfun$forAllShrink$1$$anonfun$3.apply(Prop.scala:712)`

my testcase is as follows:

```scala
import org.scalacheck._
import scalaz._
import scalaz.scalacheck.ScalazProperties._

object IntEnum {
  implicit object intInstance extends Enum[Int] {
    def zero: Int = 0
    def order(x: Int, y: Int) = if (x < y) Ordering.LT else if (x == y) Ordering.EQ else Ordering.GT
    def succ(b: Int) = b + 1
    def pred(b: Int) = b - 1
    override def succn(a: Int, b: Int) = b + a
    override def predn(a: Int, b: Int) = b - a
    override def min = Some(Int.MinValue)
    override def max = Some(Int.MaxValue)
    override def equalIsNatural: Boolean = true
  }
}

object IntEnumSpec extends Properties("IntEnum") {
  import IntEnum._
  property("checksuccn") = enum.succn[Int]
  property("checkpredn") = enum.predn[Int]
}
```

If I take the enum.succn and enum.predn definitions and put them somewhere in my own project the tests pass.
I tried several versions, including scalaz version 7.2.8 combined with scalaCheck 1.13.4 on scala 2.12.1

**Comment by xuwei-k** [comment]
please use

```scala
libraryDependencies ++= Seq(
  "org.scalacheck" %% "scalacheck" % "1.13.4",
  "org.scalaz" %% "scalaz-scalacheck-binding" % "7.2.8-scalacheck-1.13"
)
```

or 

```scala
libraryDependencies ++= Seq(
  "org.scalacheck" %% "scalacheck" % "1.12.5",
  "org.scalaz" %% "scalaz-scalacheck-binding" % "7.2.8"
)
```

https://github.com/scalaz/scalaz/commit/189315efc8f048b4

**Comment by Philippus** [comment]
thank you Kenji. That works!

**Comment by S11001001** [comment]
Oh hey, I did not know about the `scalacheck-1.13` builds.  Neato.  Thanks @xuwei-k!
