### ISSUE TITLE
Change order of type parameters to monad transformers?

### ISSUE THREAD

**Issue by TomasMikula** [scalaz/scalaz#1305]
I suppose there was a reason why type parameters of some monad transformers in scalaz are in different order than in Haskell. For example

```scala
StateT[F[_], S, A]
```

instead of

```scala
StateT[S, F[_], A]
```

The latter seems to be a more common order of partial application.

Whatever the reason was, is it still valid?

Now that there's partial unification of type arguments, should we change the type parameter order to the one that's more common?

At least the following types could benefit from different parameter order:
 - [ ] `StateT`
 - [ ] `WriterT`
 - [ ] `ReaderT`
 - [ ] `ReaderWriterStateT`
 - [ ] `EitherT`
 - [ ] `ContT`

**Comment by xuwei-k** [comment]
@retronym wrote 5 years ago https://github.com/scalaz/scalaz/commit/4be176876edfde66b4018ed598c887eb1011f658#diff-f8a29528927f2b43e168ec1b8fede81fR239

> Declare type parameters requiring type constructors first in type parameter declarations. This is and arbitrary choice,
> but the consistency is worth it.
>
>     class Foo[F[_], A, B] // good
>     class Foo[A, F[_], B] // bad

https://github.com/scalaz/scalaz/blob/v7.3.0-M7/CONTRIBUTING.md#type-parameters

**Comment by TomasMikula** [comment]
I see.  Back then (before `-Ypartial-unification`), I guess optimizing for the most common use case would have made no difference. Might be time to reconsider?

**Comment by xuwei-k** [comment]
> Might be time to reconsider?

👍

**Comment by S11001001** [comment]
We can't really reconsider until we no longer support versions of Scala that *don't* have `-Ypartial-unification` or an equivalent substitute (like the plugin) available.  For the 7.3.x series, we still support Scala 2.10.

I've tagged this for 8 because there are good design cleanup reasons to require `-Ypartial-unification` be turned on for all users in that release.

**Comment by jbgi** [comment]
>  For the 7.3.x series, we still support Scala 2.10.

not anymore: https://github.com/scalaz/scalaz/pull/1367.

**Comment by TomasMikula** [comment]
See #1800 and #1838.

**Comment by jozi-k** [comment]
@TomasMikula I went through list of monad transformers and type parameters are now in correct order. I believe you can close this issue.

**Comment by TomasMikula** [comment]
Thanks for checking, @jozi-k! Closing.
