### ISSUE TITLE
support if in for-comprehensions with Scalaz State

### ISSUE THREAD

**Issue by maliqq** [scalaz/scalaz#1310]
```scala
def state1(value: Int) = State[Double, Unit] { x =>
  (value.toDouble - 10, ())
}

def state2(value: Int) = State[Double, Unit] { x =>
  (value.toDouble / x, ())
}

def process(x: Int) = for {
  a <- state1(x)
  value <- get
  a <- state2(x) if value != 0
} yield(a)

process(10)(0.0) // (0, ())
process(12)(0.0) // (6, ())
```

as seen here in example, state2 cannot be run with zero state value (state1 returns 0 for 10) to prevent division by zero.

**Comment by ritschwumm** [comment]
how would you implement withFilter for State?

**Comment by maliqq** [comment]
@ritschwumm probably just return unchanged state when filter fails

**Comment by xuwei-k** [comment]
>  just return unchanged state when filter fails

I think this is not a good idea. There is MonadPlus instance of StateT https://github.com/scalaz/scalaz/blob/v7.2.8/core/src/main/scala/scalaz/StateT.scala#L165

**Comment by vmarquez** [comment]
I agree with @xuwei-k

**Comment by maliqq** [comment]
@xuwei-k any examples of usage?

**Comment by ritschwumm** [comment]
so https://github.com/scalaz/scalaz/blob/bac0e06f399e57973ca22fddaa327d14443a11e7/core/src/main/scala/scalaz/syntax/MonadPlusSyntax.scala#L12 would give you if clauses in for-comprehensions?

**Comment by vmarquez** [comment]
yeah @ritschwumm so if you have a StateT[Option, A, B] this will work.  Here's some background on issues with withFilter:

https://github.com/scalaz/scalaz/issues/968
