### ISSUE TITLE
the series/8.0.x branch has no licensing information

### ISSUE THREAD

**Issue by stew** [scalaz/scalaz#1334]
We all assume that the intent is that you wish to allow others to redistribute this, can you please add a COPYING file or some such to make this explicit?

**Comment by S11001001** [comment]
As no license file existed at the time of commits, it's iffier to rely on ["inbound=outbound"](https://help.github.com/articles/github-terms-of-service/#6-contributions-under-repository-license), as 7.3.x series may; as such, would each of the following please attest to the below?

* [ ] @aloiscochard 
* [ ] @jbgi 
* [ ] @julien-truffaut 
* [ ] @vmarquez 
* [ ] @xuwei-k 

Please state your agreement with the following:

All of my commits are some combination of

1. original code, which I license to the Scalaz project under the same license as Scalaz 7.3.x; and/or
2. code copied from Scalaz 7.3.x or earlier.

**Comment by S11001001** [comment]
I apologize if I left you off the above list, but you feel that you should be on it; please also make the attestation in that case.  I have left a couple committers off because, while appreciating their commits, they don't seem to be copyrightable changes, even with a liberal interpretation of that, so there is no need to hassle the contributors of these about this issue.

**Comment by jbgi** [comment]
I attest that all of my contributions to the series/8.0.x are some combination of
 1.  original code, which I license to the Scalaz project under the same license as Scalaz 7.3.x; and/or
 2. code copied from Scalaz 7.3.x or earlier.

**Comment by S11001001** [comment]
Thanks @jbgi, also for noticing that "all of my commits" needs qualification 😕

**Comment by julien-truffaut** [comment]
I attest that all of my contributions to the series/8.0.x branch are some combination of

1. original code, which I license to the Scalaz project under the same license as Scalaz 7.3.x; and/or 
2. code copied from Scalaz 7.3.x or earlier.

**Comment by S11001001** [comment]
Thanks @julien-truffaut.

**Comment by aloiscochard** [comment]
I attest that all of my contributions to the series/8.0.x branch are some combination of

1. original code, which I license to the Scalaz project under the same license as Scalaz 7.3.x; and/or
2. code copied from Scalaz 7.3.x or earlier.

**Comment by S11001001** [comment]
Thanks @aloiscochard.

**Comment by S11001001** [comment]
Paging @xuwei-k @vmarquez

**Comment by xuwei-k** [comment]
I attest that all of my contributions to the series/8.0.x branch are some combination of

1. original code, which I license to the Scalaz project under the same license as Scalaz 7.3.x; and/or
2. code copied from Scalaz 7.3.x or earlier.

**Comment by vmarquez** [comment]
I attest that all of my contributions to the series/8.0.x branch are some combination of

1. original code, which I license to the Scalaz project under the same license as Scalaz 7.3.x; and/or
2. code copied from Scalaz 7.3.x or earlier.

**Comment by S11001001** [comment]
Thanks @xuwei-k , @vmarquez .

**Comment by S11001001** [comment]
@stew all's well, #1364

**Comment by S11001001** [comment]
Fixed by #1364.
