### ISSUE TITLE
Slow Scaladocs

### ISSUE THREAD

**Issue by fosskers** [scalaz/scalaz#1385]
Hi there. Every page load of the Scaladocs freshly downloads a ~9mb javascript file:
![slow](https://cloud.githubusercontent.com/assets/229679/25866376/270f4232-34ab-11e7-904d-2dcdde23e1d5.png)

which severely slows down interaction with the docs. I haven't noticed this issue with other scala projects that also produce 2.12-style docs.

Thoughts? Thanks.

**Comment by xuwei-k** [comment]
Thanks for the report. Are you using sonatyp? (e.g. https://oss.sonatype.org/service/local/repositories/releases/archive/org/scalaz/scalaz_2.12/7.2.12/scalaz_2.12-7.2.12-javadoc.jar/!/scalaz/index.html )

It's just as you say, sonatype is so slow.

Now, scalaz unidoc indexed on <http://javadoc.io> ( I just added `pom.xml` for unidoc )

Maybe <http://javadoc.io> has some nice features(Optimized HTTP caching, Accelerated with CDN, gzip support)

Could you try to following url?
https://static.javadoc.io/org.scalaz/scalaz_2.12/7.2.12/scalaz/index.html


![javadoc.io](https://cloud.githubusercontent.com/assets/389787/26062875/33f061d6-39c7-11e7-9240-8c956fc5ef70.png)

**Comment by fosskers** [comment]
Nice and fast! Thanks for the fix.
