### ISSUE TITLE
No `MonadError` instance for `StateT`?

### ISSUE THREAD

**Issue by fosskers** [scalaz/scalaz#1396]
I'm trying to raise an error in some code that is running in `StateT[EitherT]`. I have:

```scala
type EitherStr2[T] = scalaz.EitherT[scalaz.Id.Id, String, T]
type Statey2[T] = scalaz.StateT[({ type λ[α] = scalaz.EitherT[scalaz.Id.Id, String, α] })#λ, Int, T]
```
and I can manage
```scala
val foo: EitherStr2[Int] = scalaz.MonadError[EitherStr2, String].raiseError("crap")
```
but not
```scala
val bar: Statey2[Int] = scalaz.MonadError[Statey2, String].raiseError("noo")
```

I'm not sure what I'm missing. Should I take `foo` and try and lift it into `StateT`? I couldn't find examples of doing something like that, so I'm not sure what to do.

Thanks.

**Comment by TomasMikula** [comment]
Seems like such instance is indeed missing. Something similar to [what we have for `MonadState`](https://github.com/scalaz/scalaz/blob/6da7c79ce821f7002cc414dc6e7bb5d0c75fe96b/core/src/main/scala/scalaz/MonadState.scala#L30-L42) could be added for `MonadError`, i.e. if there is `MonadError` for `F`, then provide `MonadError` for any "bigger" monad `G`. Do you want to give it a try and open a pull request?

**Comment by jvz** [comment]
I actually wrote some glue code for this, but I wasn't sure if it wasn't included in scalaz because it violated some monad laws.

```scala
  implicit def stateTMonadError[F[_], S, E](implicit F: MonadError[F, E])
  : MonadError[StateT[F, S, ?], E] = new MonadError[StateT[F, S, ?], E] {
    override def raiseError[A](e: E): StateT[F, S, A] =
      StateT(_ => F.raiseError(e))

    override def handleError[A](fa: StateT[F, S, A])(f: (E) => StateT[F, S, A]): StateT[F, S, A] =
      StateT(s => F.handleError(fa(s))(f(_)(s)))

    override def bind[A, B](fa: StateT[F, S, A])(f: (A) => StateT[F, S, B]): StateT[F, S, B] =
      fa flatMap f

    override def point[A](a: => A): StateT[F, S, A] =
      StateT(s => (s, a).point[F])
  }

  implicit def rwstMonadError[F[_], R, W, S, E](implicit F: MonadError[F, E], W: Monoid[W])
  : MonadError[RWST[F, R, W, S, ?], E] = new MonadError[RWST[F, R, W, S, ?], E] {
    override def raiseError[A](e: E): RWST[F, R, W, S, A] =
      RWST((_, _) => F.raiseError(e))

    override def handleError[A](fa: RWST[F, R, W, S, A])(f: (E) => RWST[F, R, W, S, A]): RWST[F, R, W, S, A] =
      RWST((r, s) => F.handleError(fa.run(r, s))(f(_).run(r, s)))

    override def bind[A, B](fa: RWST[F, R, W, S, A])(f: (A) => RWST[F, R, W, S, B]): RWST[F, R, W, S, B] =
      fa flatMap f

    override def point[A](a: => A): RWST[F, R, W, S, A] =
      RWST((_, s) => (W.zero, a, s).point[F])
  }
```

I also attempted to expand these to the Indexed variants, but types don't align properly that way.

**Comment by puffnfresh** [comment]
Looks good to me @jvz. PR would be useful :heart:

**Comment by jvz** [comment]
Where could I put the instances? There'd be a conflict between MonadState and MonadError since they both extend Monad. Unless that's not an issue.

**Comment by puffnfresh** [comment]
@jvz that's an issue. The solution is the hierarchy of instance scopes. Scala's implicit resolution goes through an inheritance chain and stops when it finds a matching implicit. You can avoid ambiguities by using this mechanism.

Specifically StateT has:

https://github.com/scalaz/scalaz/blob/a53d51f0f1ef7af939d6ae4b2aba220446520340/core/src/main/scala/scalaz/StateT.scala#L158-L188

Notice `MonadPlus[StateT[F, S, ?]]` requires `MonadPlus[F]`. This is similar to your case, except Error instead of Plus.

**Comment by jvz** [comment]
I noticed that after I asked. I think I got it right (didn't cause any compiler errors, so that's a good sign). Incoming PR.
