### ISSUE TITLE
consistency minBy/minimumBy/extremaBy

### ISSUE THREAD

**Issue by xuwei-k** [scalaz/scalaz#1398]
in bfd934279cf4dc64cc62be2237ad9387a0b4dd9b (latest `series/7.3.x` 2017-06-03 )

```
scala> val xs = (1 to 6).toList
xs: List[Int] = List(1, 2, 3, 4, 5, 6)

scala> xs.minBy(_ % 3) // scala std
res0: Int = 3

scala> xs.minimumBy(_ % 3)
res1: Option[Int] = Some(6)

scala> xs.maxBy(_ % 3) 
res2: Int = 2

scala> xs.maximumBy(_ % 3)
res3: Option[Int] = Some(5)

scala> xs.extremaBy(_ % 3)
res4: Option[(Int, Int)] = Some((3,2))
```

- change `minimumBy` and `maximumBy`? i.e. `(1 to 6).toList.minimumBy(_ % 3)` should be return `Some(3)` ?
- change `extremaBy`? i.e. `(1 to 6).toList.extremaBy(_ % 3)` should be return `Some((6, 5))` ?
- keep current behaviors?

/cc @nuttycom

**Comment by puffnfresh** [comment]
Change `extremaBy`, just because minimum/maximum have been around longer :+1:

**Comment by ritschwumm** [comment]
apart from that the behaviour of minimumBy and maximumBy look much more useful to me -
the existing behaviour of extremaBy can easily be recovered as `xs.map(_%3).extramaBy(identity)` (or `xs.map(_%3).extrama` if that exists), but not the other way round
