### ISSUE TITLE
Delete the ever living shit out of Task

### ISSUE THREAD

**Issue by tonymorris** [scalaz/scalaz#1401]
It's 2017. `Task` still exists.

![It's 2017](http://i.imgur.com/MCKMVRJ.jpg)

**Comment by kevinmeredith** [comment]
Could you please explain the problem with `Task`?

Would something else replace it?

Thanks!

**Comment by jdegoes** [comment]
`Task` has numerous unsafe functions, tries to be an `IO` monad but without providing all the time-tested functionality of such a monad (which it then tries to provide in more ad hoc ways), uses exceptions to communicate internally, uses implicits as global effectful values, and so forth.

That said, Scalaz 7 `IO` does not (by itself) subsume the functionality of `Task`, so `Task` in 7 cannot easily be deleted without causing user's pain. Scalaz 8's `IO`, however, will be a much richer version of `IO` that supports asynchronous effects, without any of the drawbacks of `Task`.

**Comment by fommil** [comment]
This is hopefully coming in 7.3. I created a dupe at #1874

**Comment by ktonga** [comment]
@fommil I think you meant #1796

**Comment by tonymorris** [comment]
Fixed in #2037
