### ISSUE TITLE
boilerplate helpers for creating typeclasses

### ISSUE THREAD

**Issue by fommil** [scalaz/scalaz#1420]
basically using https://github.com/mpilquist/simulacrum or offering an alternative (lifting as is or forking if special requirements are needed is the obvious choice).

I can't think of any performance optimisations that could be done here across-the-board, but there might be some that pop up later. There is https://github.com/typelevel/machinist which is a pretty simple, but effective, idea, and could be extended to include common patterns in scalaz.

**Comment by aloiscochard** [comment]
I label this as 8, as I believe it would makes there, the encoding is dramatically different from simulacrum we should provide our own solution.

Also having such facilities will help newcomers a lot, as they won't have to grasp the complete encoding but just the necessary syntax.

More generally, this might also help with https://github.com/scalaz/scalaz/issues/1328

:+1:
