### ISSUE TITLE
consider using no-imports in the build

### ISSUE THREAD

**Issue by fommil** [scalaz/scalaz#1436]
I've been using these `scalacOptions` on a personal project and it's been fantastic.

```
scalacOptions ++= Seq(
  "-Yno-imports",
  "-Yno-predef"
)
```

It can be a bit irritating in the REPL, but that's easily fixed with

```
initialCommands in (Compile, console) := Seq(
  "java.lang.String",
  "scala.{Any,AnyRef,AnyVal,Boolean,Byte,Double,Float,Short,Int,Long,Char,Symbol,Unit,Null,Nothing,Option,Some,None,Either,Left,Right,StringContext}",
  "scala.annotation.tailrec",
  "scala.collection.immutable.{Map,Seq,List,::,Nil,Set,Vector}",
  "scala.util.{Try,Success,Failure}",
  "scala.Predef.{???,ArrowAssoc,identity,implicitly,<:<,=:=}",
  "scalaz._",
  "Scalaz._"
).mkString("import ", ",", "")
```

(trim as desired...)

**Comment by aloiscochard** [comment]
I'm totally for it in 8, not sure about current, would that imply massive change in the imports of the current code base?

**Comment by fommil** [comment]
it's probably an evening. You'd need to make sure you have something like MIMA or there could be binary changes. e.g. you might be accidentally using `scala.collection.Seq` somewhere instead of `scala.collection.immutable.Seq` is the classic.

I've got an eye on https://github.com/scala/scala/pull/5350 for custom predef, which sounds awesome, but it's not ready for prime time.

**Comment by soc** [comment]
Please note that replacing star imports with named imports is generally not backward-compatible due to different "strengths" those reports have. This doesn't seem to be addressed in scala/scala#5350.

**Comment by fommil** [comment]
@soc your thoughts on that PR would be fantastic.

**Comment by soc** [comment]
Maybe it would make sense to cut down on those ~ 500 types and terms that are imported into the global namespace of every program by default, instead of adding more configurable workarounds.

But as long as one can't even properly alias terms coming from Java, I welcome any effort that goes into these workarounds.

¯\_(ツ)_/¯

**Comment by fommil** [comment]
maybe a scalaz8 thing
