### ISSUE TITLE
EphemeralStream.foldRight (indeed all foldRight impls) should be stack safe

### ISSUE THREAD

**Issue by fommil** [scalaz/scalaz#1447]
I was surprised to discover that this is not stack safe

```
EphemeralStream.range(1, 10000).foldr(0L)(a => b => a + b)
```

and looking at the implementation we can see its using non-tail recursion rather than a trampoline.

I expected this to be stack safe.

**Comment by fommil** [comment]
note that reversing a finite `EphemeralStream` seems to be stack safe

```
EphemeralStream.range(1, 1000000).reverse.foldLeft(0L)(a => b => a + b)
```

**Comment by S11001001** [comment]
We can't do this; see #1143 and links from there.

**Comment by fommil** [comment]
Ok thanks. I had a read. It seems to boil down to the fact that `foldRight` could cause OOM (or be less efficient) for infinite streams. So we prefer to blow the stack. If we're going to allow blowing the stack for streams, why not just implement `foldRight` as a `???`

Perhaps we need a version of `Foldable` that doesn't require `foldRight`? Or is that just special casing for streams?

**Comment by S11001001** [comment]
This area is more complex, and doesn't deserve more half-measures.

My [comment on #615](https://github.com/scalaz/scalaz/issues/615#issuecomment-31290260) talks about some of the dimensions of the problem. My [comment on purescript/purescript-foldable-traversable#54](https://github.com/purescript/purescript-foldable-traversable/pull/54#issuecomment-270269031) lists some complex cases with frequently forgotten issues (e.g. *invoking* the resulting `Reader`).

And we didn't even try to address the nonstrict cases there. Not all folds are strict, and we want to support those too. Not all data structures are strict, and we want to support those too. So, yes, blowing the stack for strict folds is better than a right-fold that is veritably non-total for `EphemeralStream`s themselves.

**Comment by fommil** [comment]
then why not take that logic to the extreme and fail fast with `???`

**Comment by S11001001** [comment]
`???` won't work for the nonstrict folds, the current operation will.
