### ISSUE TITLE
I heard you like Enum, so I made an Enum for your Enum

### ISSUE THREAD

**Issue by fommil** [scalaz/scalaz#1449]
it would be pretty nice to have a `scalaz.Enum` for https://docs.oracle.com/javase/8/docs/api/java/lang/Enum.html

It would allow things like

```
java.time.DayOfWeek.MONDAY |-> 2
```

look like there is only an `Equal` instance.

**Comment by jdegoes** [comment]
What do you think of [the PureScript version](https://github.com/purescript/purescript-enums) as inspiration? Java 8 enums would have an efficient implementation and could also provide automatic Show.

**Comment by fommil** [comment]
Nice! I guess I'm even thinking ahead to the possibility of having `sealed trait` of `object`s converted into `enum`s at the bytecode level.
