### ISSUE TITLE
Foldable.{toMap, groupBy}

### ISSUE THREAD

**Issue by fommil** [scalaz/scalaz#1452]
It would be useful to have something equivalent to stdlib `groupBy` on `Foldable`

Maybe a bit hacky, but we can do this from `splitBy` and `fromFoldableWithKey`, example

```scala
scala> ==>>.fromFoldableWithKey(IList("foo", "bar", "bar", "faz", "gaz", "baz").splitBy(_.charAt(0)))((a, b1, b2) => b1 |+| b2)
res: Char ==>> scalaz.NonEmptyList[String] = Bin(f,NonEmpty[faz,foo],Bin(b,NonEmpty[baz,bar,bar],Tip,Tip),Bin(g,NonEmpty[gaz],Tip,Tip))
```

perhaps with an intermediate `Foldable.toMap` taking the `Semigroup[B]`

**Comment by vmarquez** [comment]
I have been thinking about this for ages. I originally thought we could solve this with a 'Buildable' type class, but @tonymorris and Ed thought that wasn't a real TypeClass.  They suggested we try something like Cons (in combination with Foldable). https://github.com/julien-truffaut/Monocle/blob/c0540739c6a71c834ca13b889a18e18f5eb6618e/core/shared/src/main/scala/monocle/function/Cons.scala

Unfortunately, I don't think that will let us use Set/Map.  I have to believe there are other optics or type classes that can abstract away the idea of "putting an A into an M" lawfully.  

@edmundnoble Thought that a Free Monoid structure might help here too, but I'm not sure I understand enough.

**Comment by jdegoes** [comment]
See [purescript-unfoldable](https://github.com/purescript/purescript-unfoldable/blob/master/src/Data/Unfoldable.purs).

This is, perhaps, not exactly the right abstraction, but the idea would be to define a suitable catamorphism (`Foldable`) and anamorphism (`Unfoldable`), and combine them to form a `Collection` type class that allows you to implement all the methods that require the ability to tear down and rebuild a linear structure.

Then instances could specialize functions like `groupBy`, etc., in order to improve performance over the default implementations.

**Comment by julien-truffaut** [comment]
A while ago I tried to experiment with `Foldable` / `Unfoldable` relationship in cats. Here is the thread for reference: https://github.com/typelevel/cats/pull/1132

**Comment by Jacoby6000** [comment]
While working on #1462 I noticed a lot of places where scalaz is using `Seq` (Mostly with `Nondeterminism`.  A `Collection` typeclass would eliminate the need for using `Seq` in there altogether.

**Comment by jdegoes** [comment]
Also relevant: Gabriel's excellent `Foldl` [package](https://hackage.haskell.org/package/foldl-1.3.2/docs/Control-Foldl.html). It's possible many one-pass folds are best expressed as `Foldl` structures, which can be materialized into different data structures.

Eagerly producing data structures introduces lots of overhead in Scala applications. You can see [@paulp's work on laziness](https://github.com/paulp/psp-std/blob/master/doc/views.md) can produce quite dramatic speedups.

**Comment by fommil** [comment]
maybe this is just all part of some kind of Unfoldable epic.
