### ISSUE TITLE
Traverse.tproduct and >>! equivalent

### ISSUE THREAD

**Issue by fommil** [scalaz/scalaz#1459]
Like `Functor.product` and `Bind.mproduct` I often find it useful to be able to `traverse` over a bunch of effects and return their inputs, not their outputs. 

As a hack, I've taken to defining the algebra to return the input rather than `Unit`

```scala
trait Machines[F[_]] {
  def start(node: MachineNode): F[MachineNode]
  def stop(node: MachineNode): F[MachineNode]
}
```

which allows me to `nodes.traverse(m.start)` (where `nodes` is a `NonEmptyList`) instead of what I'd really like to do is define

```scala
trait Machines[F[_]] {
  def start(node: MachineNode): F[Unit]
  def stop(node: MachineNode): F[Unit]
}
```

then write `nodes.<some new syntax>(m.start)` or `m.stop` which can be achieved with the (ugly)

```scala
nodes.traverse(_.pure[F] >>! m.stop)
```

Crazy? Useful? Bad name? (I'm suggesting what looks consistent with `product` and `mproduct`)

**Comment by TomasMikula** [comment]
Seems useful, but also seems that it has nothing to do with `Traverse`.

Could perhaps go to `Functor` syntax, specifically to [`FunctorIdV`](https://github.com/scalaz/scalaz/blob/fdbf1e3696b03929c39f3cf688460d2169116999/core/src/main/scala/scalaz/syntax/FunctorSyntax.scala#L48).

(PS: I believe you mean `fproduct`.)

**Comment by fommil** [comment]
You're right, I was even thinking that a syntax on Id world be better here... so something like what I wrote but without the .pure? And you're right, it wouldn't complicate matters with traverse.

**Comment by puffnfresh** [comment]
```scala
nodes.traverse(a => m.stop(a) as a)
```

Is this the same?

**Comment by fommil** [comment]
I suppose it is. Ok closing for simplicity.
