### ISSUE TITLE
introduce forever in BindRec?

### ISSUE THREAD

**Issue by fommil** [scalaz/scalaz#1460]
It seems ... dangerous... to me that `forever` is introduced by `Apply` and refined in `Bind` but it is only safe to use when it exists on a `BindRec`.

I think I'd personally prefer it to only be introduced when it is safe to use. The current situation feels a bit like the Java Collections API where implementations are free to throw an exception if they don't feel like implementing a method.

Or is stack safety treated as a kind of tangential concern?

**Comment by fommil** [comment]
@LeifW looks like you generalised `forever`... although it is technically possible to implement it at the type level in `Apply` are you sure it's wise to introduce it here before the typeclass hierarchy defines stack safety?

**Comment by fommil** [comment]
I'm closing this, since changing it would potentially break too much code without a way out. I still don't think `forever` should have been introduced at this point in the hierarchy.

**Comment by LeifW** [comment]
Sorry, I didn't really put more into it than, "It typechecks, and runs with IO" - i.e. just thought about the data dependencies. My commit just moved it from being implemented in terms of Bind.bind to Apply.apply2; wasn't familiar with where exactly the TCO is introduced.

I think forever only makes sense for side-effecting operations. The `B` in the return type doesn't exist. Also, the `A` in the `F[A]` input is inaccessible. In normal usage I can only think of those things as being `Unit` (as is usually the case for side-effecting operations that return no output).

**Comment by LeifW** [comment]
The current impl matches the type sig in Haskell: `forever :: Applicative f => f a -> f b`. I'm unfamiliar with Scala mechanisms for tracking stack safety, though I agree `forever` only makes sense for operations that can run in constant space.

**Comment by LeifW** [comment]
Moving it to something like BindRec or MonadIO or whatever I think makes sense.

**Comment by jdegoes** [comment]
In Scalaz 8, I want to kill all non-stack safe monads. In which case `Applicative` is the right place for this.

**Comment by fommil** [comment]
thanks all! Glad we got clarity on this.
