### ISSUE TITLE
replace all inconsistent fold methods with switch

### ISSUE THREAD

**Issue by fommil** [scalaz/scalaz#1466]
e.g. Validated.fold

another one for #1463

Obvs for scalaz8... but what do people think about doing this in the next 7 series?

**Comment by TomasMikula** [comment]
What do you mean by inconsistent?

**Comment by fommil** [comment]
i.e. not matching the signature of `Foldable.fold`

**Comment by TomasMikula** [comment]
I'm not sure that `cata` is a great name for [`Validation#fold`](https://github.com/scalaz/scalaz/blob/c0e4b531847348e1fd533c7d3605fe69320dde91/core/src/main/scala/scalaz/Validation.scala#L68-L71):

```scala
def fold[X](fail: E => X, succ: A => X): X
```

Doesn't literally follow the pattern

```scala
class DataStructure[F[_]] {
  def cata[X](f: F[X] => X)(implicit F: Functor[F]): X
}
```

(If you squint enough, it somewhat does: if you take `type F[X] = E \/ A` and instead of `F[X] => X` handle the cases `E` and `A` separately; but that's quite a stretch IMO.)

I think it's much more intuitively just case analysis, so what do people think about calling it `switch`?

**Comment by TomasMikula** [comment]
In other words, even if catamorphism does generalize case analysis, we would be appealing to a much more general concept than is necessary, to no benefit.

**Comment by jdegoes** [comment]
I talk about making generic deconstructors and deconstructors in [this post](http://degoes.net/articles/kill-data), where I also adopt the (somewhat familiar) name `switch` for deconstruction.

I'm not too picky on the precise names, but I do think we need pervasive consistency across each version of Scalaz to make learning the library easier and more predictable.

Btw if you want to see the catamorphism, just take `F[X] = E \/ A`. Now the function `f` that performs the "fold" must handle `E` if it's a failure, and `A` if it's a success. 

Things get more interesting with a list, in which case you take `F[X] = () \/ (A, X)`, i.e. the function `f` that performs the "fold" must handle `()` if it's an empty list, and `(A, X)` if it's a cons cell (so the implementation of `cata` must obtain the initial `X` from the terminal `Nil`, and then work backwards over each element of the list to produce the final `X`.

**Comment by TomasMikula** [comment]
👍  for consistency. Also, I think it's fine to have both `cata` and `switch` and have them do the same thing. I just think `switch` (or `caseAnalysis` or `handleCases` or `cases`) is more accurate in this case.

**Comment by NeQuissimus** [comment]
@fommil I was about to open this for Scalaz 8. Are you looking to provide a solution that would be transferable? A "Switchable" type class or whatever you come up with :) `\/.fold` and `Maybe.fold` are my primary use cases here...

**Comment by TomasMikula** [comment]
What would the `Switchable` type class  look like? The pattern is not limited to binary sums.

**Comment by NeQuissimus** [comment]
I did not exactly think this through :D. But `Maybe.fold` and `Disjunction.fold` have been used quite frequently in our code bases and I was simply wondering if that could be properly formalized.

**Comment by TomasMikula** [comment]
These two folds can have a common interface because `Maybe[A]` is isomorphic to `Unit \/ A`. But how about sums of other arities?
