### ISSUE TITLE
add lift13 to lift22 and consider beyond this

### ISSUE THREAD

**Issue by fommil** [scalaz/scalaz#1467]
Would it be ok to add lift13 through lift22 to the current stable release or would that break binary compatibility?

The availability of lift22 and divide22 (which does exist) is going to be critical for automated (and very fast) `scalaz-derived` derivation of product types that I'm currently working on. Thoughts in WIP repo called `stalactite` https://gitlab.com/fommil/stalactite/issues/39

Does anybody have any thoughts what to do beyond 22?

I will most likely need a variant of `liftX` and `divideX` that takes `String` labels with each parameter. Thoughts on clean ways to do that (that aren't just a copy/paste of the current), or appropriate names for it, would be appreciated.

Ed Kmett said I'll need Alternative (`ApplicativePlus` in scalaz) and Decideable for coproducts derivation, and I heard Profunctor about combinations of covariant and contravariant. I've not got that far, but I expect it'll be the same deal as lift22 and divide22.

BTW, it would be good to have an equivalent of `deriving` on `Apply` to complement the `lift` methods. Any suggestions for a good name? e.g. with signature (and made up name `applying`)

```
def applying2[A: F, B: F, C](f: (A, B) => C): F[C] = ...
```

**Comment by TomasMikula** [comment]
I believe it is binary compatible to add new methods.

**Comment by jdegoes** [comment]
The way it's done in Scalaz right now is not performant (through delegation), though it reduces boilerplate. I think an Emacs macro is probably the best and most performant way to implement this. 😆 

We have `ap2` / `apply2`, etc., on `Apply`, but not up to arity 22.

How would you implement your `applyingN`?

**Comment by fommil** [comment]
it would have to be something like hlists beyond 22... and that's likely going to be super inefficient. I'll call that phase 2 :smile: 

the current delegation approach is not too bad because it means a few key methods are called very regularly, irrespective of arity, which means that people implementing their own typeclass derivation this way might get a huge perf boost just from lift2, lift3 and lift4.
