### ISSUE TITLE
does Catchable.fail have a use case?

### ISSUE THREAD

**Issue by fommil** [scalaz/scalaz#1470]
I am pretty sure we shouldn't be using or encouraging the using of `Catchable.fail`.

Sure enough, `Catchable.attempt` is a horrible workaround to the fact that we're on the JVM and dealing with legacy systems, but I do not understand how `Catchable.fail` can ever be a good idea.

**Comment by puffnfresh** [comment]
Catchable should be deleted.

**Comment by fommil** [comment]
Yeah, it does seem redundant in light of MonadError.

**Comment by jdegoes** [comment]
Well, it's really a specialization of `MonadError` where the error type is `Throwable`. Also, it's not a monad, which is a superior choice to `MonadError`. 

Probably the correct thing to do is to refactor `MonadError` into a better version of `Catchable`, i.e. lawful, generic error, but not a monad (`Applicative` should be sufficient to state the laws).

**Comment by puffnfresh** [comment]
Applicatives, Apply, Bind, etc. compose so I think MonadError and \/ is enough.

**Comment by fommil** [comment]
seems like a job for scalaz8.
