### ISSUE TITLE
Tag some issues with the Hacktoberfest label to pull in new contributors

### ISSUE THREAD

**Issue by Jacoby6000** [scalaz/scalaz#1475]
Any interest in tagging some issues with the [Hacktoberfest](https://hacktoberfest.digitalocean.com/) tag to encourage some contributions from new faces?  Not sure what y'alls opinions are on that.

**Comment by fommil** [comment]
personally I don't think it will gain any new contributors BUT it means we could all get a free T-Shirt, and that is good.

**Comment by fommil** [comment]
@Jacoby6000 I can create labels ... let me know what you want tagged.
