### ISSUE TITLE
usecase for ComonadStore ?

### ISSUE THREAD

**Issue by fommil** [scalaz/scalaz#1478]
Could somebody please explain what `ComonadStore` can be used for? It used to be called `ComonadCostate` when @tonymorris added it back in 2012. It seems to only be used in `StateT` and I see `lens` mentioned around there.

I originally thought it might be related to the `Comonad[Store]` as written up by Ed Kmett https://www.schoolofhaskell.com/school/to-infinity-and-beyond/pick-of-the-week/cellular-automata but after trying to understand it for some time now I'm almost convinced it is a different thing (although the `experiment` method does seem to be the same thing). It seems more like the `experiment` should be an of a `Store` data type.

**Comment by jdegoes** [comment]
It's the type class for a comonad that supports `Store`-like functionality, in the same way that, e.g. `MonadError` can be a type class for `Either`. The advantage of the type class is that it frees your code from having to know about the concrete type used for providing `Store`-like functionality.

**Comment by fommil** [comment]
hmm, I'm not so convinced that it's that useful as a typeclass... both `pos` and `peek` are left abstract and don't help to implement anything that comes from `Comonad`. Where can I look to get a better understanding of `pos`, `peek` and `seek`?

**Comment by jdegoes** [comment]
@fommil I would Google "store comonad", which brings up [this](https://bartoszmilewski.com/2013/10/08/lenses-stores-and-yoneda/) and [this](https://bartoszmilewski.com/2017/01/02/comonads/).

The type class would be useful if you want to abstract over comonads that can implement `Store`-like functionality (e.g. a `Store` transformer with another base comonad). Arguably, however, that's only useful if `Store` functionality is useful.

I don't know of any code "in the wild" that uses the `Store` comonad. Maybe you could implement Store-like functionality for some type of `Cofree` which might make it more usable than `Store`.

**Comment by fommil** [comment]
cool thanks. I had a read at those. I think I need to introduce `Store` before I can talk about this, so I'll call it an "Advanced Monad" and kick it into the long grass.
