### ISSUE TITLE
7.3.0 timescale

### ISSUE THREAD

**Issue by fommil** [scalaz/scalaz#1480]
@xuwei-k do you have any ideas when you'd like to release 7.3.0?

I have created a bunch of tickets (as a result of studying scalaz-core for my book) that I'd like to work on when the book is finished. It's mostly easy consistency cleanups (but breaking changes). It'll be early 2018 before I have time to look at it.

I created a github milestone so we can attach tickets to it https://github.com/scalaz/scalaz/milestone/15

Presumably anything that goes into 7.3 should also be considered in scalaz 8

**Comment by xuwei-k** [comment]
I have no detailed plan yet. But I think it’s about time to release if there is no objections from other committers.
I wonder when we release 7.3.0 final
- we should continue development 7.4.x branch?
- which version of scala-js support? only 0.6 or 1.0? both?

**Comment by jdegoes** [comment]
I think we should continue 7.3.x and then focus on 8.0. No opinions on anything else.

**Comment by fommil** [comment]
I created a bunch of tickets against the 7.3 milestone for bugs / inconsistencies that I've discovered as a result of reviewing the entire codebase for my book. Realistically I do not have time to complete them so if you wish to release 7.3 I will just close them and we can all focus on 8.0.

How can we be sure that bugfixes in 7.2 have been forward ported?

I don't use scalajs or scala-native, so my vote is for whatever impacts the build time the least. I'd very much like to use plugins in scalaz8 that don't get in the way of jvm development.

**Comment by fommil** [comment]
Oh, and I want to contribute https://gitlab.com/fommil/scalaz-deriving/tree/master/scalaz-deriving-base to scalaz7.3, is pretty much ready it just needs me remove the shapeless bits and add some laws/more tests. I'll try to raise a PR this weekend to get to ball rolling.

**Comment by TomasMikula** [comment]
👍 for releasing soon.

If a worthwhile breaking change comes up before 8 is ready, I'm not against starting 7.4.x.
