### ISSUE TITLE
Add fixed-point version of AList?

### ISSUE THREAD

**Issue by jdegoes** [scalaz/scalaz#1484]
See [here](https://github.com/TomasMikula/scalaz/blob/AList-via-AFix/base/shared/src/main/scala/scalaz/data/AList.scala) for prototype implementation.

**Comment by alexknvl** [comment]
:tada: https://github.com/scalaz/scalaz/blob/series/8.0.x/base/shared/src/main/scala/scalaz/data/AList.scala#L180
