### ISSUE TITLE
Use Liskov in all places instead of subtyping

### ISSUE THREAD

**Issue by fommil** [scalaz/scalaz#1487]
`Bifunctor` (syntax) widen looks like

```
final def widen[C >: A, D >: B]: F[C, D] = F.bimap(self)(identity[C], identity[D])
```

vs `Functor`

```
final def widen[B](implicit ev: A <~< B): F[B] = F.widen(self)
```

seems inconsistent... and more generally should `<:` and `>:` be replaced with Liskov everywhere?

**Comment by puffnfresh** [comment]
Yes, pretty sure. @S11001001 would definitely know.

**Comment by jdegoes** [comment]
I think it makes sense in any case which is not capturing `Liskov` from a subtyping relationship. So that'd include things like `Bifunctor`. We await @S11001001 for the official verdict. 😄

**Comment by TomasMikula** [comment]
I would say yes, as a matter of having the least requirements necessary to do the job. Compiler's knowledge of `A <: B` can easily be turned into `A <~< B`. The reverse is not possible. So `A <: B` is a stronger requirement than `A <~< B`. Let's go with the weaker one.

**Comment by jdegoes** [comment]
@TomasMikula That's a strong argument. 👍

**Comment by S11001001** [comment]
If GADTs were better implemented, it wouldn't matter. But they aren't, so switch to `<~<` as you like.

**Comment by fommil** [comment]
other than @S11001001's two blog posts and SI-2509, does anybody have an example of when Liskov works better than standand subtyping bounds?

I had an example to motivate Liskov over subtypes in my book, but it turned out to be wrong. Basically, why use this instead of `<:` when `<:` works?

**Comment by TomasMikula** [comment]
> Basically, why use this instead of `<:` when `<:` works?

When designing an API that requires `<:`, how do you tell whether `<:` will work for the user? You can't.

There are cases where we can provide `Liskov` via unsafe `force`, justified by some external reasoning (such as the reasoning in [When can Liskov be lifted?](https://typelevel.org/blog/2014/03/09/liskov_lifting.html)), but cannot convince the compiler of `<:`. In that case, if we need to use an API that requires `<:`, we are out of luck, because we only have `Liskov` at hand.

**Comment by fommil** [comment]
I somehow missed *that* blog post, thanks!

**Comment by TomasMikula** [comment]
Other examples (that is, other than the `Functor` data types mentioned in that post) of externally justified Liskov include (in scalaz 8):
 - universal instantiation: [`∀[F] <~< F[A]`](https://github.com/scalaz/scalaz/blob/104861bb8c7974fa6e09a6c15b244c260dab8403/base/shared/src/main/scala/scalaz/data/Forall.scala#L26), for any `F[_]` and `A`;
 - [`Fix[F] <~< Fix[G]`](https://github.com/scalaz/scalaz/blob/104861bb8c7974fa6e09a6c15b244c260dab8403/base/shared/src/main/scala/scalaz/data/Fix.scala#L18), if `F[_]` is covariant and a subtype of `G[_]`.

**Comment by alexknvl** [comment]
@TomasMikula You can go from `<~<` to `<:`, although it requires some minor modifications to `<~<` (making it a tad bit more powerful). For example, see https://github.com/alexknvl/leibniz/blob/master/src/main/scala/leibniz/As.scala#L18

**Comment by TomasMikula** [comment]
Cool stuff!

As far as I understand, from `A <~< B` you don't exactly derive `A <: B`, but `A <: B1` and `B1 === B`. Though I can see that it enables a workaround, if cumbersome, for perhaps all(?) use cases.

👍  for adding it.

Still, I'd be in favor of APIs with `<~<` instead of `<:` for the sake of ease of use.

**Comment by S11001001** [comment]
Related to #649

**Comment by fommil** [comment]
Good point!

**Comment by Jacoby6000** [comment]
I've worked on this a bit now, and it has some (small) type inference implications.  If your liskov implicits do not come first in the type params list, things get funky.

This error:
```
[error] /Users/jacobbarber/projects/scalaz/core/src/main/scala/scalaz/Either.scala:442: ambiguous implicit values:
[error]  both value evidence$10 of type scalaz.Show[B]
[error]  and value evidence$9 of type scalaz.Show[A]
[error]  match expected type scalaz.Show[AA]
[error]     Show.show(_.show)
```

Came from this method:
```scala
  implicit def DisjunctionShow[A: Show, B: Show]: Show[A \/ B] =
    Show.show(_.show)
```

Which is invoking
```scala
  def show[AA, BB](implicit SA: Show[AA], SB: Show[BB], evA: A <~< AA, evB: B <~< BB): Cord =
```

Moving the `<~<` implicits to the front of the args list fixed the issue.  Thanks @edmundnoble for that suggestion.


This doesn't justify not moving to liskov, but its something to be aware of.

**Comment by fommil** [comment]
that sucks, this makes it incompatible with context bounds? I like context bounds.

In this particular case I have a far better way of deriving `Show` ;-)

**Comment by Jacoby6000** [comment]
I think its just more of a reason to make a compiler plugin substituting `<:` , or providing a way to do liskov similar to scala's notation for subtypes.  People using liskov shouldn't have to try so hard anyway!

**Comment by TomasMikula** [comment]
> ```scala
> def show[AA, BB](implicit SA: Show[AA], SB: Show[BB], evA: A <~< AA, evB: B <~< BB): Cord
> ```

Is it really useful to have subtyping on that method? As opposed to just

```scala
def show(implicit SA: Show[A], SB: Show[B]): Cord
```

**Comment by Jacoby6000** [comment]
I'm not sure. 

In this scenario:
```scala
sealed trait Foo
case class Bar(...) extends Foo
case class Baz(...) extends Foo

implicit val show: Show[Foo] = ...

Show[String \/ Bar]
```

`Show[String \/ Bar]` is derivable because of the subtype relationship (assuming I'm understanding correctly).  However, since disjunction is covariant I wonder if it matters. I'll mess around with it and see what happens.  If Disjunction were invariant, it is definitely necessary I think.

**Comment by TomasMikula** [comment]
Suppose Disjunction _is_ invariant. How common is it to request `Show[String \/ Bar]` (instead of `Show[String \/ Foo]`) and should we cater to those use-cases?

**Comment by fommil** [comment]
@TomasMikula :+1: :100: I do not think we should be catering for these cases... we have `.widen` for this sort of thing, it shouldn't be mixed up with the core functionality.

**Comment by fommil** [comment]
perhaps this should come after https://github.com/scalaz/scalaz/issues/1469 and friends?

**Comment by Jacoby6000** [comment]
I'll go back and change the way that works then.  I'll keep my eye out for similar things.
