### ISSUE TITLE
remove leaking Memo.mutableMapMemo

### ISSUE THREAD

**Issue by fommil** [scalaz/scalaz#1488]
`Memo.mutableMapMemo` allows leaking of mutable state... how do people feel about that?

**Comment by jbgi** [comment]
looks also not thread-safe. 👎

**Comment by fommil** [comment]
kill it! Well, make it private. If somebody really wants to share a mutable map then they can write their own impl using `Memo.memo`.

From a purely performance point of view, it seems wrong that we'd use the scala mutable collections instead of the concurrent Java ones.

But further than that, it seems wrong that we'd encourage the use of `.hashCode` of the `K`. We have perfectly good scalaz data structures that could be used instead, and require `Equal` /  `Order`. I guess we're missing a `Hash` and `IHashMap`.

**Comment by fommil** [comment]
`doubleArrayMemo` should probably take a positively refined `Int` (or a `Byte` / `Short`) as index to get some kind of sensible memory bounds.

**Comment by fommil** [comment]
the `sentinel` check doesn't  even consider `Double.NaN`.... sheesh.

**Comment by fommil** [comment]
`Memo` is sooo broken.

**Comment by fommil** [comment]
I vote to `@deprecating` a lot of these methods... but the core concept of `Memo` is pretty solid and it deserves good implementations.

**Comment by fommil** [comment]
It seems dangerous that a `Memo` can be attached around different functions that have the same type signature. I think I'd feel more comfortable if it was constructed with the `K => V` and `apply` was `def apply(k: K): V`

**Comment by fommil** [comment]
a backend using `identityMap` would be useful. I have some usecases where I know a function is going to be called multiple times in succession with the same input parameter and it would be useful to cache that, but not at the cost of demanding `Equal` or `Hash` instances.
