### ISSUE TITLE
Add Void

### ISSUE THREAD

**Issue by jdegoes** [scalaz/scalaz#1491]
```scala
final abstract class Void private () {
  def absurd[A]: A
}
```

**EDIT**: Improved version below by @puffnfresh and @TomasMikula:

```scala
case class Void(underlying: Nothing) extends AnyVal
```

with corresponding instances (`Show`, `Monoid`, etc.).

**EDIT**: Suggested by @alexknvl:

```scala
type Void <: Nothing with Void.Tag
object Void {
  private[scalaz] trait Tag extends Any

  implicit val showVoid: Show[Void] = ???
}
```

**Comment by TomasMikula** [comment]
I guess `Nothing` doesn't work for you.

Would

```scala
type Void = Nothing { type T }
```

fix the problem? (Taken from scala/bug#9453)

**Comment by puffnfresh** [comment]
@TomasMikula `Void` should have instances.

**Comment by puffnfresh** [comment]
Could AnyVal be useful for that?

```scala
case class Void(underlying: Nothing { type T }) extends AnyVal
```

**Comment by jdegoes** [comment]
Yes, `Void` should have instances. @TomasMikula Any thoughts on @puffnfresh's representation?

**Comment by jbgi** [comment]
Why `AnyVal` be relevant for an uninhabited type?

**Comment by puffnfresh** [comment]
@jbgi because:

```scala
case class Void(underlying: Nothing { type T })
val x: Void = null // inhabited
```

```scala
case class Void(underlying: Nothing { type T }) extends AnyVal
// val x: Void = null
//  found   : Null(null)
//  required: Void
//        val x: Void = null
```

**Comment by jdegoes** [comment]
@tomasmikula e.g. Show. It would be inconvenient not to be able to Show something with Void as a type parameter.

**Comment by puffnfresh** [comment]
@TomasMikula sorry, Show is not a great example, but it's an easy one:

```haskell
show ([] :: [Void])
```

**Comment by jbgi** [comment]
@puffnfresh  oh I see, nice!

**Comment by puffnfresh** [comment]
I don't think we need the extra refined type, just having a case class works around the bug @TomasMikula referenced:

```scala
case class Void(underlying: Nothing) extends AnyVal

take(??? : Stuff[Void]) // properly inferred, unlike Nothing
```

**Comment by TomasMikula** [comment]
Oh, by having instances you mean typeclass instances, not that it is inhabited. 👍

**Comment by alexknvl** [comment]
I suggest
```scala
type Void <: Nothing
```
defined in a `package object`. It works well with implicit resolution.

**Comment by TomasMikula** [comment]
The problem with that is where to put typeclass instances for `Void`, e.g. `Show[Void]`. It can be done in Scala 2.12.4, but what about earlier versions?

**Comment by jedws** [comment]
> where to put typeclass instances for [type alias]. It can be done in Scala 2.12.4

what is this magic new 2.12.4 feature?

**Comment by alexknvl** [comment]
@TomasMikula 
```scala
type Void <: Nothing with Void.Tag
object Void {
  private[scalaz] trait Tag extends Any
}
```

**Comment by jdegoes** [comment]
@alexknvl Putting the instances inside the type tag companion object is a very cool trick. 👍

**Comment by jdegoes** [comment]
@alexknvl Just to be certain I understand your suggestion:

```scala
type Void <: Nothing with Void.Tag
object Void {
  private[scalaz] trait Tag extends Any

  object Tag {
    implicit val showVoid: Show[Void] = ???
  }
}
```

`showVoid` will be found during implicit resolution search?

**Comment by TomasMikula** [comment]
@jedws scala/scala#6074. With that you can have

```scala
package data {
  trait VoidModule {
    type Void
  }
  object VoidModule {
    implicit def showVoid: Show[Void] = ???
  }
}

package object data {
  val Void: VoidModule = ???
  type Void = Void.Void
}
```

Now if you have
```scala
implicitly[Show[Void]]
```

`Void` is an abstract type, with fully qualified name `data.Void.Void`. In 2.12.4 with `-Xsource:2.13', scalac will add implicit scopes of enclosing types (such as `data.Void.type`) to the implicit scope of `data.Void.Void`. And since `data.Void` has type `VoidModule`, the companion object of `VoidModule` is in implicit scope for `data.Void.type`, thus, as per the previous sentence, in implicit scope for `data.Void.Void`.

**Comment by TomasMikula** [comment]
@alexknvl Nice!

(I guess the `private[scalaz]` modifier doesn't have any effect? It will be publicly visible anyway.)

**Comment by alexknvl** [comment]
@jdegoes 
Even better. `showVoid` can be in the object containing `Tag` and it will still resolve (I tested on 2.12, 2.11; I don't exactly remember if it works on 2.10).
```scala
type Void <: Nothing with Void.Tag
object Void {
  private[scalaz] trait Tag extends Any

  implicit val showVoid: Show[Void] = ???
}
```

@TomasMikula Just to make it a little bit harder to misuse. Won't it be private from outside scalaz? You can also seal it or possibly even make it `sealed abstract class Tag private () extends Any`.

**Comment by TomasMikula** [comment]
> Won't it be invisible from outside scalaz? 

If that was the case, how would the implicit `Show[Void]` be resolved? If at the use site only `type Void <: Nothing` is visible, why should the compiler look for implicits related to `Tag`?

**Comment by alexknvl** [comment]
@TomasMikula Somewhat surprisingly, the compiler ignores privacy in this case.

I just tested this snippet on 2.12, 2.11, 2.10:
```scala
trait VoidDecl {
  import A._
  type Void <: Nothing with Void.Tag
}
object A extends VoidDecl {
  trait Show[A]
  
  object Void {
    sealed trait Tag extends Any

    implicit val showVoid: Show[Void] = new Show[Void] { }
  }
}

import A._

implicitly[Void =:= Nothing]
implicitly[Void <:< Nothing]
implicitly[Nothing <:< Void]
implicitly[Show[Void]]
```

You need to move `type Void` declaration into a separate trait for 2.10, because it doesn't like abstract types in `object`s.

**Comment by TomasMikula** [comment]
> Somewhat surprisingly, the compiler ignores privacy in this case.

That's all I was saying. Even when looking at `Void` from outside `Package`, the compiler knows that `Void <: Tag`, even though `Tag` should not be visible at that place. Now if `Tag` is invisible to the user, how should the poor user figure out where the `Show[Void]` instance is coming from, without studying the source code?

**Comment by jdegoes** [comment]
Is there any drawback at all to the newtype approach?

```scala
case class Void(underlying: Nothing) extends AnyVal
```

I know you cannot now use `Void` in places that expect `Nothing` (or visa versa), but is that a hinderance in practice?

**Comment by alexknvl** [comment]
@TomasMikula By assuming it's in the "companion object" for the type :smile: 

@jdegoes Not that I know of.

```scala
case class Void(underlying: Nothing) extends AnyVal
```
doesn't compile in 2.12 (scastie) because "value class may not be a member of another class".

and
```scala
case class Void(underlying: Nothing)
// Should work even if `AnyVal` was allowed:
null.asInstanceOf[Void]
Array.ofDim[Void](10)
```

**Comment by TomasMikula** [comment]
> By assuming it's in the "companion object" for the type 

I guess that would be acceptable 😀

**Comment by puffnfresh** [comment]
Bloody hell scalac

> java.lang.AssertionError: assertion failed:
>   Cannot emit primitive conversion from Lscala/runtime/Null$; to Lscala/runtime/Nothing$;

What a joke :rofl:

**Comment by puffnfresh** [comment]
https://github.com/scala/bug/issues/10570

**Comment by puffnfresh** [comment]
@alexknvl the bug was fixed in Scala 2.12.3

**Comment by jdegoes** [comment]
So maybe the best solution for now is @alexknvl's suggestion (it's deployed and working properly). Then in Scalaz 8 (2.12.4+) the only question is whether it's better or worse to expose the relationship between `Nothing` and `Void`, which probably comes back to how much magic is built into scalac for `Nothing` and in what ways will this magic interfere with usage of `Void` as an ordinary type.

**Comment by fommil** [comment]
Kenji wants to release 7.3 soon, and nobody has stepped up to do this. I no longer have a usecase. It can always be added later if anybody wants it.
