### ISSUE TITLE
Show String Interpolator Instance

### ISSUE THREAD

**Issue by ChristopherDavenport** [scalaz/scalaz#1495]
Was wondering if there was a reason not to have a string interpolator instance for `Show`. Currently for safety writing `s"${f.shows}"` and it seems that a safe interpolator would be ideal. 

What are your thoughts? I'll happily draft the PR, but if there was a reason you were avoiding it I won't make it.

**Comment by TomasMikula** [comment]
👍

**Comment by jdegoes** [comment]
If it's type safe and runtime safe and makes users lives easier, I'm all for it.

**Comment by ritschwumm** [comment]
yes please - and then disable the s-interpolator in wartremover

**Comment by ChristopherDavenport** [comment]
Closed via #1496

**Comment by jdegoes** [comment]
@christopherdavenport Thanks for the contribution!
