### ISSUE TITLE
replace ev(_) with ev

### ISSUE THREAD

**Issue by fommil** [scalaz/scalaz#1497]
thanks to the implicit conversion `witness` on Liskov / Leibniz, the evidence can be lifted to a function and therefore avoid a method hop. Terser syntax and ever so slightly faster, I like it.

**Comment by TomasMikula** [comment]
Surely pointers to code currently using `ev(_)` would help.

**Comment by fommil** [comment]
a grep finds 3 (btw, I'm creating tickets as TODOs to myself... I'll get around to this once the book is done)
