### ISSUE TITLE
avoid object allocs around Maybe.Empty

### ISSUE THREAD

**Issue by fommil** [scalaz/scalaz#1498]
it should be possible to use `asInstanceOf` to avoid constructing objects when creating an `Empty()` https://github.com/scalaz/scalaz/blob/series/7.3.x/core/src/main/scala/scalaz/Maybe.scala#L152

I believe we can even hijack the `Empty.apply` (and `unapply`) in scala 2.11 and 2.12, but we can at least make `Maybe.empty` return a cast `private val`.

**Comment by jdegoes** [comment]
Yes, this is a good idea. It's fixed in 8 via a different mechanism.

**Comment by fommil** [comment]
looks like something similar is used in `Dequeue`

```
final case object EmptyDequeue extends Dequeue[Nothing] {
  def apply[A]() = this.asInstanceOf[Dequeue[A]]
  def unapply[A](q: Dequeue[A]) = q.isEmpty
}
```
