### ISSUE TITLE
why are methods defined on some data types?

### ISSUE THREAD

**Issue by fommil** [scalaz/scalaz#1499]
It seems to me that there are a lot of benefits to writing code in Haskell style where data types are clean (do not have any OOP methods defined on them), with functionality  provided via typeclass instances or implicit classes (where there is no generalisation of the functionality).

However, it confuses and pains me a little to see core data types like `Maybe` define methods in OOP style. It feels very inconsistent to me and introduces a needless style choice for authors.

Given that IDEs are good at detecting extension methods nowadays, is there any reason to prefer OOP in the data types over a more principled approach? I suspect somebody will say "compile times" but I have anecdotal evidence to the contrary (in my work project) that it does not impact compile times, so I'll need to see evidence if that's the case.

**Comment by fommil** [comment]
I think I have the answer now from IRC... basically historical workarounds to type inference problems. If anybody has specific examples where this style is needed today to workaround type inference problems, I'd appreciate them.

**Comment by jdegoes** [comment]
I read somewhere that in Scalaz 8, it's preferred to move functionality away from data and into type classes. The question is what to do about functionality that doesn't fit into any type class but is specific to a data type — does that go on the data type as a method (the OO way), or does that too, go into a separate function (the FP way)?

There may be performance implications. I haven't investigated. If there are not, I have no strong preference either way, since the syntax is the same.

**Comment by TomasMikula** [comment]
I need some clarification about what you mean by OOP style and Haskell/FP style. Does `.` already mean OOP?

There are at least 4 styles:

 1. Clearly OOP.
    ```scala
    sealed abstract class Maybe[A] {
      def isEmpty: Boolean
    }
    case class Just[A](a: A) extends Maybe[A] {
      def isEmpty = false
    }
    case class Empty[A]() extends Maybe[A] {
      def isEmpty = true
    }
    ```

    I think there's agreement to avoid this style, except to work around a type-inference/pattern matching limitation.

 2. Does this still count as OOP? I consider this FP and don't have any problem with it.
    ```scala
    sealed abstract class Maybe[A] {
      final def isEmpty: Boolean = this match {
        case Just(_) => false
        case Empty() => true
      }
    }
    case class Just[A](a: A) extends Maybe[A]
    case class Empty[A]() extends Maybe[A]
    ```

 3. Via syntactic enrichments.
    ```scala
    sealed abstract class Maybe[A]
    case class Just[A](a: A) extends Maybe[A]
    case class Empty[A]() extends Maybe[A]

    implicit final class MaybeOps[A](self: Maybe[A]) extends AnyVal {
      def isEmpty: Boolean = self match {
        case Just(_) => false
        case Empty() => true
      }
    }
    ```

    I don't see this as necessarily cleaner than the previous style. However, it is necessary for abstract (opaque) types.

 4. Clearly FP.
    ```scala
    sealed abstract class Maybe[A]
    case class Just[A](a: A) extends Maybe[A]
    case class Empty[A]() extends Maybe[A]

    object Maybe {
      def isEmpty[A](ma: Maybe[A]): Boolean = ma match {
        case Just(_) => false
        case Empty() => true
      }
    }
    ```

    This loses the "power of the dot" and infix notation, so I'm not a big fan, but it's OK to have it in addition (not as a replacement for) 2. or 3.

I omitted the "operations via typeclass" style, because I believe that if someone's working with a concrete data type, it should be usable without any typeclass instances.

**Comment by jdegoes** [comment]
@tomasmikula These are largely my thoughts. 👍

One clarification: Does “useable without type classes” mean duplicating methods also available in type classes?

**Comment by fommil** [comment]
Yeah, that's more or less my thoughts too, but I'd consider 2 to be OOP style since the methods are defined on the class rather than separately like 3 or 4.

It gets a little grayer when the method defined on the class is duplicating something that is provided by a typeclass, and even grayer if it has a subtely different type signature (e.g. only because I'm currently looking at it, `\/.orElse` vs `Optional.orElse`)

**Comment by jdegoes** [comment]
At the very least, I think in our upcoming style guide, we should answer the question of where to put what (and by extension, where to find what).

**Comment by TomasMikula** [comment]
> One clarification: Does “useable without type classes” mean duplicating methods also available in type classes?

> It gets a little grayer when the method defined on the class is duplicating something that is provided by a typeclass

Implement on the class (or companion object for smart constructors). Let the typeclass method call the class/companion method. So yes, there will be duplication in method signatures, but not in implementation.
