### ISSUE TITLE
\&/.+++

### ISSUE THREAD

**Issue by fommil** [scalaz/scalaz#1501]
`These` seems to be missing a `+++` alias to `append`, the odd one out with disjunction and validation.

**Comment by fommil** [comment]
hmm, no I've convinced myself that it's not consistent enough with `+++` or `+|+` to be able to share the operator. It'd need a new one... maybe `+&+` and that just looks drunk.

**Comment by ChristopherDavenport** [comment]
`+&+` does look drunk for some reason. I'm mystified that `+|+` looks ok but the former puts me so ill at ease.

**Comment by fommil** [comment]
I think `+|+` looks a bit like a stupified c3p0
