### ISSUE TITLE
ImmutableArray has unsafe methods

### ISSUE THREAD

**Issue by fommil** [scalaz/scalaz#1506]
```scala
sealed abstract class ImmutableArray[+A] {
  def apply(index: Int): A
  def copyToArray[B >: A](xs: Array[B], start: Int, len: Int): Unit
  def slice(from: Int, until: Int): ImmutableArray[A]
  def toArray[B >: A : ClassTag]: Array[B]
  ...
}

object ImmutableArray {
  def make[A](x: AnyRef): ImmutableArray[A] = ...
  def fromArray[A](x: Array[A]): ImmutableArray[A] = ...
  ...
}
```

these are all unsafe and should be removed or replaced with total variants. `fromArray` could perhaps survive as `unsafeFromArray` for performance reasons... i.e. only allowed if the caller promises that they are not retaining a reference to `x`. (looking closer it appears that there is a `.clone` in the constructor of `ImmutableArray1` but it feels like this should be done in the constructor not the body of the class)

Also wrapping an invariant data structure with a covariant type parameter seems like a troublesome thing to do.

I'm also a little confused why `elemTag` needs to persist in the API... I thought this was only needed for construction.

And pretty much everything to do with `Builder` is unsafe too... all mutable.

**Comment by fommil** [comment]
Interesting that there are no instances for `Applicative` or `Monad`... I would have expected much the same as for `List`.

**Comment by xuwei-k** [comment]
> Interesting that there are no instances for Applicative or Monad... I would have expected much the same as for List. If we drop the need to support primitives in all the typeclasses, I'm sure more is possible. It's not like scalaz is really doing specialisation anywhere else...

I have created a library a few years ago :)
https://github.com/xuwei-k/iarray

**Comment by fommil** [comment]
Why am I not surprised? :-D

**Comment by jdegoes** [comment]
@xuwei-k Will you donate it to Scalaz 8? 😄 

One can argue that there is no need for an immutable array, that such code should always use `STArray`. For chunked streams, it's convenient and an efficient encoding is required.

**Comment by xuwei-k** [comment]
> Will you donate it to Scalaz 8? 😄

Sure 👍 

> One can argue that there is no need for an immutable array, that such code should always use STArray

STArray is useful in Haskell. but maybe SArray performance is poor in Scala 😟

**Comment by jdegoes** [comment]
It's true. Users need to be able to operate on the whole array in a while loop or equivalent. i.e. import "impure array code" into a `STArray` operation, in a similar way to importing impure sync code into `IO`.
