### ISSUE TITLE
what is the point of NonEmptyIList?

### ISSUE THREAD

**Issue by fommil** [scalaz/scalaz#1507]
```scala
  type NonEmptyIList[A] = OneAnd[IList, A]
```

given that `NonEmptyList` exists, is there any point in this alias? It only confuses the issue by encouraging the use of two things for the same purpose.

**Comment by puffnfresh** [comment]
e.g. `Comonad[NonEmptyList]`

**Comment by puffnfresh** [comment]
Oh, I missed `NonEmptyIList` vs `NonEmptyList`.

**Comment by fommil** [comment]
Yeah, I went back and checked the codebase after I found this crazy thing and I was staring at it and didn't even notice it. If a I'm ever going to tell a codebase, I'm introducing the equivalent of NonEmptyIList and just leaving it there behind a radiator to get all sweaty.
