### ISSUE TITLE
FromFoldable and FromFoldable1

### ISSUE THREAD

**Issue by fommil** [scalaz/scalaz#1513]
Maybe I'm not fully grokking `Unfoldable` (which should probably have a ticket) but I found myself needing these trivial little things

```scala
trait FromFoldable[F[_]] {
  def fromFoldable[G[_]: Foldable, A](g: G[A]): F[A]
}
trait FromFoldable1[F[_]] {
  def fromFoldable1[G[_]: Foldable1, A](g: G[A]): F[A]
}
```

with mostly trivial implementations that all our data types could have and could have a `CanBuildFrom` implicit for legacy reasons. This allows the removal of a lot of methods across the board that are effectively `Foldable.toAHardCodedDataType`

I guess what we lose is the ability for `Foldable[IList]` to have an optimal `toIList` method, and such, which is maybe an argument to retain some hardcoded methods on Foldable.

Possibly related to #1452 and #1448

**Comment by jbgi** [comment]
@fommil did you have a look at  `Reducer` (and maybe `Generator`)? I think they could help.

In particular I think we could add the following to `Foldable`:
```scala
  def reduceTo[A, M](fa: F[A])(implicit M: Reducer[A, M]): M = ???
  def to[A, F[_]](fa: F[A])(implicit M: Reducer[A, F[A]]): F[A] = reduceTo[F[A]]
```
But maybe there is already a better way that I did not see.

**Comment by Jacoby6000** [comment]
@jbgi interestingly, it looks like `ReducerOps` has those exact methods hidden inside a sealed abstract class, `UnfoldTo`.
https://github.com/scalaz/scalaz/blob/1a01e0017a9bbc1d07b13a3825e2c7367d0bf624/core/src/main/scala/scalaz/syntax/ReducerOps.scala#L47

**Comment by fommil** [comment]
I love deleting hacky code that I wrote :smile: I'll take a look and report back tonight.

We should definitely get these added to `Foldable`. For 7.3 I'm all in favour of removing the stdlib collection methods on Foldable and requiring people to "reduce" to a `LiterallyCantEvenBuildFrom`

**Comment by fommil** [comment]
I think I need a `Reducer1` (for non empty things)

**Comment by jbgi** [comment]
@fommil  yes, could be worth solving https://github.com/scalaz/scalaz/issues/1038 for 7.3

**Comment by fommil** [comment]
https://hackage.haskell.org/package/reducers-3.12.2/docs/Data-Semigroup-Reducer.html

**Comment by fommil** [comment]
@jbgi I'm still not getting `Reducer`... can you please show me an example of using it to create a `NonEmptyList` from a `Foldable`?

**Comment by jbgi** [comment]
Yeah, will try to put together a Reducer1 over the holidays

**Comment by fommil** [comment]
I'm going to close this in the hope that reducers will solve the issue of creating a data structure from a list / nel
