### ISSUE TITLE
eager evaluation of EphemeralStream.traverse

### ISSUE THREAD

**Issue by fommil** [scalaz/scalaz#1515]
the following shows EphemeralStream eagerly evaluating all elements when used is `stream.traverse(f)` where the other type constructor is `Id`. Notably, this does *not* happen for stdlib `Stream`

```scala
import scala.language.higherKinds
import scalaz._, Scalaz._
import EphemeralStream.{ fromStream, EStream }

object Laziness {
  def testing[G[_]: Applicative](s: EStream[Int])(f: Int => G[Int]) =
    s.traverse(f)

  def main(args: scala.Array[String]): scala.Unit = {
    val stream = EphemeralStream.iterate(0) { i =>
      println(i)
      i + 1
    }

    val trav = testing[Id](stream)(identity)
    println(trav)
  }
}

```

**Comment by fommil** [comment]
possible reason

```
  def foldRight[B](z: => B)(f: (=> A) => (=> B) => B): B =
    if (isEmpty) z else f(head())(tail().foldRight(z)(f))
```

both `head()` and `tail()` will evaluate their contents even though the `f` can take lazy parameters.

Also, note that this is actually `foldr` (curried), not the usual `Foldable.foldRight`

Same thing in the Traverse impl

```
    override def foldRight[A, B](fa: EphemeralStream[A], z: => B)(f: (A, => B) => B): B =
      if(fa.isEmpty) z else f(fa.head(), foldRight(fa.tail(), z)(f))

```

**Comment by fommil** [comment]
This is the repeating stacktrace

```
background log: error: 	at scalaz.IdInstances$$anon$1.ap(Id.scala:57)
background log: error: 	at scalaz.Apply.ap2(Apply.scala:49)
background log: error: 	at scalaz.Apply.ap2$(Apply.scala:48)
background log: error: 	at scalaz.IdInstances$$anon$1.ap2(Id.scala:19)
background log: error: 	at scalaz.Applicative.apply2(Applicative.scala:32)
background log: error: 	at scalaz.Applicative.apply2$(Applicative.scala:31)
background log: error: 	at scalaz.IdInstances$$anon$1.apply2(Id.scala:19)
background log: error: 	at scalaz.EphemeralStreamInstances$$anon$1.$anonfun$traverseImpl$4(EphemeralStream.scala:208)
background log: error: 	at scalaz.EphemeralStream.foldRight(EphemeralStream.scala:37)
background log: error: 	at scalaz.EphemeralStream.$anonfun$foldRight$2(EphemeralStream.scala:37)

```

**Comment by fommil** [comment]
maybe this

```
    def traverseImpl[G[_], A, B](fa: EphemeralStream[A])(f: A => G[B])(implicit G: Applicative[G]): G[EphemeralStream[B]] = {
      val seed: G[EphemeralStream[B]] = G.point(EphemeralStream[B]())

      fa.foldRight(seed) {
        x => ys => G.apply2(f(x), ys)((b, bs) => EphemeralStream.cons(b, bs))
      }
    }
```

should be rewritten to use the `foldRight` in the typeclass implementation rather than the native one on the class.

**Comment by fommil** [comment]
nope, changing to

```
        foldRight(fa, seed) { (x, ys) =>
          G.apply2(f(x), ys)((b, bs) => EphemeralStream.cons(b, bs))
        }
```

doesn't make a difference

**Comment by TomasMikula** [comment]
I think this is impossible to fix. To get the accumulated effect `G`, you have to eagerly evaluate all elements (modulo short-circuiting on failure), unless `G` is lazy.

If you want to have an effect at each step instead of one accumulated effect for the whole stream, use `StreamT`.

**Comment by fommil** [comment]
But why is it possible for stdlib Stream ? OneAnd is also broken.

I'm not sure an EStream with eager traverse is of much use, traverse is one of the most common things I do.

Incidentally, the also need an IStream.

**Comment by TomasMikula** [comment]
> But why is it possible for stdlib Stream ?

What, exactly, is possible for stdlib Stream?

**Comment by fommil** [comment]
`stream.traverse`... it doesn't eagerly evaluate all elements. I added it to the linked PR / failing test to show that it is working. I think `EStream` and `OneAnd` should do whatever `Stream` is doing but I cannot work out *why* it is ok.

**Comment by TomasMikula** [comment]
Huh, you're right. But the fact that it works for `Id` is more of a curiosity, IMO. It doesn't work for, say, `Option`, or any other non-lazy monad (and even for a lazy one, you would evaluate the whole source stream before you could get your hands on the result stream). If you only mean to `traverse` with `Id`, you can just as well use `map`. Otherwise, you should expect `traverse` to evaluate the whole stream.

**Comment by TomasMikula** [comment]
That said, I'm not against making the implementation match what's done for std Stream, but I'm not too excited about what will be achieved by that.

**Comment by fommil** [comment]
`Id` is just the minimised bug reproduction, I ran into this in `scalaz-deriving` https://gitlab.com/fommil/scalaz-deriving/blob/master/scalaz-deriving/src/main/scala/scalaz/IotaHelpers.scala#L149-175 where the effect is an arbitrary `Monad` and `Stream` seems to have much better behaviour than `EStream`. Admittedly, one of my examples is using `Id` as the `Monad` so this could be a curiosity, as you say.

The thing is that I can't make the implementation match std `Stream`, no matter what I do it evaluates eagerly and *I don't know why* :confused:

**Comment by TomasMikula** [comment]
> where the effect is an arbitrary `Monad` and `Stream` seems to have much better behaviour than `EStream`

Do you see better behavior with a monad other than `Id`?

> The thing is that I can't make the implementation match std `Stream`, no matter what I do it evaluates eagerly and `I don't know why`

By a quick look I can't tell either 😕

**Comment by fommil** [comment]
I was going to use Stream/EStream as the inner monad, but maybe I really mean to be using MonadPlus which feels like it could be done lazily (i.e. filtering out failures rather than collapsing the entire result).

**Comment by TomasMikula** [comment]
Have you given consideration to StreamT?

**Comment by fommil** [comment]
Now that you've mentioned it, I'll look into it... but I'd still like to get to the bottom of why EStream and Stream traverse behave differently at least for `Id`. Out of morbid curiosity at this point.
