### ISSUE TITLE
Foldable1.head

### ISSUE THREAD

**Issue by fommil** [scalaz/scalaz#1517]
It would be good to have the ability to get a guaranteed element from a `Foldable1`, I have a usecase in `scalaz-deriving` where a typeclass derivation can choose one of many things and arbitrarily wishes to choose the `index(0).get` (which means calling a non-total function despite knowing it will always succeed).

**Comment by Jacoby6000** [comment]
Provided the definition of `Foldable1` I think its reasonable to leave this abstract and up to the implementor to include.

Alternatively, `head` could be defined using an invocation to foldMap1, using a semigroup that always returns the left side.

**Comment by fommil** [comment]
I tried with `foldRight` doing something similar but many data types were iterating the entire thing...
