### ISSUE TITLE
[8.0.x] Disjunction cases, syntax not in Prelude

### ISSUE THREAD

**Issue by NeQuissimus** [scalaz/scalaz#1523]
When I played with `Disjunction` for #1522, I noticed that I needed imports to get to the syntax bits as well as the deconstruction (the two case classes `\/-` and `-\/` are in an object)

I don't think a user should have to specifically add these imports to do such basic things...

```
import data.Disjunction._
import data.Disjunction.Syntax._
```

**Comment by TomasMikula** [comment]
👍

**Comment by NeQuissimus** [comment]
This is no longer required after #1586
