### ISSUE TITLE
[8.0.x] Keep the Prelude clean - Discussion

### ISSUE THREAD

**Issue by NeQuissimus** [scalaz/scalaz#1528]
There was a little bit of a discussion in #1521 about what should and should not be in the `Prelude`.

I propose that "convenience" methods and implicits, i.e. everything that is "Ops" or "Syntax", reside in some secondary object.
That way the actual `Prelude` would stay mean and clean and users can choose whether to include convenience structures.

Probably relevant for #1526 

This is open for opinions and ideas

**Comment by jdegoes** [comment]
My preferences would be for the following:

1. Type names, top-level function names, and extension method names chosen to be unambiguous within all of Scalaz, and low (but non-zero) chance of collision outside Scalaz.
2. All types, syntax, and top-level functions available in a single import, e.g. `import Scalaz._`, with no major effect on compilation time.

For new users especially, figuring out what to import can be quite confusing. This is all the more true in Scalaz 7, which has orphan instances and inconsistencies. In Scalaz 8, I'd like to make this completely simple and as fool-proof as possible.

I don't mind _also_ having a single import to bring types (but not top-level functions or extension methods) into scope and allowing ala carte imports with a completely consistent methodology. But I feel that is _not_ the case to optimize for, it's a case for power users who know exactly what they're doing.

**Comment by NeQuissimus** [comment]
I agree with the simplicity that is required for newcomers. When I started using Scalaz, all the implicits were awfully confusing, so I was happy I could just `import scalaz._; import Scalaz._`.
Whether we use the top-level package or an object should not matter too much. As long as there is the option for the "poweruser" to only import what they need and for the "newb" to get everything in one or two imports.

**Comment by jdegoes** [comment]
So perhaps we should figure out where to put what:

 * `import scalaz._` — Make this the "one import to rule them all"?
 * `import scalaz.Prelude._` — Import "all types" and "all modules"? What about syntax? What about helper functions? What about orphan instances (if we have any)?

**Comment by NeQuissimus** [comment]
I would not even mind keeping it the "old way" at all!

`import scalaz._` for the necessities, `import scalaz._; import Scalaz._` for everything.
Why rename/reinvent what has been working well and users are familiar with?

**Comment by NeQuissimus** [comment]
In a way, this is relevant to #1533... We have cross-contaminated the issues a bit...

Anyways, here is what I propose (which is close to 7.x but I just want to detail it out):

`import scalaz._`

- All the types (type aliases, type classes, data types etc.) are imported
- Constructors and deconstructors(? I mean an unapply to pattern match) must be available
- Absolute minimum for working with Scalaz, as few implicits as possible

`import scalaz.Scalaz._`

- Type class instances are imported
- Syntax is imported
- Anything that makes Scalaz more convenient to use

Importing both should give me *everything* Scalaz has to offer.

Additionally, I would suggest we allow for things like `import scalaz.data._` to be the data class equivalent of `import scalaz._` (which brings **all** types).
I could imagine the package object `scalaz` to just be a logical sum of all the package objects defined in #1540.

*Food for thought...*

I am looking at these things from a user's perspective for the most part, so let me know if there are issues with the above...
