### ISSUE TITLE
stringops parse methods should not encourage exceptions

### ISSUE THREAD

**Issue by fommil** [scalaz/scalaz#1590]
the return type of the parse methods in the string ops/syntax uses IllegalArgumentException and NumberFormat etc, which is leakage of bad jvm details. It would be better if we used String as the error type and included more information about the failure, e.g. I've been using this in some decoder code

```
  @inline private def str[A](f: String => A)(implicit A: ClassTag[A]): XDecoder[A] =
    string.andThen { s =>
      try Right(f(s))
      catch {
        case NonFatal(t) =>
          Left(s"expected $A in '$txt', failed: ${t.getMessage}")
      }
    }
```

**Comment by NeQuissimus** [comment]
I've used this from time to time: https://gist.github.com/NeQuissimus/d778e7b621dd2a23cc77d869594bdb64

Is that what you mean?

**Comment by fommil** [comment]
@NeQuissimus yes! Much better than what we have. Although two comments about your gist

- I'm not a fan of type aliases to `String`, it'd rather just see `String` in the sigs
- Your error messages do not include the original string. It's usually nice to see something like `"'Falze' is neither 'true' nor 'false'"`

**Comment by ritschwumm** [comment]
string as an error type sounds a bit lacking - sometime you want to know precisely _why_ parsing e.g. a number went wrong.

**Comment by ritschwumm** [comment]
string as an error type sounds a bit lacking - sometime you want to know precisely _why_ parsing e.g. a number went wrong. or at least at which position in the input string.

**Comment by fommil** [comment]
@ritschwumm but that's exactly what the proposed string message gives you. The java exceptions are useless in this regard. We'll recover what we can from the exception message but wrap it in a contextual message.

**Comment by jbgi** [comment]
> I'm not a fan of type aliases to String, it'd rather just see String in the sigs

I'd rather we use a newtype, it's free after all (at least from 7.3 onward).

**Comment by ritschwumm** [comment]
@fommil for me as a human, it does. but i might prefer dealing with the errors in code. maybe some ADT might make more sense here?

**Comment by fommil** [comment]
@ritschwumm an ADT may be too much, but still better than an exception. How about a case class that has the original string, the exception error, and an optional position? (if there is any way to extract that from the exception).

**Comment by fommil** [comment]
Actually, scratch that... we really don't need to know which character an int / double / other primitive parser failed on. It's always obvious from the context of the input string. And, indeed, there is very little argument for having an error type at all: `Maybe` is enough and an error message can be constructed from that if desired: "`foo` is not a number".

**Comment by ritschwumm** [comment]
depends - i've found myself grepping through some input files to find the offending input i saw in an error message.

if you return an Option, people tend not to pass on the original string to somewhere i can see. that's why i usually return Either[String,T] nowadays where the String on the left is the original, unparsed value - to encourage people to at least write it to the logfile.

**Comment by fommil** [comment]
@ritschwumm yup, for my APIs that require an Either that's probably what I'd do as well. But that can be constructed from the input so I don't think the core methods need to do it. i.e.

```
s => s.parseInt.toRight(s)
```
