### ISSUE TITLE
pattern matcher for IList

### ISSUE THREAD

**Issue by fommil** [scalaz/scalaz#1591]
As much as I prefer using IList over stdlib List, I do miss the convenient pattern matcher syntax.

I noticed we have some nice syntax for EphemeralStream, could we perhaps do something similar for IList?

**Comment by tonymorris** [comment]
There are not many functions for list that cannot be written using the typical library functions that you the pattern-matching for you. However, that fact ignores any performance concerns.

**Comment by fommil** [comment]
That's true, although I tend to write a lot of encoders and decoders and being able to differentiate between "one thing in a list" vs "two things in a list" comes up a lot for me.
