### ISSUE TITLE
FingerTree needs a rewrite

### ISSUE THREAD

**Issue by fommil** [scalaz/scalaz#1609]
The original paper on the FingerTree is http://www.staff.city.ac.uk/~ross/papers/FingerTree.html

which has one type parameter. We have two (although admitedly, the original paper does also annotate with a custom Monoid), and we also carry a `Reducer` around on every single ADT element. This is both inconsistent (e.g. we have had long discussions about the possibility of `ISet` holding an `Order`) and very bad on memory consumption (64 bits per entry). In addition, much of the internal detail leaks out into the `scalaz` namespace, e.g. `scalaz.ViewL` and `scalaz.Node` is a thing (which causes annoying import problems because `Node` is the kind of thing that pops up a lot). It also appears to use multiple ADT encodings instead of just using private sealed abstract classes and final case classes, and arbitrary use of laziness.

I propose that scalaz8's `FingerTree` is rewritten more in the style of the original paper. It's a wonderful data structure that we've butchered.

**Comment by jbgi** [comment]
:+1:
this was also my sentiment when I saw the impact of https://github.com/scalaz/scalaz/pull/1602 on `FingerTree`.

**Comment by emilypi** [comment]
I'm on it my dudes. We've got a working repo [here](https://gitlab.com/emilypi/FingerTree) to track a more up to date candidate for a full rewrite of `FingerTree`, `Reduce(r)`, `Node`, `Tree`, and `StrictTree`.
