### ISSUE TITLE
CHAMP Hash

### ISSUE THREAD

**Issue by fommil** [scalaz/scalaz#1622]
This seems very exciting... maybe we should have something similar in scalaz 7.3 and scalaz 8, but using typeclasses to provide the equal / hash https://github.com/scala/collection-strawman/pull/342 and no unsafe methods.

**Comment by msteindorfer** [comment]
@fommil a Champ implementation using type classes for `equals` and `hashCode` would definitely be great and shouldn't take to much effort to implement.

Furthermore, type-safety can easily be restored by splitting the untyped `content: Array[Any]` into two typed arrays (one for payload and one for sub-nodes) at the expense trading up memory for type-safety.

**Comment by NeQuissimus** [comment]
For 8.0.x I would refer to #1807
