### ISSUE TITLE
Enum range constructors return Diev

### ISSUE THREAD

**Issue by fommil** [scalaz/scalaz#1624]
It would be nice if the things like `1 |==> 10` returned a `Diev` instead of `List` / `Stream`. It's basically designed exactly for this usecase.

**Comment by fommil** [comment]
and while we're at it, `Diev` could do with a rewrite for scalaz8 to use trees... I don't see why Vector is better. And remove that implicit from the case class.

**Comment by tonymorris** [comment]
link to `Diev`?

**Comment by tonymorris** [comment]
link to `Diev`?

**Comment by fommil** [comment]
@tonymorris brace yourself... https://github.com/scalaz/scalaz/blob/series/7.3.x/core/src/main/scala/scalaz/Diev.scala

You may need to read the paper, and the haskell impl, afterwards...

- http://web.engr.oregonstate.edu/~erwig/papers/Diet_JFP98.pdf
- http://web.engr.oregonstate.edu/~erwig/diet/diet.hs.txt

**Comment by tonymorris** [comment]
Yeah I've read the paper, and written in Haskell a while ago.
https://hackage.haskell.org/package/diet

I thought I also wrote it in Scala once upon a time. I agree that `Vector` has zero, or almost zero, use-cases. It was a hyped data structure a while back and that hype drowned out any critical discussion.

Why the rewrite though?

**Comment by fommil** [comment]
I'd advocate a scalaz8 rewrite because 1) don't use `Vector` 2) don't hold the `Enum` typeclass on the data structure (rely on typeclass coherence instead).

Mostly I just don't understand why a flat structure like `Vector` is being used... we could use `IList` in its place and it wouldn't change anything. The entire point of the paper was to use an ordered tree and that appears to have been lost in our implementation. Now we're just doing all kinds of binary searches to workaround the fact that our data structure... has no data structure.

I'm not sure where your version has gone but the one in scalaz 7 has been written by Sean Parsons, coauthored with Lars.
