### ISSUE TITLE
publish for Scala 2.13.0-M3, please?

### ISSUE THREAD

**Issue by SethTisue** [scalaz/scalaz#1634]
prerequisite: #1629 

also prerequisite, I believe: https://github.com/non/kind-projector/issues/63

**Comment by xuwei-k** [comment]
published scalaz `7.2.19` without `scalacheck_sjs0.6_2.13.0-M3`

**Comment by xuwei-k** [comment]
published `scalaz-scalacheck-binding_sjs0.6_2.13.0-M3`

**Comment by SethTisue** [comment]
wonderful, thank you!
