### ISSUE TITLE
OptionalSyntax liftMonadPlus

### ISSUE THREAD

**Issue by fommil** [scalaz/scalaz#1653]
I found myself wanting some nice syntax to avoid cata boilerplate when lifting an Optional thing into a MonadPlus

e.g. instead of

```scala
trait Twitter[F[_]] {
  def getUser(name: String): F[Maybe[User]]
  def getStars(user: User): F[Int]
}

def stars[F[_]: MonadPlus](user: String): F[Int] = for {
  user  <- getUser(name).cata(MonadPlus[F].point, MonadPlus[F].empty)
  stars <- getStars(user)
} yield stars
```

```scala
def stars[F[_]: MonadPlus](user: String): F[Int] = for {
  user  <- getUser(name).liftMonadPlus
  stars <- getStars(user)
} yield stars
```

what do people think about adding this to OptionalSyntax? Should be fairly trivial. It just seems obvious to me and I was wondering if there is a reason not to do it.

Proposed impl

```scala
implicit class OptionalExtraSyntax[O[_]: Optional](o: O) {
  def liftOpt[A, F[_]: MonadPlus]: F[A] =
    o.toMaybe.cata(MonadPlus[F].point, MonadPlus[F].empty)
}
```

or possibly with ApplicativePlus.

(maybe I should raise a PR...)

**Comment by fommil** [comment]
The above doesn't compile because I forgot to `>>=` but you should get the point.

With that in mind, the standalone function is more useful than the syntax... e.g.

```
 user  <- getUser(name) >>= liftMonadPlus
```

**Comment by fommil** [comment]
oh, ffs, this is just `.orEmpty` isn't it?

**Comment by fommil** [comment]
the funniest thing is, check who last touched that method.

**Comment by emilypi** [comment]
HA I'll go poke him

**Comment by fommil** [comment]
easier than you'd think... https://github.com/scalaz/scalaz/pull/1596

Although I think there may be room for a similar `.orError` method that takes a `MonadError` and an `E`.

**Comment by fommil** [comment]
```scala
def orError[F[_], A, E](m: Maybe[A])(e: E)(implicit F: MonadError[F, E]): F[A] =
  m.cata(F.point, F.raiseError(e))
```
