### ISSUE TITLE
split MonadError into raise and handle parts

### ISSUE THREAD

**Issue by fommil** [scalaz/scalaz#1657]
I have a usecase in `scalaz-deriving`, where derivation for refined types needs the `raiseError` for a `MonadError[?, String]` but not the `handle` side. https://gitlab.com/fommil/scalaz-deriving/issues/56#note_61076470

Since this puts a requirement on typeclass authors to provide a `MonadError` it is annoying that I'm asking them to write a `handleError` when I never plan to use it.

// @fthomas we don't need things like circe-refined, spray-json-refined, play-refined, config-refined or doobie-refined anymore with this ^^^

**Comment by fommil** [comment]
Now that I can piggy back off EitherT for my most common usecase, I don't really care anymore :stuck_out_tongue:

**Comment by rabbitonweb** [comment]
@fommil what do you mean by "piggy back off EitherT"?
