### ISSUE TITLE
MonadError syntax doesn't work

### ISSUE THREAD

**Issue by fommil** [scalaz/scalaz#1659]
@edmundnoble explained the problem... it's because the implicit is on the class.

Since syntax doesn't work at all, I recommend that such a fix be backported to 7.2 on the basis that nobody is using that code.

**Comment by fommil** [comment]
this doesn't work either...

```
  implicit class MonadErrorOps[F[_], A](private val self: F[A]) {
    def handleError[E](f: E => F[A])(implicit F: MonadError[F, E]): F[A] =
      F.handleError(self)(f)
  }
```

so I suspect it's actually a problem about deriving the monaderror for `String \/ ?`

**Comment by xuwei-k** [comment]
`scalacOptions += "-Ypartial-unification"` ?

**Comment by fommil** [comment]
@xuwei-k oh, you're right... I'm in a project that isn't using partial-unification.

But I think I found a better way to do what I want anyway with EitherT
