### ISSUE TITLE
MonadError.emap

### ISSUE THREAD

**Issue by fommil** [scalaz/scalaz#1660]
I'm not sure how to implement it yet, but it would be very useful to have this function:

```scala
def emap[A, G[_]](fa: F[A])(f: A => G[A])(implicit G: MonadError[G, S]): F[A] = ...
```

probably needs some extra evidence to allow smashing F and G together.

Most decoder typeclasses implement this directly, but I'm pretty sure it can be provided automatically (with a `MonadError`, obvs).

**Comment by fommil** [comment]
btw, if we hard code to disjunction, it's trivial

```scala
  def emap[A](fa: F[A])(f: A => S \/ A): F[A] =
    bind(fa) { a =>
      f(a) match {
        case -\/(err)  => raiseError(err)
        case \/-(succ) => pure(succ)
      }
    }
```

**Comment by fommil** [comment]
closed in #1661 with hardcoded disjunction, because it's super useful

**Comment by fommil** [comment]
hmm, looking at it this way... `bifoldMap` would seem to do what is needed.

**Comment by ritschwumm** [comment]
why not generalize from `F[A] => (A => S \/ A) => F[A]` to `F[A] => (A => S \/ B) => F[B]`?

**Comment by fommil** [comment]
doh
