### ISSUE TITLE
fromIso everywhere

### ISSUE THREAD

**Issue by fommil** [scalaz/scalaz#1662]
In https://github.com/scalaz/scalaz/pull/1661 I introduced a method on MonadError called `fromIso` which allowed deriving a `MonadError` from something isomorphic that has one already.

Most things already have an `IsomorphismThing` trait in `Isomorphism.scala` but very few people know about it, and using it is tedious.

We should add `fromIso` methods onto all typeclass companions that has an isomorphism.

The convention should be:

1. `Iso` parameter is not implicit
2. underlying / delegate instance is implicit

since `Iso` is not technically a typeclass.

**Comment by fommil** [comment]
it would also be good if there was Iso syntax. It would need to consider isos that are either way around and flip the opposite one. So maybe two implicit classes, to avoid overloading.

This would remove the need for `.toList` and `.fromList` style methods.

**Comment by xuwei-k** [comment]
> Iso is not technically a typeclass.

create new typeclass ? https://github.com/xuwei-k/scalaz/commit/8076ed999b4d99dcc0ca30f70562f4450d5260d3

**Comment by fommil** [comment]
I guess that works :smile:

**Comment by fommil** [comment]
I'm increasingly convinced that `fromIso` is how to derive typeclasses of shape `F[_[_]]` such as `Monad`. see https://gitlab.com/fommil/scalaz-deriving/issues/74

The `fromIso` convention is easily supported, but obtaining the `IsoFunctor` for the data type could be difficult unless we encourage them to be implicit or we derive them with a macro (I have one already).

I also think I need a refinement of `Iso` to include string names of the fields, but that's another conversation.

**Comment by xuwei-k** [comment]
https://github.com/scalaz/scalaz/pull/1842
https://github.com/scalaz/scalaz/pull/1847

**Comment by fommil** [comment]
:-D
