### ISSUE TITLE
add a Foldable.{asum, atraverse}

### ISSUE THREAD

**Issue by fommil** [scalaz/scalaz#1672]
https://hackage.haskell.org/package/base-4.11.0.0/docs/Data-Foldable.html

I keep finding myself wanting this, especially atraverse since scala is eager.

Example usecase

```scala
scala> val stream = Stream.continually { println("called") ; "a" }
scala> stream.traverse(_.right[String])
... runs forever
```

but I'd like to do

```scala
scala> stream.atraverse(_.right[String])
res: Either[String, String] = Right(a)
```

**Comment by fommil** [comment]
`asum` looks like `msuml`. We could do with an alias for the haskell name on the syntax and an `atraverse` on `Traverse`.

**Comment by fommil** [comment]
this may just be as simple as

```scala
xs.map(f).foldRight1(_ <+> _)
```

but with the map applied when folding in the fold to account for eager `xs` structures.

**Comment by jbgi** [comment]
@fommil : could it help if we tackle #1663 first?
