### ISSUE TITLE
Partial.apply

### ISSUE THREAD

**Issue by fommil** [scalaz/scalaz#1684]
I often find myself having to interact with a legacy API that is completely deterministic, yet throws an exception on failure. Examples are: parsing numbers, parsing base64. We do this within the scalaz codebase itself.

We can either use `IO` or `Try` to run this code and convert the non-referentially transparent `Throwable` into a more meaningful type, but the ceremony is lengthy.

I propose a new convenience function

```scala
object Partial {
  def apply[A, E](a: => A, err: Throwable => E): E \/ A = ...
}
```

This would avoid us ever having to use `Try` or `try` in our user code, funnelling everything through one place. Of course, IO would still be needed for anything that is not deterministic.

I also propose decommissioning the methods on `object \/` that encourage `Throwable` to leak back into user code. These methods are not referentially transparent.

**Comment by fommil** [comment]
`Exception` is better than `Throwable`. We shouldn't be catching serious things.

**Comment by NeQuissimus** [comment]
Why not add a third function next to `\/.fromTryCatchThrowable` and `\/.fromTryCatchNonFatal`?

https://github.com/scalaz/scalaz/blob/series/7.3.x/core/src/main/scala/scalaz/Either.scala#L399

**Comment by fommil** [comment]
@NeQuissimus good idea. I'd rather deprecate the others and use a shorter name.
