### ISSUE TITLE
a scalaz.TypeClass marker trait

### ISSUE THREAD

**Issue by fommil** [scalaz/scalaz#1695]
if such a trait were to be provided and all typeclasses inherit from it (e.g. via the gentypeclass), tooling could do a much much better job in terms of discoverability and linting. It would help us find a) typeclasses and b) instance types, very easily. We could even have tooling that would add the necessary typeclasses to our functions.

Nothing else should be in the trait. It'd just be a marker.

**Comment by alexknvl** [comment]
Are there any guidelines to decide what is and what isn't a typeclass? For example, is `Is[A, B]` a typeclass?

**Comment by emilypi** [comment]
@alexknvl If we hide the ability for end users to construct their own `TypeClass`es, and have quorum on what constitutes a valid typeclass for Scalaz, I'd be very amenable to this, and I agree - we need to decide what is and is not a "typeclass" for our purposes.

**Comment by TomasMikula** [comment]
I think that whether a type is a typeclass depends on context (how it's used) rather than on what it is.

**Comment by fommil** [comment]
I've heard people say in `#scalaz` that it must be a trait with a single type parameter hole, which excludes things like `IsoFunctor` unless it is pinned to a specific type (this has consequences for how HKT deriving is implemented).

But then again, everybody is happy accepting that `MonadError` is a typeclass when it is pinned to a specific error type.

**Comment by alexknvl** [comment]
I think this is something we should definitely do for S8.
