### ISSUE TITLE
Potentially shortcircuiting foldMaps

### ISSUE THREAD

**Issue by TomasMikula** [scalaz/scalaz#1706]
Implement `foldMap` that supports early termination whenever the target `Monoid` does, for sequential data structures:

 - [ ] `List`
 - [ ] `IList`
 - [ ] `NonEmptyList`
 - [ ] `EphemeralStream`

This is analogous to what's already been done for `Stream` in https://github.com/scalaz/scalaz/commit/1fbc0cb10e555667e69e1360b8d4b1ad1d3cfb5e#diff-bf0e1bb9c3e7f9beb88c492281f38ed7

**Comment by malancas** [comment]
Hi, I'm a new contributor. I've started an implementation and would like to pick this issue up if it's okay. Thanks.
