### ISSUE TITLE
fix the invariant parameterless case class encoding

### ISSUE THREAD

**Issue by fommil** [scalaz/scalaz#1712]
in 7.3 we used an encoding that was recently discovered to be flawed https://github.com/scala/bug/issues/10822

But @hrhino fixed it in https://github.com/scalaz/ioeffect/pull/9

We should go back through 7.3 and fix our encoding.

**Comment by alexknvl** [comment]
I asked Tony on #scalaz

**Comment by hrhino** [comment]
Tony was kind enough to add me (thanks!)

**Comment by hrhino** [comment]
So... I took a look, and scalaz 7 *really* doesn't like exposing ADT branches.

The requirements are that:
- a `sealed` `abstract class`/`trait`...
- with an invariant type parameter...
- which has a case in which that parameter is `Nothing`...
- which is encoded with the zero-allocation casting trick...
- and is used in a match scrutinee where the type parameter is a concrete type.

We don't actually many of those at all. (I think `Maybe` is the only one).

Semi-relatedly: I think Scalaz 8 should expose more ADTs in a matchable way. Having a `fold` that takes a function for each case is less efficient and doesn't gain us anything in "encapsulation" (which I argue is a dubious virtue for functional programming, anyways). Obviously there will be exceptions, but those exceptions would be in cases where we wouldn't expose a raw catamorphism.

**Comment by fommil** [comment]
@hrhino there are a couple, search for `abstract case` (6 uses) but

> scalaz 7 really doesn't like exposing ADT branches

this.

In my book I've outright lied about the implementation of many data structures because it's so hard to understand what's going on with the OOP style encoding.

I think there is general consensus that using ADTs (even if they are kept private, such as `ISet` would need) is the preferred approach.
