### ISSUE TITLE
Make Traversables short-circuiting _and_ stack-safe

### ISSUE THREAD

**Issue by TomasMikula** [scalaz/scalaz#1716]
Traversals can be made both stack-safe _and_ short-circuiting, provided that the target `Applicative` implements short-circuiting. The key is to use the applicative's `unfoldrOpt` method for the implementation of `traverse`.

This has been done for `List` in https://github.com/scalaz/scalaz/commit/79c5413274b64e144049d4279c3a69ea17087e5c.

We should implement this at least for sequential data structures with natural left-to-right traversal:

 - [ ] `IList`
 - [ ] `NonEmptyList`
 - [ ] `Stream`
 - [ ] `EphemeralStream`

**Comment by malancas** [comment]
Hello, I'll pick this issue up.

**Comment by TomasMikula** [comment]
Awesome! It's also fine to do them one at a time.

**Comment by malancas** [comment]
Hey, I plan to have a PR up for this in the next day or so.
