### ISSUE TITLE
continuing native support?

### ISSUE THREAD

**Issue by fommil** [scalaz/scalaz#1735]
Given that graal is now a thing... should we drop scala-native in 7.3+ ?

I vote yes. Cross building is a massive pain.

**Comment by emilypi** [comment]
I honestly don't know of anyone using it. If they want it, they should speak up and raise an issue later. Until that day, no thanks.

**Comment by OlegYch** [comment]
@fommil sounds too early

**Comment by xuwei-k** [comment]
some libraries depends on scalaz-core for scala-native (e.g. argonaut, monocle)

**Comment by fommil** [comment]
ok, maybe we keep in 7.3 but drop in scalaz8?

**Comment by emilypi** [comment]
That sounds like a good middle ground @fommil

**Comment by Milyardo** [comment]
I've found having scalaz in scala-native pretty useful, but I'm not using it for anything worthwhile. That said, I see the whole scala-native vs graal thing as a non-sequiter.
