### ISSUE TITLE
ContT should be standalone

### ISSUE THREAD

**Issue by fommil** [scalaz/scalaz#1737]
ContT is implemented in terms of IndexedContT (adding another type parameter and Contravariant) which is implemented in terms of IndexedContsT (adding a Comonad).

The indexing layer of abstraction does not have a Monad and I am not sure either generalisation is worth it. They complicate the code of something that is already very difficult to understand, and introduce unnecessary object allocations.

I propose that `ContT` be a standalone transformer, not an alias, ~~which should make it easier to become stack safe~~ (Edmundo says this is not possible on the JVM)

I point at Haskell as prior art in not abstracting beyond `(A => F[B]) => F[B]`.

**Comment by TomasMikula** [comment]
I don't know what the use case for the extra comonad is. +1 for removing
that.

OTOH, indexed signatures typically preclude some incorrect implementations,
so I would keep the implementation indexed. I believe it doesn't introduce
any additional allocations.
