### ISSUE TITLE
String interpolator for Debug

### ISSUE THREAD

**Issue by NeQuissimus** [scalaz/scalaz#1749]
In order to avoid rogue `toString` calls, we should provide a string interpolator similar to #1496 that requires `Debug` instances for everything used.

Also, maybe rename the interpolator to `z"Hello ${World}"`

**Comment by barambani** [comment]
I can have a look a this if it's ok

**Comment by NeQuissimus** [comment]
My bad, I forgot to close this issue. I already did the work in #1750
