### ISSUE TITLE
Change SafeApp to expect an error free main function

### ISSUE THREAD

**Issue by jdegoes** [scalaz/scalaz#1759]
`SafeApp` lets the user choose the type of error of the main function, which is a holdover from pre-bifunctor days.

It makes more sense to force the main fiber to handle all its errors. 

So this:

```scala
def run(args: List[String]): IO[Error, Unit]
```

can change to this:

```
def run(args: List[String]): IO[Void, Unit]
```

and the `Error` type member of `SafeApp` can be deleted, with documentation updated to match.

**Comment by hrhino** [comment]
#1774
