### ISSUE TITLE
Change SafeApp to support MainResult

### ISSUE THREAD

**Issue by jdegoes** [scalaz/scalaz#1760]
A `MainResult` type can be defined that determines the behavior of the runtime system with respect to threads.

```scala
sealed trait MainResult
object MainResult {
  final case class Wait(code: Int) extends MainResult
  final case class Immediate(code: Int) extends MainResult
  final object Daemon extends MainResult
}
```

The design is up for discussion but the main feature should be the ability to exit without waiting for threads to finish, exit waiting for threads to finish, or not exit regardless of threads.

**Comment by hrhino** [comment]
#1774

(just trying to keep the issue tracker clean, sorry John if this isn't actually done somehow)

**Comment by jdegoes** [comment]
@hrhino Thanks!
