### ISSUE TITLE
Improve Async in Scalaz 8 IO

### ISSUE THREAD

**Issue by jdegoes** [scalaz/scalaz#1786]
Async can benefit from 2 improvements:

 * Delete `Async.Later`, and implement `Async.later` by passing a no-op canceler to `Async.MaybeLater`. This will simplify the ADT and handling the different cases in the code.
 * Add a new constructor, `Async.MaybeLaterIO`, whose canceler has signature `Throwable => IO[Void, Unit]`. This represents a pure canceler. Add a `Async.maybeLaterIO` helper function, and support the new canceler inside `RTS` by submitting the run of the canceller to the thread pool.

After these two improvements, the ADT for `Async` will be less redundant, and will also have gained the ability to represent pure cancellations, which is a necessary property for "closure".

See `asyncIO` for similar idea applied to the `async` constructor.

**Comment by barambani** [comment]
I would give this a try if that's ok

**Comment by jdegoes** [comment]
@barambani That would be awesome! I am here to help with anything at all. 💪
