### ISSUE TITLE
custom IO Cord writer

### ISSUE THREAD

**Issue by fommil** [scalaz/scalaz#1797]
It is often the case, when writing applications, that we need to write large strings to network sockets or files. However, constructing the String in its entirety is a performance problem.

We should have a function in `effect` that can access the `Cord` internal structure and write it out using NIO in 7.3. Depends on #1796

**Comment by edmundnoble** [comment]
Not a bad idea; what do you think about just exposing a
```scala
def traverseCord_[F[_]: Applicative](f: String => F[Unit])(cord: Cord): F[Unit]`
```

**Comment by emilypi** [comment]
Subissue: please prefix all `Cord` methods with `dank`. Thank you.

**Comment by fommil** [comment]
I'm not sure it's possible to abstract it, the string builder is a concrete class on the JDK :man_shrugging: 

I'd prefer to have a way of doing this with NIO to avoid blocking the thread on the output stream.

**Comment by edmundnoble** [comment]
It is possible to abstract this in a stack-safe way. Just replace the stringbuilder calls with calls to `f`.

**Comment by fommil** [comment]
`f` would need to be defined as a side effect `f: String => Unit` to be equivalent to the current code.
