### ISSUE TITLE
Adopt modern file naming convention

### ISSUE THREAD

**Issue by jdegoes** [scalaz/scalaz#1816]
The current naming convention for files dates from the Java era, when every class was required to have its own separate file. This leads to a proliferation of files and does not actually make it easier for users to find what they're looking for, since it's not always obvious when a method is in syntax, data type, functions, or instances.

I propose we move from this convention:

```
These.scala
TheseFunctions.scala
TheseInstances.scala
TheseSyntax.scala
```

To this convention:

```
these.scala
```

Where `these.scala` would contain all classes currently split across 4 files.

This change will decrease the visual noise and move away from conventions that were born in Java of necessity rather than conscious choice.

**Comment by TomasMikula** [comment]
👍

**Comment by TomasMikula** [comment]
See also #1640.

**Comment by jdegoes** [comment]
@TomasMikula Awesome. I'll mark #1640 as closed because it's subsumed by this one.

**Comment by hrhino** [comment]
I nearly did this as part of #1814, so _big_ 👍 from me.

**Comment by barambani** [comment]
If no one is looking into this I could do it

**Comment by jdegoes** [comment]
@barambani 👍

**Comment by barambani** [comment]
I have almost ready a pr for this. I have a question, should the case of the file name's first letter be consistent ?

**Comment by jdegoes** [comment]
Let's make them all lower case. It's too hard to push shift and there's no reason to do so.
