### ISSUE TITLE
scalac options

### ISSUE THREAD

**Issue by NeQuissimus** [scalaz/scalaz#1821]
We should review the subset of scalac options we want to have in Scalaz 8.

https://tpolecat.github.io/2017/04/25/scalac-flags.html is a good starting point.

We will want `"-Yno-imports"`.

Personally, I vote for using all the ones mentioned in the article (sans the Typelevel Scala stuff).

**Comment by jbgi** [comment]
We can use the lint options of the 7.3 branch + no-import. I used the tpolecat guide above when I added them.

**Comment by NeQuissimus** [comment]
Turns out the options other than "no-imports" are already there xD
