### ISSUE TITLE
Provide a sample benchmark for IO/RTS vs Future/ExecutionContext

### ISSUE THREAD

**Issue by JohnSColeman** [scalaz/scalaz#1854]
I guess this isn' quite the right place of this but I'd like to see a benchmark of Futures vs IO for handling blocking code, e.g.:

```scala
import java.util.concurrent.atomic.AtomicInteger
import scalaz.ioeffect.{ExitResult, IO, RTS}
import scala.concurrent.{ExecutionContext, Future}
import scala.util.Random
import scala.concurrent.forkjoin.ForkJoinPool

object FutureVsIOBenchmark extends App with RTS {

  val atomicInt = new AtomicInteger(1)
  val atomicWaitInt = new AtomicInteger()
  val count = 50000
  val startTime = System.currentTimeMillis()
  val mutex = new Object()

  def task = {
    val wait = Random.nextInt(100) + 50
    atomicWaitInt.addAndGet(wait)
    Thread.sleep(wait)
    val i = atomicInt.getAndIncrement()
    if (i == count) {
      var runtime = (System.currentTimeMillis() - startTime).toFloat
      println("runtime = " + runtime)
      println("wait time/runtime = " + (atomicWaitInt.get() / runtime))
      mutex.synchronized {
        mutex.notify()
      }
    }
  }

  /** Task with Future */
  implicit val ec = ExecutionContext.fromExecutor(new ForkJoinPool(2000))

  for (i <- 1 to count) {
    Future(task) // 1171 1180 1112 835 1202 1166 1160 1225 1266 1288 [1160]
  }

  mutex.synchronized {
    mutex.wait()
  }

  /** Task with IO */
  // TODO implement IO/RTS version of above??

}
```

Is there a discussion board for this kind of thing? Also some practical samples to help people transition from Future think to IO this would hugely help with adoptable.

**Comment by jdegoes** [comment]
There are lots of benchmarks of `IO` vs `Future` in the `benchmarks` package. The problem with measuring blocking code is that at that point, you're measuring the performance of blocking, not `Future` / `IO`. The ideal benchmark measures the overhead of the solution and not the specifics of the sample problem being benchmarked.

**Comment by JohnSColeman** [comment]
Hi,

Thanks, understood, blocking would just be JVM vs JVM so the same performance. I had wondered if there would be any difference in efficiencies perhaps because of less resource overhead with fibres.

How would one use IO with legacy libraries that return Futures and expect Futures? Like IO is the filling in a sandwich. Could IO based code defer until the Future completed somehow? We use a lot of Futures based library code but would like the cleanness of using IO in our code.

John

**Comment by jdegoes** [comment]
We do need a project to go `IO => Future`, `Future => IO`. Possibly a subproject in `scalaz-zio`.

**Comment by ktonga** [comment]
Why subproject? It's just two functions and does not require any extra dependency. It could be just an object plus syntax provided by zio in it's own file.

**Comment by jdegoes** [comment]
Impure and unlawful code should. It contaminate the core zio project. But we could have a zio-compat directory that generates a different JAR.

**Comment by JohnSColeman** [comment]
If someone would care to throw up an example (gist?) of these 2 functions, that would be hugely appreciated.

**Comment by jdegoes** [comment]
@JohnSColeman These are being implemented in [zio](http://github.com/scalaz/scalaz-zio) in a new `interop` module, so you'll be able to use them from there without writing any code.
