### ISSUE TITLE
Contravariant should be a subclass of InvariantFunctor

### ISSUE THREAD

**Issue by hrhino** [scalaz/scalaz#1859]
`Functor` already is. Just do the same thing.

**Comment by hrhino** [comment]
As pointed out on gitter: you'll need to override `imap` in `PhantomClass` due to diamond inheritance.

**Comment by nicflores** [comment]
@hrhino, I'd like to take on this issue, can you assign it to me?

**Comment by hrhino** [comment]
I think @earldouglas has been taking a stab at it in #1860.

**Comment by nicflores** [comment]
@hrhino, no worries. I'll grab something else.

**Comment by hrhino** [comment]
#1860
