### ISSUE TITLE
applyN in terms of ap or apply2?

### ISSUE THREAD

**Issue by fommil** [scalaz/scalaz#1903]
@TomasMikula in https://github.com/scalaz/scalaz/pull/1474 you change applyN to use apN for optimisation reasons, but I am not sure I agree with the rationale.

In scalaz-deriving, the primitive is `apply2`, not `ap`, as it is more natural to use. Likewise, in `IO` the primitive for parallelisation of effects (in the `Applicative @@ Parallel` instance) is also `apply2`. By making `applyN` go via `ap`, we incur extra object allocations that we might not have had in 7.2.

I was wondering if we could do the same thing with `applyN` that we do with `divideN`, where we split 4 into 2+2, and so on. Which reduces the depth of the nested combinators.

Do you have any evidence that going via ap is faster?

**Comment by TomasMikula** [comment]
These are at least 3 worthwhile questions:

 1. **Should we optimize the default method implementations as if `apply2` is the primitive?**
  I think that would be weird given our formulation of `Apply` with `ap` as the main primitive. So the question really is whether to change the definition of `Apply`.

 2. **Was #1474 actually an improvement?**
    Let's look at the definition of, say, `apply8` before and after #1474.
    
    **Before:**
    ```scala
    def apply8[A, B, C, D, E, FF, G, H, R](fa: => F[A], fb: => F[B], fc: => F[C], fd: => F[D], fe: => F[E], ff: => F[FF], fg: => F[G], fh: => F[H])(f: (A, B, C, D, E, FF, G, H) => R): F[R] =
      apply2(tuple4(fa, fb, fc, fd), tuple4(fe, ff, fg, fh))((t, t2) => f(t._1, t._2, t._3, t._4, t2._1, t2._2, t2._3, t2._4))
    ```
    which after inlining `tuple4` becomes
    ```scala
      apply2(apply4(fa, fb, fc, fd)((_,_,_,_)), apply4(fe, ff, fg, fh)((_,_,_,_)))((t, t2) => f(t._1, t._2, t._3, t._4, t2._1, t2._2, t2._3, t2._4))
    ```
    which after inlining `apply4` becomes
    ```scala
      apply2(apply2(tuple2(fa, fb), tuple2(fc, fd))((t, d) => (t._1,t._2,d._1,d._2)), apply2(tuple2(fe, ff), tuple2(fg, fh))((t, d) => (t._1,t._2,d._1,d._2)))((t, t2) => f(t._1, t._2, t._3, t._4, t2._1, t2._2, t2._3, t2._4))
    ```
    which after inlining `tuple2` becomes
    ```scala
      apply2(apply2(apply2(fa, fb)((_,_)), apply2(fc, fd)((_,_)))((t, d) => (t._1,t._2,d._1,d._2)), apply2(apply2(fe, ff)((_,_)), apply2(fg, fh)((_,_)))((t, d) => (t._1,t._2,d._1,d._2)))((t, t2) => f(t._1, t._2, t._3, t._4, t2._1, t2._2, t2._3, t2._4))
    ```
    If I'm counting correctly (I'm probably not 😃), this creates
     - 6 (in general, n-2) additional thunks for by-name evaluation,
     - 6 (in general, n-2) intermediate tuples,
     - 7 (in general, n-1) anonymous functions.

    **After:**
    ```scala
      ap(fh)(ap(fg)(ap(ff)(ap(fe)(ap(fd)(ap(fc)(ap(fb)(map(fa)(f.curried))))))))
    ```
    I see
     - 7 (in general, n-1) additional thunks,
     - 8 (in general, n) function values (`f.curried`, before reaching the final result, will create another 7 intermediate functions).

    This analysis suggests that we went from 3n-5 to 2n-1 allocations.
    Assuming that `ap` and `apply2` are equally expensive, then #1474 was an improvement.

    But wait! 6 of those 7 (n-2 of those n-1) additional anonymous functions in the original implementation are not closures (do not capture variables from the outer scope). They are just polymorphic functions. If Scala had polymorphic function values, we could allocate them once and for all. This will probably be possible in dotty. That would improve my analysis of the original implementation to 2n-3, i.e. slightly better.

 3. **Binary splits reduce the depth of the expression. Should we prefer them for this reason?**
    Do we actually care about the depth?

**Comment by fommil** [comment]
good answer! Actually I vote for apply2 to be the primitive.

With regards to depth, yes I think we do care, because it makes it easier for downstream to optimise it because you can just optimise the next prime factor to improve almost all arities above you, like divide.

That said, I plan to override all the arities in terms of the generic impl once scalaz-deriving is feature complete.

**Comment by TomasMikula** [comment]
I agree that `apply2` seems more natural than `ap`, especially because `ap` orders the effects of its arguments in reverse (or in other words, it takes its arguments in reverse order), which is very confusing (but we do it to better work with Scala's type inference).

> With regards to depth, yes I think we do care, because it makes it easier for downstream to optimise it: we can just optimise the next prime factor to improve almost all arities above, like divide.

That's a compelling argument.

**Comment by fommil** [comment]
We could make the same argument in `Alt` but I chose to make `def alt` the primitive instead of `alt2` because of the precedent in `Apply`. If we change `Apply` we should also change `Alt`!

**Comment by fommil** [comment]
`Alt` has the same argument... I choose to use `def alt` as the primitive rather than `altly2` (maybe we should just call these things `def alt2` but I was following the precedent  set in `Apply`)

**Comment by fommil** [comment]
btw, we are missing a composition law in Apply similar to the Divide composition law. That would be very useful for scalaz-deriving.

**Comment by TomasMikula** [comment]
Namely?
