### ISSUE TITLE
should contramap be derived by divide2?

### ISSUE THREAD

**Issue by fommil** [scalaz/scalaz#1907]
@puffnfresh @ekmett your thoughts on this would be appreciated

In https://github.com/scalaz/scalaz/issues/1481#issuecomment-335437707 Brian suggested a way to derive `liftD` in terms of divide and conquer

```scala
def liftD[F[_]: Divisible, A, B](fa: F[A], f: B => A): F[B] =
  Divisible[F].divide2(Divisible[F].conquer[Unit], fa)(c => ((), f(c)))
```

I equated `liftD` with `contramap`, as per https://github.com/scalaz/scalaz/issues/1481#issuecomment-335600814, and converted `contramap` to a derived combinator in https://github.com/scalaz/scalaz/pull/1565 There is precedent since `.map` is derived by `ap` (equivalent to `apply2`, the analogue of `divide2`).

However, this can lead to some very counter-intuitive results.

Consider what happens for the following example ADT and an encoder algebra

This is our "wire format"

```scala
@deriving(Equal, Show)
sealed abstract class Packed
final case class Rational(long: Long)               extends Packed
final case class Collection(entries: IList[Packed]) extends Packed
```

and this is our encoder algebra (not necessarily a typeclass)

```scala
trait Pack[A] {
  def encode(a: A): Packed
}
object Pack {
  implicit val divisible: Divisible[Pack] = new Divisible[Pack] {
    def divide[A, B, C](fa: Pack[A], fb: Pack[B])(f: C => (A, B)): Pack[C] = { c =>
      val (a, b) = f(c)
      (fa.encode(a), fb.encode(b)) match {
        case (Collection(as), Collection(bs)) => Collection(as ::: bs)
        case (Collection(as), bs) => Collection(as :+ bs)
        case (as, Collection(bs)) => Collection(as +: bs)
        case (as, bs) => Collection(IList(as, bs))
      }
    }

    def conquer[A]: Pack[A] = _ => Collection(IList.empty)
  }

  implicit val long: Pack[Long]     = i => Rational(i)
  implicit val boolean: Pack[Boolean] = long.contramap(b => if (b) 1 else 0)
}
```

The strange thing comes from the fact that `boolean` formats always come wrapped in a `Collection` whereas one might have intuitively thought that `Pack[Boolean]` would produce `Rational` values.

Is this example just fundamentally broken? Is the implementation of `divide2` wrong? Or is it perhaps the case that `contramap` should not be derived.

If the example is broken (and I believe it is), it is strong evidence that encoders can't have lawful typeclass of Divisible (and Decidable), which is quite significant. I already knew this was the case if the "label" metadata is taken into account (e.g. such as JSON using field names from products), but I was careful to construct an example that did not make use of such information. The `Collection` unlayering probably breaks all kinds of laws when encoding nested products.

**Comment by fommil** [comment]
OK, I've convinced myself that encoders can't have a `Divide` instance, because they simply don't compose. My attempts to workaround this (above) by trying to account for the collection on both sides is a hack. In fact the obvious implementation would be

```scala
 def divide[A, B, C](fa: Pack[A], fb: Pack[B])(f: C => (A, B)): Pack[C] = { c =>
      val (a, b) = f(c)
      Collection(IList(fa.encode(a), fb.encode(b)))
    }
```

and this just makes it obvious that `divide2(divide2(a, b), c) != divide2(a, divide2(b, c))`.

**Comment by edmundnoble** [comment]
This makes sense to me. However, if you *always* emitted inside of `Collection`, you could have a lawful `Divisible`.
