### ISSUE TITLE
+++ for all Applicatives

### ISSUE THREAD

**Issue by JasnaMRB** [scalaz/scalaz#1984]
`Validation` has an implementation for +++ but it would be nice to have for other applicative functors.

**Comment by gaelrenoux** [comment]
In Validation:
```scala
def +++(x: => Validation[E, A])(implicit M1: Semigroup[A], M2: Semigroup[E]): Validation[E, A]
```

Add this and its default implementation to the Applicative typeclass:
```scala
def appendM[A: Semigroup](x:  => F[A], y: => F[A]): F[A]
```

Add apply syntax to the ApplySyntax with the +++ notation.
