### ISSUE TITLE
Add EitherT.fromOption

### ISSUE THREAD

**Issue by allantl** [scalaz/scalaz#2002]
I noticed that `EitherT` doesn't have this currently.
I'd like to help contribute.

WDYT?

**Comment by hrhino** [comment]
A pull request would be the best way to suggest this 😉. It sounds useful.

**Comment by jozi-k** [comment]
You might consider closing this issue.

**Comment by hrhino** [comment]
nice catch; consider it considered! apparently github doesn't understand "addresses".
