### ISSUE TITLE
Add Day convolution

### ISSUE THREAD

**Issue by lemastero** [scalaz/scalaz#2021]
Currently there is no Day convolution type class in Scalaz. There are implementations in Haskell: http://hackage.haskell.org/package/kan-extensions/docs/Data-Functor-Day.html and Purescript: https://github.com/paf31/purescript-day

Here is a proposition: https://github.com/scalaz/scalaz/pull/2020

**Comment by emilypi** [comment]
It looks like you addressed it thoroughly and correctly - thanks for the submission, @lemastero.
