### ISSUE TITLE
Type parameters order in `TracedT`

### ISSUE THREAD

**Issue by regiskuckaertz** [scalaz/scalaz#2025]
Hi 👋 I noticed a couple of examples where the functor is in head position in the type parameter list of some types:
```scala
TracedT[W[_], A, B]
IndexedStoreT[F[_], +I, A, B]
PIndexedStateT[F[_], -S1, S2, A]
PStateT[F[_], S, A]
```
compare with
```scala
WriterT[W, F[_], A]
IndexedStateT[-S1, S2, F[_], A]
```
Is it deliberate? If not, let me know and I can submit a PR.

**Comment by xuwei-k** [comment]
>  I think it’s just a matter of preference of the author.

No, see https://github.com/scalaz/scalaz/pull/1800 and https://github.com/scalaz/scalaz/pull/1838

**Comment by regiskuckaertz** [comment]
Thanks both, I take it that the following changes would be recommended then:

Before|After
-------|----
`TracedT[W[_], A, B]`|`TracedT[T, W[_], B]`
`IndexedStoreT[F[_], +I, A, B]`|`IndexedStoreT[+S1, S2, F[_], B]`
`PIndexedStateT[F[_], -S1, S2, A]`|`PIndexedStateT[-S1, S2, F[_], A]`
`PStateT[F[_], S, A]`|`PStateT[S, F[_], A]`
