### ISSUE TITLE
Scala 2.13 regression in EitherT instances (using 7.2.27)

### ISSUE THREAD

**Issue by oxbowlakes** [scalaz/scalaz#2069]
Here's scala 2.12.8:

    Welcome to Scala 2.12.8 (OpenJDK 64-Bit Server VM, Java 1.8.0_181).
    Type in expressions for evaluation. Or try :help.

    scala> import scalaz.{EitherT, Functor, effect}, effect.IO
    import scalaz.{EitherT, Functor, effect}
    import effect.IO

    scala> type L[A] = EitherT[IO, Exception, A]
    defined type alias L

    scala> Functor[L]
    res0: scalaz.Functor[L] = scalaz.EitherTInstances2$$anon$10@629a9f26

Here is 2.13.0 (still scalaz 7.2.27)

    Welcome to Scala 2.13.0 (OpenJDK 64-Bit Server VM, Java 1.8.0_181).
    Type in expressions for evaluation. Or try :help.

    scala> import scalaz.{EitherT, Functor, effect}, effect.IO
    import scalaz.{EitherT, Functor, effect}
    import effect.IO

    scala> type L[A] = EitherT[IO, Exception, A]
    defined type alias L

    scala> Functor[L]
                  ^
           error: ambiguous implicit values:
            both method eitherTMonadError in class EitherTInstances3 of type [F[_], E](implicit F0: scalaz.Monad[F])scalaz.MonadError[[γ$3$]scalaz.EitherT[F,E,γ$3$],E]
            and method eitherTFunctor in class EitherTInstances2 of type [F[_], L](implicit F0: scalaz.Functor[F])scalaz.Functor[[γ$4$]scalaz.EitherT[F,L,γ$4$]]
            match expected type scalaz.Functor[L]

**Comment by xuwei-k** [comment]
Thanks for the report!

**Comment by oxbowlakes** [comment]
I think that the scala peeps are going to consider that this regression is a fix. Consider the following code:
```
package object foo {
  import scala.language.higherKinds
  class Functor[X[_]]
  trait Monad[F[_]] extends Functor[F]

  class OptionT[M[_]]
  trait OptionTInstances2 {
    implicit def optionTMonad[M[_]]: Monad[OptionT] = ???
  }

  trait OptionTInstances1 extends OptionTInstances2 {
    implicit def optionTFunctor[M[_]]: Functor[OptionT] = ???
  }

  object OptionT extends OptionTInstances1

  object Main extends App {
    implicitly[Functor[OptionT]]
  }
}
```
This fails to compile on 2.12.8. However, if we give `OptionT` a second type parameter:
```
package object foo {
  import scala.language.higherKinds
  class Functor[X[_]]
  trait Monad[F[_]] extends Functor[F]

  class OptionT[M[_], A]
  trait OptionTInstances2 {
    implicit def optionTMonad[M[_]]: Monad[({ type l[a] = OptionT[M, a] })#l] = ???
  }

  trait OptionTInstances1 extends OptionTInstances2 {
    implicit def optionTFunctor[M[_]]: Functor[({ type l[a] = OptionT[M, a] })#l] = ???
  }

  object OptionT extends OptionTInstances1

  object Main extends App {
    implicitly[Functor[({type l[a] = OptionT[Option, a]})#l]]
  }
}
```
The code compiles in scala 2.12.8. It seems like it should not. And it does not compile in scala 2.13.0. Given this regression (ahem, _fix_) to `scalaz`, I'm not sure what the fix/workaround is in scalaz

**Comment by xuwei-k** [comment]
- https://github.com/scala/bug/issues/11596
- https://github.com/scala/bug/issues/11068
- https://github.com/scalaz/scalaz/commit/2fdd887f536e17d59b586b93bf8639e5b84eccd9

**Comment by xuwei-k** [comment]
7.2.28 released

**Comment by tonymorris** [comment]
The correct thing to do is not use inheritance.

`trait [Monad[F[_]] { def functor: Functor[F[_]] = ???; def fmap[A, B] = ??? }`

c.f. the original Scalaz 7.

**Comment by joroKr21** [comment]
> The correct thing to do is not use inheritance.

Then you would need to define conversions `Monad => Applicative` and `Applicative => Functor` and prioritize them as well, but I guess that's what Scalaz 8 will do.

**Comment by tonymorris** [comment]
* `Monad => Bind => Functor`
* `Bind => Apply => Functor`
* `Comonad => Cobind => Functor`
* *etc etc*

There would be no need to prioritise implicit selection.

**Comment by joroKr21** [comment]
There is, if you can get `Functor` via different paths (which you can) we have to prioritize those paths because no coherence guarantees.
