### ISSUE TITLE
Apply instance/syntax for Function1

### ISSUE THREAD

**Issue by sarkologist** [scalaz/scalaz#2097]
I upgraded from 7.2.27 to 7.3.1 and the following stopped compiling:
```
import scalaz.syntax.applicative._
import scalaz.std.function._

(f |@| g){ _ ::: _ }
```
where `f,g : A => List[B]`

But the following does compile:
```
import scalaz.Apply
import scalaz.std.function._

Apply[({ type X[T] = Function1[A, T] })#X]
   .lift2[List[B], List[B], List[B]] { _ ::: _ }
   .apply(f, g)
```

**Comment by joroKr21** [comment]
Which version of Scala? Do you have `-Ypartial-unification` enabled?

**Comment by sarkologist** [comment]
`-Ypartial-unification` makes it work! I am using scala `2.12.7`. Thanks.
