### ISSUE TITLE
Trouble with Apply on Kleisli

### ISSUE THREAD

**Issue by justinhj** [scalaz/scalaz#2160]
Having trouble getting ApplyOps to work with a Kleisli[Either as shown below. 

```
import scalaz._
import std.AllFunctions._
import std.AllInstances._

     val a1: Kleisli[Either[String,?],Env[Int],Int] = Kleisli.kleisli(_ => Right(10))
      val a2: Kleisli[Either[String,?],Env[Int],Int => Int] = Kleisli.kleisli(_ => Right((a: Int) => a + 1))

      val a1Inc = a1.ap(a2) // ERROR Value ap is not a member of Kleisli

      val a1Inc2 = Kleisli.kleisliApplicative[Either[String,?],Env[Int]].ap(a1)(a2) // OK 
```

Not sure if it's just the imports or if there is some issue preventing the type inference to allow ApplyOps to do its work and bring the ap function into scope.

**Comment by tonymorris** [comment]
Hey mate,

When having problems with implicit, try passing the implicit 
*explicitly* to give you better error messages and work out why it's not 
working (implicitly).

PS: an improvement is remove all the subclassing in the type-class 
hierarchy.

**Comment by joroKr21** [comment]
That sounds like a partial unification problem - if you're using Scala 2.12 you need the `-Ypartial-unification` compiler flag.

**Comment by justinhj** [comment]
> Hey mate, When having problems with implicit, try passing the implicit *explicitly* to give you better error messages and work out why it's not working (implicitly). PS: an improvement is remove all the subclassing in the type-class hierarchy.

Yeah good idea, cheers.  So I can summon an Apply manually and it works fine...

```

// final class ApplyOps[F[_],A] private[syntax](val self: F[A])(implicit val F: Apply[F])

    implicit val explicitApply = Apply[Kleisli[Either[String,?],Env[Int],?]]
     explicitApply.ap(a1)(a2) // OK

      val a1Inc = a1.ap(a2) // :( Value ap is not a member of Kleisli

```

But it's still not picking it up so I can't use ap on a1 in the next line.

> PS: an improvement is remove all the subclassing in the type-class
hierarchy.

👍

**Comment by justinhj** [comment]
> That sounds like a partial unification problem - if you're using Scala 2.12 you need the `-Ypartial-unification` compiler flag.

Thanks but I'm using 2.13
