### ISSUE TITLE
scalaz.org down

### ISSUE THREAD

**Issue by hanxue** [scalaz/scalaz#701]
Sorry if this is inappropriate, I could not find the scalaz.org Github pages repository. Navigating to http://scalaz.org results in

![image](https://cloud.githubusercontent.com/assets/760008/2813551/4a965dd0-ce8d-11e3-81a1-be0184a03cb6.png)

**Comment by retronym** [comment]
I currently own this domain, but I'm no longer contributing to the project. It would make sense for me to transfer ownership of the domain to someone who is active within Scalaz.

@tonymorris @jedws @xuwei-k @S11001001 please discuss.

**Comment by S11001001** [comment]
@retronym I think @tonymorris or @xuwei-k would be ideal choices of steward as founder and release manager respectively, but am happy to take it over if no one else wants to deal with it.

**Comment by tonymorris** [comment]
I think using scalaz.org would be ideal.

**Comment by S11001001** [comment]
Currently redirects to github.
