### ISSUE TITLE
Aliasing `Disjunction` to `\/`

### ISSUE THREAD

**Issue by adelbertc** [scalaz/scalaz#804]
We have a `Disjunction` type alias for `\/`, but:
- No corresponding `val Disjunction = \/`
- No aliases for `-\/` and `\/-` - perhaps `DLeft` and `DRight`?
- Should rename Either.scala to Disjunction.scala
- Should do similar renamings for `EitherT` and `scalaz.syntax.either` and co.

**Comment by hrhino** [comment]
#805
