### ISSUE TITLE
Co[F, G]#Product[A] instead of Coproduct[F, G, A]

### ISSUE THREAD

**Issue by EECOLOR** [scalaz/scalaz#827]
I am working with Free monads using the concepts presented by Rúnar. I keep bumping into problems with implicit resolution of things that use `Coproduct`. This is caused by the fact that `Coproduct` has 3 type parameters and things like `~>` accept a single type parameter.

One of the examples is the following.

``` scala
type Co[F[_], G[_]] = {
  type Product[A] = Coproduct[F, G, A]
}

implicit class NaturalTransformationEnhancements[F[_], O[_]](fToO: F ~> O) {
  def or[G[_]](gToO: G ~> O) = {
    new (Co[G, F]#Product ~> O) {
      def apply[A](c: Co[G, F]#Product[A]) = c.run match {
        case -\/(g) => gToO(g)
        case \/-(f) => fToO(f)
      }
    }
  }
}
```

The above implicit enhancement will work for

``` scala
trait X[A]
trait Y[A]

val xToR:X ~> R = ???
val yToR:Y ~> R = ???

xToR or yToR
```

It will however fail for

```
trait Z[A]

val zToR: Z ~> R = ???

xToR or yToR or zToR
```

To make it work I would need to do

``` scala
type XY[A] = Coproduct[X, Y, A]

val xyToR: XY ~> R = xToR or yToR

xyToR or zToR
```

These types of problems can be solved by defining `Coproduct` like this:

``` scala
class Co[F[_], G[_]] {
  case class Product[A](run: F[A] \/ G[A])
}
object Co {
  def apply[F[_], G[_]] = new Co[F, G]
}
type Coproduct[F[_], G[_], A] = Co[F, G]#Product[A]
object Coproduct {
  def apply[F[_], G[_], A](run: F[A] \/ G[A]) = Co[F, G].Product(run)
}
```

**Comment by S11001001** [comment]
The end of SI-2712 will actually make the existing version easier to infer; given that they've also made expansion of type synonyms much more eager in 2.11 (and *that* was pretty annoying in places), it is almost certainly safer to stick with the current encoding at this point.
