### ISSUE TITLE
Tag.subst is unsafe

### ISSUE THREAD

**Issue by Blaisorblade** [scalaz/scalaz#838]
`Tag.subst` used to require a `Functor` constraint, with another version requiring a `Contravariant` constraint, even if they were not used. This was safe and simpler than [the GHC story](http://www.seas.upenn.edu/~sweirich/papers/coercible.pdf).

Now, these constraints were all removed in d90a5b568588e44acd35a9d6ae0a4a1baae1aaeb, and I can't navigate from the removal to an explanation. And IIUC, there's none — the original code did not explain why the constraints were necessary even if unused, so somebody decided to just drop them. Removing subtyping in d04ab1f371a17e48aa8b80c5c9a93b35b3aaa20d did not affect this problem.

The problem is tricky — according to the above paper, this is unsafe for *nominal* type parameters — the ones which are used in GADTs (or with associated types, but that does not apply here).

So let's take a simple GADT:
```scala
sealed trait Exp[T]
final case class Pair[A, B](a: Exp[A], b: Exp[B]) extends Exp[(A, B)]
// Other cases omitted
```

Now I usually assume that if `Exp[T]` is a `Pair`, then `T = (A, B)` (right @pchiusano ?), whether or not Scalac happens to figure that out when typechecking code.

So let's take a `Pair[A, B]`, upcast it to `Exp[(A, B)]`, and use subst it to get `Exp[(A, B) @@ BippyTag]` — what's that? Is that ` Pair[C, D]` for some `C`, `D`? It's clearly a Pair, but no `C`, `D` exist. This sounds bad.

I'm not convinced you can actually get a `ClassCastException`, even if you write `interpret[T]: Exp[T] => T` and apply it to a `subst`ed value. I suspect it's a case where multiple wrongs make a right.

But even if you get no `ClassCastException`, the reasons are too subtle for this to belong to Scalaz without comment.

**Comment by S11001001** [comment]
OK, let's add a comment. I'd rather not reintroduce the constraint.

**Comment by Blaisorblade** [comment]
I'm fine with that, thanks for taking action on this :+1:

**Comment by puffnfresh** [comment]
:+1: to reintroducing the constraint.

**Comment by S11001001** [comment]
@Blaisorblade HTH 21b6dbc :)

@puffnfresh fightin' words
