### ISSUE TITLE
type parameters on \/.fromTryCatchThrowable are backwards

### ISSUE THREAD

**Issue by stew** [scalaz/scalaz#863]
It would be more natural if they were in the same order as they are on \/. right now you use \/.fromTryCatchThrowable[A,B] to produce a \/[B,A]

**Comment by S11001001** [comment]
Agreed.

**Comment by jozi-k** [comment]
I believe this issue can be closed as `fromTryCatchThrowable` is deprecated.

**Comment by TomasMikula** [comment]
👍
