### ISSUE TITLE
Order.reverseOrder Should tie the knot

### ISSUE THREAD

**Issue by NightRa** [scalaz/scalaz#870]
Order.reverseOrder.reverseOrder should result in the original order instance.
(It actually is one of the performance bottlenecks in my application right now)
It may also override the other methods in Order - as lessThan, greaterThan and the others,
As computing the ordering is usually more expensive than calling the appropriate comparison function directly.

**Comment by xuwei-k** [comment]
https://github.com/scalaz/scalaz/pull/956
