### ISSUE TITLE
A Traversal over a list runs in reversed list order

### ISSUE THREAD

**Issue by dozed** [scalaz/scalaz#886]
The return value is in correct list order, but the traversal happens in reverse list order. This leads to problems when side-effecting.

```scala
import scalaz._, Scalaz._
def print(x: Int): Option[Int] = { println(x); Some(x) }
List(1, 2, 3) traverseU print
// 3
// 2
// 1
// Option[List[Int]] = Some(List(1, 2, 3))
```

Also see: https://github.com/scalaz/scalaz/blob/series/7.2.x/core/src/main/scala/scalaz/std/List.scala#L41-L57

**Comment by tpolecat** [comment]
I think you're going to run into problems generally in scalaz if you're side-effecting. Try sequencing into a type that captures effects like `IO` or `Task` (or even `Name` or `Function0` in a pinch) and you will find that the effects are sequenced in the expected order.

```scala
scala> List(1,2,3).traverse(a => IO { Console.println(a); Option(a) })
res9: scalaz.effect.IO[List[Option[Int]]] = scalaz.effect.IOFunctions$$anon$6@25599024

scala> res9.unsafePerformIO
1
2
3
res10: List[Option[Int]] = List(Some(1), Some(2), Some(3))
```

**Comment by tonymorris** [comment]
> This leads to problems when side-effecting.

Other way around. Side-effecting leads to problems.

**Comment by dozed** [comment]
I guess it is more a feature than a bug that Traversal does not make any guarantees about the ordering. Closing the issue, thanks.
