### ISSUE TITLE
Releasing 7.2?

### ISSUE THREAD

**Issue by aloiscochard** [scalaz/scalaz#893]
Hey folks,

I was wondering how we feel about cutting a release for 7.2?

As @xuwei-k did one with backport to 7.1, maybe that would be a good time to cut one on the 7.2 series?

**Comment by wedens** [comment]
+1

**Comment by puffnfresh** [comment]
:+1:

What's the release notes gonna look like?

**Comment by xuwei-k** [comment]
Which do you mean, 7.2.0 final or 7.2.0-M1? I think we should release 7.2.0-M1 as soon as possible, but it's a little bit too early to release 7.2.0 final.

**Comment by tonymorris** [comment]
:thumbsup:

What do you think is required for 7.2.0 final?

**Comment by aloiscochard** [comment]
Here is the diff:
https://github.com/scalaz/scalaz/compare/series/7.1.x...series/7.2.x

Personally I'm not waiting eagerly on a 7.2 release, but I heard people asking for it on IRC. A milestone should be enough for them I'll ask for comment.

@xuwei-k +1 about a M1 release

**Comment by vmarquez** [comment]
I think we need to have an RC before we release final, as there could be breaking changes in some of the recent PRs. I know one of mine that hasn't been merged in yet for 7.2 but was added to the roadmap changes the variance of NEL, which could impact some users. 

From my experience talking to casual scala users, Scalaz has the reputation of 'it just works', so I think it's worth being a little extra careful for releases. 

Is the idea that milestones can have incremental changes, and an RC would be final in terms of which issues and PRs it is attempting to push out?  This way we could release a milestone without all PRs scheduled to go in to 7.2 merged in, then cut an RC whenever the rest gets reviewed.

**Comment by S11001001** [comment]
If we do not potentially wish to upgrade a release to a final release with no changes, it oughtn't be called a Release Candidate.

**Comment by vmarquez** [comment]
Any news on this?  I'd be happy to help out in any way (code reviews, additional testing, test against other projects)...

**Comment by xuwei-k** [comment]
>  I think we should release 7.2.0-M1 as soon as possible, but it's a little bit too early to release 7.2.0 final

Personally, I am of the same mind. I want to release 7.2.0-M1 if there is no strong objections, at the moment.

**Comment by aloiscochard** [comment]
+1 for a milestone

I'm afraid I cannot give much help those days as I am very busy with
work...

**Comment by xuwei-k** [comment]
[scalaz 7.2.0-M1 released](https://groups.google.com/d/msg/scalaz/uH28mi3HGww/unhwvBisUS8J)
