### ISSUE TITLE
tuplex monoid instance doest not work with literal values on the right hand side

### ISSUE THREAD

**Issue by MasseGuillaume** [scalaz/scalaz#901]
```scala
val a = (1,1)
(2,2) |+| a // (3,3)
```

```scala
val a = (1,1)
a |+| (2,2) // too many arguments for method |+|: (other: => (Int, Int))(Int, Int)
```

**Comment by ceedubs** [comment]
That second example is being interpreted as `a.|+|(2, 2)`, so it thinks you are trying to pass two arguments to the `|+|` operator.

I believe with the default compiler flags, Scalac will actually auto-tuple the argument for you, which can lead to some big surprises. It's probably good that you have your compiler flags set up such that this doesn't work.

An easy alternative is to use `a |+| (2 -> 2)` or `a |+| ((2, 2))`.

**Comment by ceedubs** [comment]
P.S. for a fun example of how auto-tupling can lead to big surprises, see https://twitter.com/FouriersTrick/status/500023553178468352

**Comment by MasseGuillaume** [comment]
oh that's right, I have 

``` scala
scalacOptions ++= Seq("-Ywarn-numeric-widen", "-Xfatal-warnings")
```

closing this, to fix this we need to fix scala :P

**Comment by MasseGuillaume** [comment]
this works too @ceedubs 

```scala
(1, 1) |+| 1 -> 1 // (2, 2)
```
