### ISSUE TITLE
weakHashMemo not very useful

### ISSUE THREAD

**Issue by tpolecat** [scalaz/scalaz#910]
The doc for this reads

``` scala
  /** As with `mutableHashMapMemo`, but forget elements according to
    * GC pressure.
    */
```

but in fact elements will be forgotten as soon as the memo keys are no longer strongly reachable. So in practice it's likely to mean that this `Memo` never memoizes anything at all.

https://github.com/scalaz/scalaz/blob/series/7.2.x/core/src/main/scala/scalaz/Memo.scala#L78-L82

**Comment by vmarquez** [comment]
I'm not sure they will be forgotten 'immediately', it may only be on the next GC mark phase that they are not 'counted', and will shortly be collected.  There are also 'soft references' which stay around a little longer than Weak References, but no canonical SoftRefMap that I know of.

**Comment by jedws** [comment]
WeakRefs will disappear when the object they are referencing would
disappear, which is somewhat non-deterministic. If the reference is still
in the young generation, then it is likely that it will happen reasonably
quickly (at the next young gen collection). A reference in the older gen
though may last for quite some time.

Note that SoftReferences are pretty terrible for memoisation, as they will
only get cleared when under serious GC pressure, which is usually the worst
time to add further pressure by performing expensive operations to recreate
at that time.

It is usually best on the JVM to address memoisation fairly directly as an
application level concern, trying to hitch a lift on top of the GC
infrastructure has some significant short-comings.

**Comment by tpolecat** [comment]
Agree. A fixed-size LRU memo perhaps.

**Comment by jedws** [comment]
Well, I was trying to say that a WeakRef based memo can actually be quite
useful, as it only keeps things around while they are being kept alive by
some external party, plus a non-deterministic delay until the next relevant
GC event. This means they do not hang around until the entire cache is
cleared.

As to whether or not scalaz should be in the business of writing caches
with configurable retention and eviction policies, I'd argue that it
probably should not, as it seems right outside of its core focus.

**Comment by S11001001** [comment]
#1347
