### ISSUE TITLE
scalaz.org/scalaz.com

### ISSUE THREAD

**Issue by tonymorris** [scalaz/scalaz#916]
Jason Zaugg has kindly transferred these domains.

Suggestions for what to do with them?

**Comment by tonymorris** [comment]
Does anyone want an email address @scalaz.org/com to forward to theirs?

**Comment by relrod** [comment]
Ooh, that would be pretty. I'll take a forward to ricky@elrod.me if you're handing them out.

As far as a site, I'm more than happy to work on a Hakyll site, but I probably won't have much time before the semester is over (so mid-May). If nobody does anything before then, I will gladly start on something.

**Comment by tonymorris** [comment]
ricky or relrod? both?

**Comment by relrod** [comment]
Either relrod or both. Up to you :)

**Comment by S11001001** [comment]
Both forward to Github; fine for now.
