### ISSUE TITLE
`Traverse` and `Applicative` have conflicting signatures for `sequence`, `traverse`

### ISSUE THREAD

**Issue by refried** [scalaz/scalaz#926]
This seems to make it impossible to call with type args:

```scala
// scala 2.11.6, scalaz 7.1.0
import scalaz._, Scalaz._

val x = List(Option(1),Option(2))

listInstance.sequence(x) // ok
listInstance.sequence[Option,Int](x) // error: Int takes no type parameters, expected: one
(listInstance:Traverse[List]).sequence[Option,Int](x) // ok
```

**Comment by S11001001** [comment]
Direct use of the identifier `listInstance` is unsupported, and breaks an important method of fixing illegal instances whilst preserving binary compatibility (cf. where `implicit` keyword was removed in #582).

**Comment by refried** [comment]
Interesting, thanks.
