### ISSUE TITLE
Free's Monad[Free[S, ?]] instance requires a Functor[S], but flatMap doesn't, make them consistent

### ISSUE THREAD

**Issue by jedws** [scalaz/scalaz#936]
the Monad instance for `Free[S, ?]` is defined as requiring a `Functor[S]`, but `flatMap` is not defined with the same constraint, as it uses `gosub` to achieve the same functionality. This means that for compilation, the `Functor[S]` constraint is unused.

    implicit def freeMonad[S[_]:Functor]: Monad[Free[S, ?]]

But, Free as a construction would usually use the Functor to implement this, for instance https://hackage.haskell.org/package/free-4.12.1/docs/src/Control-Monad-Free.html#line-188

There are good cases for both adding the constraint even though it is unused, and for removing it even though it is correct in theoretical terms.

**Comment by runarorama** [comment]
We should have `Free` be the free monad generated by a type construction, not the free monad generated by a functor. These two are isomorphic via the yoneda lemma, but the former goes with the grain of Scala. At the moment `Free` is sort of a half-breed between them and we should fix it.

**Comment by S11001001** [comment]
cf. #937

**Comment by jedws** [comment]
@runarorama I think you said +1 to #937 but I'm not entirely sure :-)

**Comment by runarorama** [comment]
@jedws This is my current thinking on this: https://github.com/scalaz/scalaz/pull/938

**Comment by jedws** [comment]
So, @runarorama's #938 entirely subsumes this issue. Assuming that gets merged this is addressed.
