### ISSUE TITLE
How to get None in an OptionT with MonadTell

### ISSUE THREAD

**Issue by pschorf** [scalaz/scalaz#944]
Hi:

I'm using the MonadTell syntax to use writers with OptionT, but I'm stuck on how to create a new writer with None. The syntax seems to be:
    val tell = OptionT.monadTell[Writer, List[String], List[String]]
    tell.writer(List("Message"), 1)

But value is of type Int, in this case, so I can't see how you would get a none in there. The only other method, tell, returns a Unit monad instead of an Option[Int], so that won't work. Is there a better way to do this I'm missing?

**Comment by justjoheinz** [comment]
I think you can't by using MonadTell directly. I would materialize a MonadPlus instance. This is how I tried, with a breakdown of the types, because I did not have kind projector in the REPL:
```
  type Log = List[String]
  type W[A] = Writer[Log, A]
  type OT[A] = OptionT[W, A]
  val MP = MonadPlus[OT]
  MP.empty[Int]// OptionT(WriterT((List(),None)))
```
