### ISSUE TITLE
Add fromTryCatchThrowable-like semantics to TryFunctions

### ISSUE THREAD

**Issue by torgeirsh** [scalaz/scalaz#945]
scalaz.std.TryFunctions.toDisjunction has semantics that match scalaz.DisjunctionFunctions.fromTryCatchNonFatal. Would it be useful for TryFunctions to have a function that matches the semantics of scalaz.DisjunctionFunctions.fromTryCatchThrowable as well?

**Comment by jozi-k** [comment]
As `fromTryCatchNonFatal/fromTryCatchThrowable` is deprecated, I think you can close this issue.

**Comment by TomasMikula** [comment]
👍
