### ISSUE TITLE
why make object apply method parameter implicit?

### ISSUE THREAD

**Issue by haryzhou** [scalaz/scalaz#951]
most of the object in scalaz has such an apply method(with implicit parameter). 

I just wonder why make the parameter implicit?   in which scenario the apply method will be called with the implict value ?

```
object Plus {
  @inline def apply[F[_]](implicit F: Plus[F]): Plus[F] = F

  ////

  ////
}
```

**Comment by adelbertc** [comment]
The `apply` method found on the type classes is intended to be a (syntactically) nicer way of getting a hold of the type class instance/implicit value.

For instance:

```scala
trait Plus[F[_]] { ... }

implicit val listPlus: Plus[List] = . . .

// Somewhere else
val x: Plus[List] = implicitly[Plus[List]] // long, verbose
```

However..

```scala
trait Plus[F[_]] { ... }

object Plus {
  def apply(implicit F: Plus[F]): Plus[F] = F
}

implicit val listPlus: Plus[List] = . . .

// Somewhere else
val x: Plus[List] = Plus[List] // yay
```

When you do `Plus[List]` (at the value level), it will call the `apply` method on the `Plus` companion object, along with fixing the type parameter to be `List`. It will check to see if an implicit `Plus[List]` is in scope (checking to see if there is a type class instance of `Plus` for `List`) and if it does bind it to the argument `F` (see the implicit args list). It then simply returns that `F`.

You can see `apply` as a more specific version of `implicitly`:

```scala
def implicitly[A](implicit ev: A): A = ev // search for implicit value of any type A
implicitly[Plus[List]]

def getPlus[A](implicit ev: Plus[A]): Plus[A] = ev // given A, search only for Plus[A]
```

Hope that helps!

**Comment by S11001001** [comment]
Most of the `apply` methods work just like that.

However, there are some special cases where you only want to say some of the type parameters, and have the others inferred.  [A typelevel blog explains the problem](http://typelevel.org/blog/2014/01/18/implicitly_existential.html), and [`Unapply.apply` exemplifies the solution](https://github.com/scalaz/scalaz/blob/v7.1.2/core/src/main/scala/scalaz/Unapply.scala#L233-L237) (rewrapped):

```scala
scala> Unapply[Functor, Int \/ String]
res0: scalaz.Unapply[scalaz.Functor,scalaz.\/[Int,String]]{
        type M[X] = scalaz.\/[Int,X];
        type A = String
      }{
        type M[A] = scalaz.\/[Int,A];
        type A = String
      } = scalaz.Unapply_0$$anon$13@66db239a
```

**Comment by haryzhou** [comment]
3ks
