### ISSUE TITLE
Memoization

### ISSUE THREAD

**Issue by igalbenardete** [scalaz/scalaz#958]
When I try to create memoization for a function with less than or more than one arguments, I always get an error.  The first example gives an error where itemIdToEbayItemIdRDD is a function with no arguments.

val memoizedItemIdToEbayItemIdRDD: () => JdbcRDD[ItemIdToEbayItemId] = Memo.mutableHashMapMemo {
    itemIdToEbayItemIdRDD
  }

**Comment by japgolly** [comment]
You can use `scalaz.Need` for this use case.

**Comment by igalbenardete** [comment]
How does that work exactly ?

**Comment by edmundnoble** [comment]
`scalaz.Need` is a container for a call-by-need value. `Need.apply` takes a function that requires no parameters and will evaluate it at most once, then return the same result value after. This is what you can use for a no-argument function.

My recommendation to memoize a multi-argument function would be to take the function you want to use and call `FunctionN.tupled`. Then, the function will take a single argument representing a tuple of its original arguments. For example:
```scala
def multiArgumentFunction(a: Int, b: Int) = a * b
val memoized = Memo.mutableHashMapMemo {
    (multiArgumentFunction _).tupled
}
```

**Comment by S11001001** [comment]
It is also possible that a [`lazy val`](http://www.artima.com/pins1ed/abstract-members.html#i1386009102-1) will suit your use case.  Between that and @edmundnoble's comment, the design space is covered.
