### ISSUE TITLE
Missing withFilter in for comprehensions

### ISSUE THREAD

**Issue by TomasMikula** [scalaz/scalaz#968]
The following definition

```scala
def foo[A, B](m: Maybe[(A, B)]): Maybe[A] =
  for {
    (a, b) <- m
  } yield a
```

does not compile with the following error:

     value withFilter is not a member of scalaz.Maybe[(A, B)]

Can/should this be fixed?

The workaround is

```scala
def foo[A, B](m: Maybe[(A, B)]): Maybe[A] =
  for {
    ab <- m
    (a, b) = ab
  } yield a
```

There is the same problem with other scalaz monads.

**Comment by vmarquez** [comment]
So there's this:

https://github.com/scalaz/scalaz/pull/922 which references https://github.com/scalaz/scalaz/pull/728

But as you can see in 728, @puffnfresh pointed out that this behavior can actually cause scalac to lose some type safety! 

Here's an example: https://github.com/scalaz/scalaz/pull/728#issuecomment-45779363

**Comment by TomasMikula** [comment]
Thanks for the pointers. So the problem seems to be that pattern matching in for-comprehensions translates to `withFilter` at all.
