### ISSUE TITLE
Contravariant implicit resolution issue

### ISSUE THREAD

**Issue by joshcough** [scalaz/scalaz#976]
Hi. For an unknown reason, the implicit for contramap is not properly being resolved for me. I've pasted the code below, and I've also created a github repo for it, so you can easily pull it down and test the bug. It's here: https://github.com/joshcough/contravariant-resolution-issue

If this is not a bug, can you please tell me what I've done wrong, and how to fix it? Thanks.

```scala
import scalaz.Contravariant

trait Go[I,O] { def go(i:I): O }

object Go {

  implicit def GoContravariant[O]: Contravariant[({type l[A]=Go[A,O]})#l] =
    new Contravariant[({type l[A]=Go[A,O]})#l] {
      def contramap[A, B](r: Go[A, O])(f: B => A): Go[B, O] =
        new Go[B, O] { def go(b: B): O = r go f(b) }
    }

  import scalaz.syntax.contravariant._

  val go1 = new Go[String, Int] { def go(a: String) = a.length }
  val go2: Go[List[Char], Int] = go1.contramap { cs: List[Char] => cs.mkString }
}
```

**Comment by edmundnoble** [comment]
It looks like you'll need to use Unapply here. If your method needs to know about an implicit instance of a typeclass TC for fully applied type MA, make your method accept an implicit parameter of type Unapply[TC, MA] and you'll be fine. I'd try to fix it for you, but I'm out right now; for examples, you can look at the sequenceU method in the scalaz source and this link: http://eed3si9n.com/learning-scalaz/Unapply.html.

**Comment by jedws** [comment]
to further explain Unapply, please see Stephen Compall's great article:
http://typelevel.org/blog/2013/09/11/using-scalaz-Unapply.html

**Comment by S11001001** [comment]
@edmundnoble @jedws That doesn't characterize this situation.

The expected usage of `Unapply` is the implicit conversion of `go1` via `ToContravariantOpsUnapply`, as for `Function1` in the following Scala 2.11.7, scalaz 7.1.3 example (because `Go` has the same arity and same contravariant position, so `unapplyMAB1` should be found):

```scala
scala> import scalaz.Contravariant, scalaz.std.function._, scalaz.syntax.contravariant._

scala> :type (??? : String => Int) contramap {cs: List[Char] => cs.mkString}
List[Char] => Int

scala> reflect.runtime.universe.reify{(??? : String => Int) contramap {cs: List[Char] => cs.mkString}}
res1: reflect.runtime.universe.Expr[List[Char] => Int] = 
  Expr[scala.List[Char] => Int](
    `package`.contravariant.ToContravariantOpsUnapply
      ((Predef.$qmark$qmark$qmark: Function1[Predef.String, Int]))
      (Unapply.unapplyMAB1(function.function1Contravariant))
    .contramap(((cs: `package`.List[Char]) => cs.mkString)))
```

@joshcough I added a type annotation to `go1` and your sample worked:

```scala
  val go1: Go[String, Int] = new Go[String, Int] { def go(a: String) = a.length }
```

¯\\\_(ツ)\_/¯ Scala
